import * as moment from 'moment';
import { Plugin } from '../model/plugin';
import { Template } from '../model/template';

export const aiQueryPlugin: Plugin = {
  tag: 'plugin/inbox/ai',
  name: $localize`👻️💭️ Ask AI`,
  config: {
    mod: $localize`👻️ AI Chat`,
    type: 'tool',
    default: false,
    add: true,
    submitText: true,
    signature: '+plugin/openai',
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    description: $localize`Send this Ref to the ai for response.`,
    icons: [{ label: $localize`👻️💭️`, order: -1 }],
    filters: [
      { query: 'plugin/inbox/ai', label: $localize`👻️💭️ ai query`, group: $localize`Notifications ✉️` },
    ],
    advancedActions: [
      { tag: 'plugin/inbox/ai', labelOff: $localize`ask ai`, global: true }
    ],
  },
  schema: {
    optionalProperties: {
      exts: { elements: { type: 'string' } },
    }
  }
};

export const aiPlugin: Plugin = {
  tag: '+plugin/openai',
  name: $localize`👻️ OpenAI`,
  config: {
    mod: $localize`👻️ AI Chat`,
    type: 'tool',
    default: false,
    signature: '+plugin/openai',
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    icons: [{ thumbnail: $localize`👻️`, order: 1 }],
    filters: [
      { query: '+plugin/openai', label: $localize`👻️ ai`, group: $localize`Plugins 🧰️` },
    ],
    reply: ['plugin/inbox/ai'],
    description: $localize`AI signature tag. Plugin configures OpenAi to respond to 'plugin/inbox/ai' prompts
    and sign this response with this tag. Plugin data contains token usage stats.`,
    model: 'gpt-4-1106-preview',
    fallback: ['gpt-4'],
    maxTokens: 4096,
    maxContext: 7,
    systemPrompt: $localize`
Your inbox is tag plugin/inbox/ai.
You are a helpful research assistant in a private database codenamed Jasper.
Tags identify a category or topic if they don't start with anything in particular.
The plugin/inbox/ai tag is used to send the Ref as a prompt to an AI (like you).
The +plugin/openai tag is your signature, it is added to indicate the Ref was authored by you.
Use markdown to format your response.
Hashtags and user mentions will replace the link text with whatever their Ext name is, if available.
If you include a diagram in your response, use mermaid to draw it. Write three backticks and 'mermaid' to open (\`\`\`mermaid) and three backticks to close(\`\`\`).
For example:
\`\`\`mermaid
graph TB
    Start -->|Both Cooperate| BothWin{Both Win}
    Start -->|Both Defect| BothLose{Both Lose}
    Start -->|P1 Cooperates, P2 Defects| P2Wins{P2 Wins, P1 Loses}
    Start -->|P1 Defects, P2 Cooperates| P1Wins{P1 Wins, P2 Loses}
\`\`\`
You can reply with multiple Refs and request help from another assistant by tagging with plugin/inbox/ai.
Responses sent to you will only include direct sources plus 7 levels of ancestors.
Be sure to only respond to the last Ref sent to you, the others are just for context.
`,
  },
  schema: {},
  generateMetadata: true,
};

export const aiTemplate: Template = {
  tag: 'plugin/openai',
  name: $localize`👻️ OpenAI`,
  config: {
    mod: $localize`👻️ AI Chat`,
    type: 'tool',
  },
  defaults: {
    dms: 'plugin/inbox/ai',
  }
};
