import * as moment from 'moment';
import { Plugin } from '../model/plugin';
import { Mod } from '../model/tag';

export const audioPlugin: Plugin = {
  tag: 'plugin/audio',
  name: '📻️ Audio',
  config: {
    type: 'plugin',
    default: true,
    cache: true,
    add: true,
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    submit: $localize`📻️ audio`,
    icons: [{ label: $localize`📻️`, order: 2 }],
    filters: [
      { query: 'plugin/audio', label: $localize`📻️ audio`, group: $localize`Plugins 🧰️` },
    ],
    extensions: ['.mp3', '.aac', '.flac', '.m4a', '.ogg', '.wav'],
    description: $localize`Play in an inline audio player.`,
    advancedForm: [{
      key: 'url',
      type: 'audio',
      props: {
        label: $localize`URL:`,
      },
    }],
  },
  defaults: {},
  schema: {
    optionalProperties: {
      url: { type: 'string' },
    },
  },
};

export const audioMod: Mod = {
  plugins: {
    audioPlugin,
  },
};
