import { DateTime } from 'luxon';
import { Mod } from '../model/tag';
import { Template } from '../model/template';

export const banlistConfig: Template = {
  tag: 'config/banlist',
  name: $localize`🚫️ Banlist`,
  config: {
    type: 'config',
    default: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    bannedUrls: [
      '//bit.ly/',
      '//ow.ly/',
      '//tinyurl.com/',
      '//is.gd/',
      '//buff.ly/',
      '//adf.ly/',
      '//bit.do/',
      '//mcaf.ee/',
      '//su.pr/',
    ],
    expandShorteners: {
      'https://youtu.be/': 'https://www.youtube.com/watch?v=',
      'https://m.youtube.com/': 'https://www.youtube.com/',
      'https://youtube.com/': 'https://www.youtube.com/',
    },
    stripTrackers: [
      '//x.com/',
      '//twitter.com/',
      '//www.youtube.com/',
      '//www.amazon.',
    ],
  },
};

export const banlistMod: Mod = {
  template: [
    banlistConfig,
  ]
};
