import * as moment from 'moment';
import { Template } from '../model/template';

export const banlistConfig: Template = {
  tag: 'banlist',
  name: $localize`🚫️ Banlist`,
  config: {
    type: 'config',
    default: true,
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    bannedUrls: [
      '//bit.ly/',
      '//ow.ly/',
      '//tinyurl.com/',
      '//is.gd/',
      '//buff.ly/',
      '//adf.ly/',
      '//bit.do/',
      '//mcaf.ee/',
      '//su.pr/',
    ]
  },
};

