import { DateTime } from 'luxon';
import { Plugin } from '../model/plugin';
import { Mod } from '../model/tag';

export const userClipboardPlugin: Plugin = {
  tag: 'plugin/user/clipboard',
  name: $localize`📋️ Clipboard`,
  config: {
    mod: $localize`📋️ Clipboard`,
    version: 1,
    settings: $localize`clipboard`,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Adds a multi-item in-browser clipboard stored locally and in your user URL Ref.`,
    internal: true,
    form: [{
      key: 'interceptCopy',
      type: 'boolean',
      props: {
        label: $localize`Intercept Copy:`,
        title: $localize`Send copy commands to the Jasper clipboard instead of the system clipboard.`,
      },
    }, {
      key: 'interceptPaste',
      type: 'boolean',
      props: {
        label: $localize`Intercept Paste:`,
        title: $localize`Send paste commands from the Jasper clipboard instead of the system clipboard.`,
      },
    }],
  },
  defaults: {
    interceptCopy: false,
    interceptPaste: false,
  },
  schema: {
    optionalProperties: {
      interceptCopy: { type: 'boolean' },
      interceptPaste: { type: 'boolean' },
      items: {
        elements: {
          properties: {
            id: { type: 'string' },
            text: { type: 'string' },
            created: { type: 'string' },
            x: { type: 'float64' },
            y: { type: 'float64' },
          },
          optionalProperties: {
            hold: { type: 'boolean' },
          },
        },
      },
    },
  },
};

export const clipboardMod: Mod = {
  plugin: [
    userClipboardPlugin,
  ],
};
