import { DateTime } from 'luxon';
import { Plugin } from '../model/plugin';
import { Mod } from '../model/tag';

export const userClipboardPlugin: Plugin = {
  tag: 'plugin/user/clipboard',
  name: $localize`📋️ Clipboard`,
  config: {
    mod: $localize`📋️ Clipboard`,
    version: 1,
    settings: $localize`clipboard`,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Adds a multi-item in-browser clipboard stored locally and in your user URL Ref.`,
    internal: true,
    actions: [{
      event: 'clip',
      label: $localize`clip`,
      title: $localize`Add this Ref to the clipboard.`,
      global: true,
    }],
    form: [{
      key: 'interceptCopy',
      type: 'boolean',
      props: {
        label: $localize`Intercept Copy:`,
        title: $localize`Send copy commands to the Jasper clipboard instead of the system clipboard.`,
      },
    }, {
      key: 'interceptPaste',
      type: 'boolean',
      props: {
        label: $localize`Intercept Paste:`,
        title: $localize`Send paste commands from the Jasper clipboard instead of the system clipboard.`,
      },
    }],
  },
  defaults: {
    interceptCopy: false,
    interceptPaste: false,
  },
  schema: {
    optionalProperties: {
      interceptCopy: { type: 'boolean' },
      interceptPaste: { type: 'boolean' },
      items: {
        elements: {
          properties: {
            id: { type: 'string' },
            created: { type: 'string' },
          },
          optionalProperties: {
            text: { type: 'string' },
            html: { type: 'string' },
            image: { type: 'string' },
            ref: {
              properties: {
                url: { type: 'string' },
              },
              optionalProperties: {
                origin: { type: 'string' },
                title: { type: 'string' },
              },
            },
          },
        },
      },
    },
  },
};

export const clipboardMod: Mod = {
  plugin: [
    userClipboardPlugin,
  ],
};
