import { DateTime } from 'luxon';
import { Plugin } from '../model/plugin';

export const commentPlugin: Plugin = {
  tag: 'plugin/comment',
  name: $localize`💬️ Comment`,
  config: {
    mod: $localize`💬️ Comment`,
    type: 'plugin',
    default: true,
    genId: true,
    internal: true,
    reply: ['internal', 'plugin/comment'],
    responseButton: $localize`💬️`,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Activates built-in comment support and allows users to create comments.`,
    aiInstructions: `# plugin/comment
    The plugin/comment tag indicates the Ref represents a comment on it's source.`,
    icons: [{ thumbnail: $localize`💬️`, order: 1 }],
    filters: [
      { query: 'plugin/comment', label: $localize`💬️ comments`, title: $localize`Comments`, group: $localize`Plugins 🧰️` },
    ],
  },
  generateMetadata: true,
};
