import * as moment from 'moment';
import { Plugin } from '../model/plugin';

export const commentPlugin: Plugin = {
  tag: 'plugin/comment',
  name: $localize`💬️ Comment`,
  config: {
    type: 'plugin',
    default: true,
    genId: true,
    internal: true,
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    description: $localize`Activates built-in comment support and allows users to create comments.`,
    icons: [{ thumbnail: $localize`💬️`, order: 1 }],
    filters: [
      { query: 'plugin/comment', label: $localize`💬️ comments`, group: $localize`Plugins 🧰️` },
    ],
    reply: ['internal', 'plugin/comment'],
  },
  generateMetadata: true,
};
