import * as moment from 'moment';
import { Plugin } from '../model/plugin';

export const cronPlugin: Plugin = {
  tag: '+plugin/cron',
  name: $localize`⏱️ Scheduler`,
  config: {
    default: true,
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    icons: [{ label: $localize`⏱️`, order: -3 }],
    description: $localize`Schedule scripts to be run on the server at specific intervals.`,
    form: [{
      key: 'interval',
      type: 'duration',
      defaultValue: 'PT15M',
    }],
  },
  defaults: {
    interval: 'PT15M',
  },
  schema: {
    properties: {
      interval: { type: 'string' },
    },
  },
};
