import { $localize } from '@angular/localize/init';
import * as moment from 'moment';
import { Plugin } from '../model/plugin';
import { Ref } from '../model/ref';
import { Tag } from '../model/tag';

export const deletePlugin: Plugin = {
  tag: 'plugin/delete',
  name: $localize`🗑️ Delete Notice`,
  config: {
    internal: true,
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    description: $localize`Activates built-in delete notice support which clears refs and marks them as deleted instead of actually deleting them.`,
    icons: [{ thumbnail: $localize`🗑️`, order: -1 }],
    filters: [
      { query: 'plugin/delete', label: $localize`🗑️ deleted`, group: $localize`Filters 🕵️️` },
    ],
  },
};

export function deleteNotice(ref: Ref): Ref {
  return {
    url: ref.url,
    origin: ref.origin,
    tags: ['plugin/delete', 'internal'],
    created: ref.created,
    published: ref.published,
    modifiedString: ref.modifiedString,
  };
}

export function tagDeleteNotice(tag: Tag) {
  return {
    tag: tag.tag + '/deleted',
    origin: tag.origin,
    config: {},
  };
}
