import { DateTime } from 'luxon';
import { Plugin } from '../model/plugin';
import { refSchema } from '../model/ref';
import { Mod } from '../model/tag';
import { Template } from '../model/template';

export const editingPlugin: Plugin = {
  tag: 'plugin/editing',
  name: $localize`📝️ Editing`,
  config: {
    mod: $localize`🎬️ Drafts`,
    type: 'plugin',
    default: true,
    view: $localize`📝️`,
    inbox: $localize`drafts`,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Save edits to a plugin before publishing.`,
    embeddable: true,
    icons: [{ thumbnail: $localize`📝️`, order: 1 }],
    filters: [
      { query: 'plugin/editing', label: $localize`📝️ editing`, title: $localize`Drafts`, group: $localize`Plugins 🧰️` },
    ],
    actions: [
      { tag: 'plugin/editing', labelOn: $localize`revert`, title: $localize`Revert pending edits to this Ref`, confirm: $localize`Are you sure?` },
      { tag: 'plugin/delta/commit', labelOff: $localize`commit`, title: $localize`Save pending edits to this Ref`, confirm: $localize`Are you sure?` },
    ],
  },
  schema: refSchema,
};

export const commitPlugin: Plugin = {
  tag: 'plugin/delta/commit',
  name: $localize`🐢️ Commit`,
  config: {
    mod: $localize`🎬️ Drafts`,
    type: 'plugin',
    default: true,
    actions: [
      { tag: 'plugin/delta/commit', labelOn: $localize`cancel`, title: $localize`Cancel committing edits to this Ref` },
    ],
    timeoutMs: 30_000,
    language: 'javascript',
    // language=JavaScript
    script: `
      const axios = require('axios');
      const ref = JSON.parse(require('fs').readFileSync(0, 'utf-8'));
      if (ref?.tags?.find(t => t === 'plugin/editing' || t?.startsWith('plugin/editing/'))) {
        const editPlugin = ref.plugins['plugin/editing'];
        delete ref.plugins['plugin/editing'];
        delete ref.metadata;
        ref.tags = ref.tags
          .filter(t => t !== 'plugin/editing' && !t.startsWith('plugin/editing/'))
          .filter(t => t !== 'plugin/delta/commit' && !t.startsWith('plugin/delta/commit/'));
        const edit = {
          ...ref,
          ...editPlugin,
          url: ref.url,
        };
        delete edit.metadata;
        const author = ref.tags.find(tag => tag === '+user' || tag === '_user' || tag.startsWith('+user/') || tag.startsWith('_user/'));
        if (!author) throw new Error('No author tag found');
        await axios.post(process.env.JASPER_API + '/pub/api/v1/repl/ref', [edit], {
          headers: {
            'Local-Origin': ref.origin || 'default',
            'User-Tag': author,
          },
          params: {
            origin: ref.origin,
          }
        }).catch(e => {
          console.error(e.response.data);
          throw new Error(e);
        });
      }
    `,
  }
}

export const draftMod: Mod = {
  plugin: [
    editingPlugin,
    commitPlugin,
  ],
};
