import { DateTime } from 'luxon';
import { Plugin } from '../model/plugin';
import { refSchema } from '../model/ref';
import { Mod } from '../model/tag';

export const editingPlugin: Plugin = {
  tag: 'plugin/editing',
  name: $localize`📝️ Editing`,
  config: {
    mod: $localize`📝️ Editing`,
    type: 'plugin',
    default: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Save edits to a plugin before publishing.`,
    icons: [{ thumbnail: $localize`📝️`, order: 1 }],
  },
  schema: refSchema,
};

export const editingMod: Mod = {
  plugin: [
    editingPlugin,
  ],
};
