import { DateTime } from 'luxon';
import { Plugin } from '../model/plugin';
import { Mod } from '../model/tag';

export const filePlugin: Plugin = {
  tag: 'plugin/file',
  name: $localize`💾️️ File`,
  config: {
    default: true,
    mod: $localize`💾️️ File Cache`,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    aiInstructions: ` # plugin/file
    The file plugin indicates a Ref contains a file. It is used with the
    cache plugin (_plugin/cache) to refer to a user generated file stored in
    this server's file cache.
    You may refer to a file you returned with the URL ai:part, or optionally
    multiple returned assets as ai:part1, ai:part2, etc. These will be uploaded
    to the cache and the URL will be rewritten with it's cache URL.
    `,
    icons: [{ label: $localize`💾️️`, order: 1 }],
    description: $localize`Allow storing user files on the server.`,
    filters: [
      { query: 'plugin/file', label: $localize`💾️️ file`, title: $localize`Uploaded Files`, group: $localize`Plugins 🧰️` },
    ],
  },
};

export const fileMod: Mod = {
  plugin: [
    filePlugin,
  ]
};
