import * as moment from 'moment';
import { Template } from '../model/template';

export const graphConfig: Template = {
  tag: 'graph',
  name: $localize`🎇️ Graph`,
  config: {
    type: 'template',
    default: true,
    global: true,
    view: $localize`graph`,
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    description: $localize`Activates built-in graph support and allows users to create graphs.`,
  },
};
