import { DateTime } from 'luxon';
import { Mod } from '../model/tag';
import { Template } from '../model/template';

export const gridTemplate: Template = {
  tag: 'grid',
  name: $localize`☰ Grid`,
  config: {
    mod: $localize`☰ Grid`,
    type: 'lens',
    default: true,
    global: true,
    view: $localize`☰`,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    submit: $localize`☰ grid/`,
    description: $localize`Activates built-in grid viewer mode for viewing Refs.`,
    filters: [
      { query: 'grid', label: $localize`☰ grid`, group: $localize`Templates 🎨️` },
    ],
    form: [{
      key: 'columnDefs',
      type: 'list',
      props: {
        label: $localize`Columns:`,
        addText: $localize`+ Add another column`,
      },
      fieldArray: {
        fieldGroup: [{
          key: 'headerName',
          type: 'string',
          props: {
            label: $localize`Header Name:`,
          },
        }, {
          key: 'field',
          type: 'string',
          props: {
            label: $localize`Field:`,
          },
        }, {
          key: 'type',
          type: 'select',
          defaultValue: '',
          props: {
            label: $localize`Type:`,
            options: [
              { value: '' },
              { value: 'text', label: $localize`Text` },
              { value: 'number', label: $localize`Number` },
              { value: 'boolean', label: $localize`Boolean` },
              { value: 'date', label: $localize`Date` },
              { value: 'dateString', label: $localize`Date (String)` },
              { value: 'dateTime', label: $localize`Date Time` },
              { value: 'dateTimeString', label: $localize`Date Time (String)` },
            ],
          }
        }]
      },
    }]
  },
  schema: {
    optionalProperties: {
      columnDefs: {
        elements: {
          optionalProperties: {
            headerName: { type: 'string' },
            field: { type: 'string' },
            type: { type: 'string' },
          }
        }
      }
    }
  },
  defaults: {
    submitText: true,
    noFloatingSidebar: true,
    columnDefs: [
      { headerName: $localize`Title`, field: 'title' },
      { headerName: $localize`Comment`, field: 'comment' },
      { headerName: $localize`Published`, field: 'published', type: 'dateTime' },
    ],
  }
};


export const gridMod: Mod = {
  template: [
    gridTemplate,
  ]
};
