import { $localize } from '@angular/localize/init';
import * as moment from 'moment/moment';
import { Template } from '../model/template';

export const gridTemplate: Template = {
  tag: 'grid',
  name: $localize`☰ Grid`,
  config: {
    mod: $localize`☰ Grid`,
    type: 'lens',
    default: true,
    global: true,
    view: $localize`grid`,
    generated: 'Generated by jasper-ui ' + moment().toISOString(),
    description: $localize`Activates built-in grid viewer mode for viewing Refs.`,
    icons: [{ thumbnail: $localize`☰`, order: 1 }],
    filters: [
      { query: 'grid', label: $localize`☰ grid`, group: $localize`Templates 🎨️` },
    ],
  },
  schema: {
    optionalProperties: {
      columnDefs: {
        elements: {
          optionalProperties: {
            headerName: { type: 'string' },
            field: { type: 'string' },
          }
        }
      }
    }
  },
  defaults: {
    hideEdit: true,
    disableResize: true,
  }
};
