import { DateTime } from 'luxon';
import { Mod } from '../model/tag';
import { Template } from '../model/template';

export const gridTemplate: Template = {
  tag: 'grid',
  name: $localize`☰ Grid`,
  config: {
    mod: $localize`☰ Grid`,
    type: 'lens',
    default: true,
    global: true,
    view: $localize`☰`,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    submit: $localize` grid/`,
    description: $localize`Activates built-in grid viewer mode for viewing Refs.`,
    filters: [
      { query: 'grid', label: $localize`☰ grid`, group: $localize`Templates 🎨️` },
    ],
  },
  schema: {
    optionalProperties: {
      columnDefs: {
        elements: {
          optionalProperties: {
            headerName: { type: 'string' },
            field: { type: 'string' },
            type: { type: 'string' },
          }
        }
      }
    }
  },
  defaults: {
    hideEdit: true,
    disableResize: true,
    noFloatingSidebar: true,
    columnDefs: [
      { headerName: $localize`Title`, field: 'title' },
      { headerName: $localize`Comment`, field: 'comment' },
      { headerName: $localize`Published`, field: 'published' },
    ],
  }
};


export const gridMod: Mod = {
  template: [
    gridTemplate,
  ]
};
