import * as moment from 'moment';
import { Template } from '../model/template';

export const homeTemplate: Template = {
  tag: 'home',
  name: $localize`🏡️ Home Page`,
  config: {
    type: 'config',
    default: true,
    generated: 'Generated by jasper-ui ' + moment().toISOString(),
    description: $localize`Customise this Ext to customise the home screen.`,
  },
};
