import { DateTime } from 'luxon';
import { Template } from '../model/template';

export const htmlToMarkdownConfig: Template = {
  tag: 'html.markdown',
  name: $localize`⬇️ Markdown Converter`,
  config: {
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Add button to editor to convert HTML into Markdown.`,
  },
};
