import { $localize } from '@angular/localize/init';
import * as moment from 'moment';
import { Template } from '../model/template';
import { RootConfig } from './root';

export const kanbanTemplate: Template = {
  tag: 'kanban',
  name: $localize`📋️ Kanban Board`,
  config: {
    type: 'template',
    default: true,
    generated: 'Generated by jasper-ui ' + moment().toISOString(),
    submit: $localize`📋️ kanban/`,
    view: $localize`📋️`,
    description: $localize`Activates built-in Kanban mode for viewing Refs.`,
    filters: [
      { query: 'kanban', label: $localize`📋️ kanban`, group: $localize`Templates 🎨️` },
    ],
    form: [{
      key: 'columns',
      className: 'columns',
      type: 'tags',
      props: {
        label: $localize`Columns:`,
        addText: $localize`+ Add another column`,
      }
    }, {
      key: 'showNoColumn',
      id: 'showNoColumn',
      type: 'boolean',
      props: {
        label: $localize`Extra column for untagged Refs:`
      }
    }, {
      key: 'noColumnTitle',
      id: 'noColumnTitle',
      type: 'string',
      props: {
        label: $localize`Extra Column Title:`
      },
      expressions: {
        hide: '!field.parent.model.showNoColumn'
      },
    }, {
      key: 'swimLanes',
      className: 'swim-lanes',
      type: 'tags',
      props: {
        label: $localize`Swim Lanes:`,
        addText: $localize`+ Add another swim lane`,
      }
    }, {
      key: 'showNoSwimLane',
      id: 'showNoSwimLane',
      type: 'boolean',
      props: {
        label: $localize`Extra swim lane for untagged Refs:`
      },
      expressions: {
        hide: '!model.swimLanes || !model.swimLanes[0]'
      },
    }, {
      key: 'noSwimLaneTitle',
      id: 'noSwimLaneTitle',
      type: 'string',
      props: {
        label: $localize`Extra Swim Lane Title:`
      },
      expressions: {
        hide: '!model.swimLanes || !model.swimLanes[0] || !model.showNoSwimLane'
      },
    }, {
      key: 'hideSwimLanes',
      id: 'hideSwimLanes',
      type: 'boolean',
      props: {
        label: $localize`Hide Swim Lanes by Default:`
      },
      expressions: {
        hide: '!model.swimLanes || !model.swimLanes[0]'
      },
    }, {
      key: 'badges',
      className: 'badges',
      type: 'tags',
      props: {
        label: $localize`Badges:`,
        addText: $localize`+ Add another badge tag`,
      }
    }]
  },
  defaults: <KanbanConfig> {
    defaultSort: 'modified,desc',
    submitText: true,
    columns: [],
    badges: ['p1', 'p2', 'p3', 'p4', 'p5']
  },
  schema: {
    properties: {
      columns: { elements: { type: 'string' } },
    },
    optionalProperties: {
      swimLanes: { elements: { type: 'string' } },
      hideSwimLanes: { type: 'boolean'},
      showNoColumn: { type: 'boolean'},
      noColumnTitle: { type: 'string'},
      showNoSwimLane: { type: 'boolean'},
      noSwimLaneTitle: { type: 'string'},
      badges: { elements: { type: 'string' } },
    },
  },
};

export interface KanbanConfig extends RootConfig {
  columns: string[];
  swimLanes?: string[];
  hideSwimLanes?: boolean;
  showNoColumn?: boolean;
  noColumnTitle?: string;
  showNoSwimLane?: boolean;
  noSwimLaneTitle?: string;
  badges?: string[];
}
