import { type StyleSpecification } from '@maplibre/maplibre-gl-style-spec';
import { Feature } from 'geojson';
import { DateTime } from 'luxon';
import { Plugin } from '../model/plugin';
import { Ref } from '../model/ref';
import { Mod } from '../model/tag';
import { Template } from '../model/template';

export const mapTemplate: Template = {
  tag: 'map',
  name: $localize`🗺️ Map`,
  config: {
    type: 'lens',
    mod: $localize`🗺️ Map`,
    default: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    global: true,
    submit: $localize`🗺️ map/`,
    view: $localize`🗺️`,
    tab: $localize`map`,
    description: $localize`Activates built-in map mode for viewing Refs on a map.`,
    filters: [
      { query: 'map', label: $localize`🗺️ map`, group: $localize`Templates 🎨️` },
    ],
    mapStyle: <StyleSpecification> {
      version: 8,
      glyphs: 'https://demotiles.maplibre.org/font/{fontstack}/{range}.pbf',
      sources: {
        maplibre: {
          url: 'https://demotiles.maplibre.org/tiles/tiles.json',
          type: 'vector'
        },
      },
      layers: [{
        id: 'background',
        type: 'background',
        paint: {
          'background-color': '#D8F2FF'
        },
        filter: ['all'],
        layout: {
          visibility: 'visible'
        },
        maxzoom: 24
      },
      {
        id: 'coastline',
        type: 'line',
        paint: {
          'line-blur': 0.5,
          'line-color': '#198EC8',
          'line-width': {
            'stops': [[0, 2], [6, 6], [14, 9], [22, 18]]
          }
        },
        filter: ['all'],
        layout: {
          'line-cap': 'round',
          'line-join': 'round',
          visibility: 'visible'
        },
        source: 'maplibre',
        maxzoom: 24,
        minzoom: 0,
        'source-layer': 'countries'
      },
      {
        id: 'countries-fill',
        type: 'fill',
        paint: {
          'fill-color': ['match',
            ['get', 'ADM0_A3'],
            ['ARM', 'ATG', 'AUS', 'BTN', 'CAN', 'COG', 'CZE', 'GHA', 'GIN', 'HTI', 'ISL', 'JOR', 'KHM', 'KOR', 'LVA', 'MLT', 'MNE', 'MOZ', 'PER', 'SAH', 'SGP', 'SLV', 'SOM', 'TJK', 'TUV', 'UKR', 'WSM'],
            '#D6C7FF',
            ['AZE', 'BGD', 'CHL', 'CMR', 'CSI', 'DEU', 'DJI', 'GUY', 'HUN', 'IOA', 'JAM', 'LBN', 'LBY', 'LSO', 'MDG', 'MKD', 'MNG', 'MRT', 'NIU', 'NZL', 'PCN', 'PYF', 'SAU', 'SHN', 'STP', 'TTO', 'UGA', 'UZB', 'ZMB'],
            '#EBCA8A',
            ['AGO', 'ASM', 'ATF', 'BDI', 'BFA', 'BGR', 'BLZ', 'BRA', 'CHN', 'CRI', 'ESP', 'HKG', 'HRV', 'IDN', 'IRN', 'ISR', 'KNA', 'LBR', 'LCA', 'MAC', 'MUS', 'NOR', 'PLW', 'POL', 'PRI', 'SDN', 'TUN', 'UMI', 'USA', 'USG', 'VIR', 'VUT'],
            '#C1E599',
            ['ARE', 'ARG', 'BHS', 'CIV', 'CLP', 'DMA', 'ETH', 'GAB', 'GRD', 'HMD', 'IND', 'IOT', 'IRL', 'IRQ', 'ITA', 'KOS', 'LUX', 'MEX', 'NAM', 'NER', 'PHL', 'PRT', 'RUS', 'SEN', 'SUR', 'TZA', 'VAT'],
            '#E7E58F',
            ['AUT', 'BEL', 'BHR', 'BMU', 'BRB', 'CYN', 'DZA', 'EST', 'FLK', 'GMB', 'GUM', 'HND', 'JEY', 'KGZ', 'LIE', 'MAF', 'MDA', 'NGA', 'NRU', 'SLB', 'SOL', 'SRB', 'SWZ', 'THA', 'TUR', 'VEN', 'VGB'],
            '#98DDA1',
            ['AIA', 'BIH', 'BLM', 'BRN', 'CAF', 'CHE', 'COM', 'CPV', 'CUB', 'ECU', 'ESB', 'FSM', 'GAZ', 'GBR', 'GEO','KEN', 'LTU', 'MAR', 'MCO', 'MDV', 'NFK', 'NPL', 'PNG', 'PRY', 'QAT', 'SLE', 'SPM', 'SYC', 'TCA', 'TKM', 'TLS', 'VNM', 'WEB', 'WSB', 'YEM', 'ZWE'],
            '#83D5F4',
            ['ABW', 'ALB', 'AND', 'ATC', 'BOL', 'COD', 'CUW', 'CYM', 'CYP', 'EGY', 'FJI', 'GGY', 'IMN', 'KAB', 'KAZ', 'KWT', 'LAO', 'MLI', 'MNP', 'MSR', 'MYS', 'NIC', 'NLD', 'PAK', 'PAN', 'PRK', 'ROU', 'SGS', 'SVN', 'SWE', 'TGO', 'TWN', 'VCT', 'ZAF'],
            '#B1BBF9',
            ['ATA', 'GRL'],
            '#FFFFFF',
            '#EAB38F'
          ]
        },
        filter: ['all'],
        layout: {
          visibility: 'visible'
        },
        source: 'maplibre',
        maxzoom: 24,
        'source-layer': 'countries'
      },
      {
        id: 'countries-boundary',
        type: 'line',
        paint: {
          'line-color': 'rgba(255, 255, 255, 1)',
          'line-width': {
            'stops': [[1, 1], [6, 2], [14, 6], [22, 12]]
          },
          'line-opacity': {
            'stops': [[3, 0.5], [6, 1]]
          }
        },
        layout: {
          'line-cap': 'round',
          'line-join': 'round',
          visibility: 'visible'
        },
        source: 'maplibre',
        maxzoom: 24,
        'source-layer': 'countries'
      },
      {
        id: 'geolines',
        type: 'line',
        paint: {
          'line-color': '#1077B0',
          'line-opacity': 1,
          'line-dasharray': [3, 3]
        },
        filter: ['all', ['!=', 'name', 'International Date Line']],
        layout: {
          visibility: 'visible'
        },
        source: 'maplibre',
        maxzoom: 24,
        'source-layer': 'geolines'
      },
      {
        id: 'geolines-label',
        type: 'symbol',
        paint: {
          'text-color': '#1077B0',
          'text-halo-blur': 1,
          'text-halo-color': 'rgba(255, 255, 255, 1)',
          'text-halo-width': 1
        },
        filter: ['all', ['!=', 'name', 'International Date Line']],
        layout: {
          'text-font': [
            'Open Sans Semibold'
          ],
          'text-size': {
            'stops': [[2, 12], [6, 16]]
          },
          'text-field': '{name}',
          visibility: 'visible',
          'symbol-placement': 'line'
        },
        source: 'maplibre',
        maxzoom: 24,
        minzoom: 1,
        'source-layer': 'geolines'
      },
      {
        id: 'countries-label',
        type: 'symbol',
        paint: {
          'text-color': 'rgba(8, 37, 77, 1)',
          'text-halo-blur': {
            'stops': [[2, 0.2], [6, 0]]
          },
          'text-halo-color': 'rgba(255, 255, 255, 1)',
          'text-halo-width': {
            'stops': [[2, 1], [6, 1.6]]
          }
        },
        filter: ['all'],
        layout: {
          'text-font': [
            'Open Sans Semibold'
          ],
          'text-size': {
            'stops': [[2, 10], [4, 12], [6, 16]]
          },
          'text-field': {
            'stops': [[2, '{ABBREV}'], [4, '{NAME}']]
          },
          visibility: 'visible',
          'text-max-width': 10,
          'text-transform': {
            'stops': [[0, 'uppercase'], [2, 'none']]
          }
        },
        source: 'maplibre',
        maxzoom: 24,
        minzoom: 2,
        'source-layer': 'centroids'
      }],
      center: [-64, 45],
      zoom: 6,
      bearing: 0,
      pitch: 0,
      roll: 0,
      elevation: 0,
      // Constraints
      minZoom: 0,
      maxZoom: 22,
      minPitch: 0,
      maxPitch: 60,
      // Interaction options
      interactive: true,
      hash: false,
      bearingSnap: 7,
      zoomSnap: 0,
      clickTolerance: 3,
      scrollZoom: true,
      boxZoom: true,
      dragRotate: true,
      dragPan: true,
      keyboard: true,
      doubleClickZoom: true,
      touchZoomRotate: true,
      touchPitch: true,
      cooperativeGestures: false,
      pitchWithRotate: true,
      rollEnabled: false,
      // Display options
      renderWorldCopies: true,
      trackResize: true,
      // Performance options
      refreshExpiredTiles: true,
      fadeDuration: 300,
      crossSourceCollisions: true,
      collectResourceTiming: false,
      maxTileCacheZoomLevels: 5,
      anisotropicFilterPitch: 20,
    },
  },
  schema: {
    optionalProperties: {
      mapStyle: {
        optionalProperties: {
          version: { type: 'uint8' },
          name: { type: 'string' },
          metadata: {},
          // Style-level camera properties
          center: { elements: { type: 'float64' } },
          centerAltitude: { type: 'float64' },
          zoom: { type: 'float64' },
          bearing: { type: 'float64' },
          pitch: { type: 'float64' },
          roll: { type: 'float64' },
          // Style sources, layers, etc.
          sources: {},
          layers: {},
          sprite: {},
          glyphs: { type: 'string' },
          light: {},
          sky: {},
          projection: {},
          terrain: {},
          transition: {},
          state: {},
          // Map constructor options (can also be in style)
          minZoom: { type: 'float64' },
          maxZoom: { type: 'float64' },
          minPitch: { type: 'float64' },
          maxPitch: { type: 'float64' },
          maxBounds: { elements: { elements: { type: 'float64' } } },
          interactive: { type: 'boolean' },
          hash: { type: 'boolean' },
          bearingSnap: { type: 'float64' },
          zoomSnap: { type: 'float64' },
          clickTolerance: { type: 'float64' },
          scrollZoom: { type: 'boolean' },
          boxZoom: { type: 'boolean' },
          dragRotate: { type: 'boolean' },
          dragPan: { type: 'boolean' },
          keyboard: { type: 'boolean' },
          doubleClickZoom: { type: 'boolean' },
          touchZoomRotate: { type: 'boolean' },
          touchPitch: { type: 'boolean' },
          cooperativeGestures: { type: 'boolean' },
          pitchWithRotate: { type: 'boolean' },
          rollEnabled: { type: 'boolean' },
          renderWorldCopies: { type: 'boolean' },
          trackResize: { type: 'boolean' },
          refreshExpiredTiles: { type: 'boolean' },
          fadeDuration: { type: 'float64' },
          crossSourceCollisions: { type: 'boolean' },
          collectResourceTiming: { type: 'boolean' },
          maxTileCacheZoomLevels: { type: 'float64' },
          anisotropicFilterPitch: { type: 'float64' },
        }
      },
    }
  },
};

const geoPlugin: Plugin = {
  tag: 'plugin/geo',
  name: $localize`🌐️ Geo`,
  config: {
    type: 'lens',
    mod: $localize`🗺️ Map`,
    default: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    icons: [{ label: $localize`🗺️` }],
    filters: [
      { query: 'plugin/geo', label: $localize`📍️ geo`, group: $localize`Plugins 🧰️` },
    ],
    description: $localize`A GeoJSON Feature.`,
  },
};

const geoPointPlugin: Plugin = {
  tag: 'plugin/geo/point',
  name: $localize`🌐️📍️ Geo Point`,
  config: {
    type: 'lens',
    mod: $localize`🗺️ Map`,
    default: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    icons: [{ label: $localize`📍️` }],
    description: $localize`A GeoJSON Point.`,
    form: [{
      key: 'type',
      defaultValue: 'Feature',
    }, {
      key: 'geometry.type',
      defaultValue: 'Point',
    }, {
      key: 'geometry.coordinates',
      type: 'location',
      props: {
        label: $localize`Location: `,
      },
    }],
  },
  defaults: {
    type: 'Feature',
    geometry: {
      type: 'Point',
      coordinates: [0, 0],
    }
  },
  schema: {
    optionalProperties: {
      bb: { elements: { type: 'int32' } } ,
    },
    properties: {
      type: { enum: ['Feature'] },
      geometry: {
        properties: {
          type: { enum: ['Point'] },
          coordinates: { elements: { type: 'int32' } },
        },
      }
    },
  },
};

const geoLineStringPlugin: Plugin = {
  tag: 'plugin/geo/linestring',
  name: $localize`🌐️📌️📌️ Geo Line String`,
  config: {
    type: 'lens',
    mod: $localize`🗺️ Map`,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    icons: [{ label: $localize`📌️📌️` }],
    description: $localize`A GeoJSON LineString.`,
    form: [{
      key: 'type',
      defaultValue: 'Feature',
    }, {
      key: 'geometry.type',
      defaultValue: 'LineString',
    }, {
      key: 'geometry.coordinates',
      type: 'list',
      props: {
        label: $localize`Points:`,
        addText: $localize`+ Add Point`,
      },
      fieldArray: {
        type: 'location',
      },
    }],
  },
  defaults: {
    type: 'Feature',
    geometry: {
      type: 'LineString',
      coordinates: [],
    }
  },
  schema: {
    optionalProperties: {
      bb: { elements: { type: 'int32' } } ,
    },
    properties: {
      type: { enum: ['Feature'] },
      geometry: {
        properties: {
          type: { enum: ['LineString'] },
          coordinates: { elements: { elements: { type: 'int32' } } },
        },
      }
    },
  },
};

const geoPolygonPlugin: Plugin = {
  tag: 'plugin/geo/polygon',
  name: $localize`🌐️🔷️ Geo Polygon`,
  config: {
    type: 'lens',
    mod: $localize`🗺️ Map`,
    default: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    icons: [{ label: $localize`🔷️` }],
    description: $localize`A GeoJSON Polygon.`,
    form: [{
      key: 'type',
      defaultValue: 'Feature',
    }, {
      key: 'geometry.type',
      defaultValue: 'Polygon',
    }, {
      key: 'geometry.coordinates',
      type: 'list',
      props: {
        label: $localize`Rings:`,
        addText: $localize`+ Add Ring`,
      },
      fieldArray: {
        type: 'list',
        props: {
          label: $localize`Points:`,
          addText: $localize`+ Add Point`,
        },
        fieldArray: {
          type: 'location',
        },
      },
    }],
  },
  defaults: {
    type: 'Feature',
    geometry: {
      type: 'Polygon',
      coordinates: [],
    }
  },
  schema: {
    optionalProperties: {
      bb: { elements: { type: 'int32' } } ,
    },
    properties: {
      type: { enum: ['Feature'] },
      geometry: {
        properties: {
          type: { enum: ['Polygon'] },
          coordinates: { elements: { elements: { elements: { type: 'int32' } } } },
        },
      }
    },
  },
};

const geoMultiPointPlugin: Plugin = {
  tag: 'plugin/geo/multipoint',
  name: $localize`🌐️📍️📍️ Geo Multi Point`,
  config: {
    type: 'lens',
    mod: $localize`🗺️ Map`,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    icons: [{ label: $localize`📍️📍️` }],
    description: $localize`A GeoJSON MultiPoint.`,
    form: [{
      key: 'type',
      defaultValue: 'Feature',
    }, {
      key: 'geometry.type',
      defaultValue: 'MultiPoint',
    }, {
      key: 'geometry.coordinates',
      type: 'list',
      props: {
        label: $localize`Points:`,
        addText: $localize`+ Add Point`,
      },
      fieldArray: {
        type: 'location',
      },
    }],
  },
  defaults: {
    type: 'Feature',
    geometry: {
      type: 'MultiPoint',
      coordinates: [[]],
    }
  },
  schema: {
    optionalProperties: {
      bb: { elements: { type: 'int32' } } ,
    },
    properties: {
      type: { enum: ['Feature'] },
      geometry: {
        properties: {
          type: { enum: ['MultiPoint'] },
          coordinates: { elements: { elements: { type: 'int32' } } },
        },
      }
    },
  },
};

const geoMultiLineStringPlugin: Plugin = {
  tag: 'plugin/geo/multilinestring',
  name: $localize`🌐️📌️📌️📌️ Geo Multi Line String`,
  config: {
    type: 'lens',
    mod: $localize`🗺️ Map`,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    icons: [{ label: $localize`📌️📌️📌️` }],
    description: $localize`A GeoJSON MultiLineString.`,
    form: [{
      key: 'type',
      defaultValue: 'Feature',
    }, {
      key: 'geometry.type',
      defaultValue: 'MultiLineString',
    }, {
      key: 'geometry.coordinates',
      type: 'list',
      props: {
        label: $localize`Lines:`,
        addText: $localize`+ Add Line`,
      },
      fieldArray: {
        type: 'list',
        props: {
          label: $localize`Points:`,
          addText: $localize`+ Add Point`,
        },
        fieldArray: {
          type: 'location',
        },
      },
    }],
  },
  defaults: {
    type: 'Feature',
    geometry: {
      type: 'MultiLineString',
      coordinates: [],
    }
  },
  schema: {
    optionalProperties: {
      bb: { elements: { type: 'int32' } } ,
    },
    properties: {
      type: { enum: ['Feature'] },
      geometry: {
        properties: {
          type: { enum: ['MultiLineString'] },
          coordinates: { elements: { elements: { elements: { type: 'int32' } } } },
        },
      }
    },
  },
};

const geoMultiPolygonPlugin: Plugin = {
  tag: 'plugin/geo/multipolygon',
  name: $localize`🌐️🔷️🔷️ Geo Multi Polygon`,
  config: {
    type: 'lens',
    mod: $localize`🗺️ Map`,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    icons: [{ label: $localize`🔷️🔷️` }],
    description: $localize`A GeoJSON MultiPolygon.`,
    form: [{
      key: 'type',
      defaultValue: 'Feature',
    }, {
      key: 'geometry.type',
      defaultValue: 'MultiPolygon',
    }, {
      key: 'geometry.coordinates',
      type: 'list',
      props: {
        label: $localize`Polygons:`,
        addText: $localize`+ Add Polygon`,
      },
      fieldArray: {
        type: 'list',
        props: {
          label: $localize`Rings:`,
          addText: $localize`+ Add Ring`,
        },
        fieldArray: {
          type: 'list',
          props: {
            label: $localize`Points:`,
            addText: $localize`+ Add Point`,
          },
          fieldArray: {
            type: 'location',
          },
        },
      },
    }],
  },
  defaults: {
    type: 'Feature',
    geometry: {
      type: 'MultiPolygon',
      coordinates: [],
    }
  },
  schema: {
    optionalProperties: {
      bb: { elements: { type: 'int32' } } ,
    },
    properties: {
      type: { enum: ['Feature'] },
      geometry: {
        properties: {
          type: { enum: ['MultiPolygon'] },
          coordinates: { elements: { elements: { elements: { elements: { type: 'int32' } } } } },
        },
      }
    },
  },
};

export const mapMod: Mod = {
  template: [
    mapTemplate,
  ],
  plugin: [
    geoPlugin,
    geoPointPlugin,
    geoLineStringPlugin,
    geoPolygonPlugin,
    geoMultiPointPlugin,
    geoMultiLineStringPlugin,
    geoMultiPolygonPlugin,
  ],
};

export function features(ref: Ref) {
  const result: Feature[] = [];
  if (!ref.plugins) return result;
  Object.entries(ref.plugins).forEach(([key, value]) => {
    if (key.startsWith('plugin/geo/')) {
      result.push(value);
    }
  })
  return result;
}
