import { type StyleSpecification } from '@maplibre/maplibre-gl-style-spec';
import { Feature } from 'geojson';
import { DateTime } from 'luxon';
import { Plugin } from '../model/plugin';
import { Ref } from '../model/ref';
import { Mod } from '../model/tag';
import { Template } from '../model/template';

export const mapTemplate: Template = {
  tag: 'map',
  name: $localize`🗺️ Map`,
  config: {
    type: 'lens',
    mod: $localize`🗺️ Map`,
    default: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    global: true,
    submit: $localize`🗺️ map/`,
    view: $localize`🗺️`,
    tab: $localize`map`,
    description: $localize`Activates built-in map mode for viewing Refs on a map.`,
    filters: [
      { query: 'map', label: $localize`🗺️ map`, group: $localize`Templates 🎨️` },
    ],
    mapStyle: <StyleSpecification> {
      version: 8,
      sources: {
        satellite: {
          tileSize: 512,
          type: 'raster',
          url: 'https://api.maptiler.com/tiles/satellite-v2/tiles.json?key=get_your_own'
        },
      },
      layers: [{
        id: 'satellite',
        layout: {
          visibility: 'visible'
        },
        minzoom: 0,
        paint: {
          'raster-opacity': 1
        },
        source: 'satellite',
        type: 'raster'
      }],
      center: [-64, 45],
      zoom: 6,
      bearing: 0,
      pitch: 0,
      roll: 0,
      elevation: 0,
      // Constraints
      minZoom: 0,
      maxZoom: 22,
      minPitch: 0,
      maxPitch: 60,
      // Interaction options
      interactive: true,
      hash: false,
      bearingSnap: 7,
      zoomSnap: 0,
      clickTolerance: 3,
      scrollZoom: true,
      boxZoom: true,
      dragRotate: true,
      dragPan: true,
      keyboard: true,
      doubleClickZoom: true,
      touchZoomRotate: true,
      touchPitch: true,
      cooperativeGestures: false,
      pitchWithRotate: true,
      rollEnabled: false,
      // Display options
      renderWorldCopies: true,
      trackResize: true,
      // Performance options
      refreshExpiredTiles: true,
      fadeDuration: 300,
      crossSourceCollisions: true,
      collectResourceTiming: false,
      maxTileCacheZoomLevels: 5,
      anisotropicFilterPitch: 20,
    },
  },
  schema: {
    optionalProperties: {
      mapStyle: {
        optionalProperties: {
          version: { type: 'uint8' },
          name: { type: 'string' },
          metadata: {},
          // Style-level camera properties
          center: { elements: { type: 'float64' } },
          centerAltitude: { type: 'float64' },
          zoom: { type: 'float64' },
          bearing: { type: 'float64' },
          pitch: { type: 'float64' },
          roll: { type: 'float64' },
          // Style sources, layers, etc.
          sources: {},
          layers: {},
          sprite: {},
          glyphs: { type: 'string' },
          light: {},
          sky: {},
          projection: {},
          terrain: {},
          transition: {},
          state: {},
          // Map constructor options (can also be in style)
          minZoom: { type: 'float64' },
          maxZoom: { type: 'float64' },
          minPitch: { type: 'float64' },
          maxPitch: { type: 'float64' },
          maxBounds: { elements: { elements: { type: 'float64' } } },
          interactive: { type: 'boolean' },
          hash: { type: 'boolean' },
          bearingSnap: { type: 'float64' },
          zoomSnap: { type: 'float64' },
          clickTolerance: { type: 'float64' },
          scrollZoom: { type: 'boolean' },
          boxZoom: { type: 'boolean' },
          dragRotate: { type: 'boolean' },
          dragPan: { type: 'boolean' },
          keyboard: { type: 'boolean' },
          doubleClickZoom: { type: 'boolean' },
          touchZoomRotate: { type: 'boolean' },
          touchPitch: { type: 'boolean' },
          cooperativeGestures: { type: 'boolean' },
          pitchWithRotate: { type: 'boolean' },
          rollEnabled: { type: 'boolean' },
          renderWorldCopies: { type: 'boolean' },
          trackResize: { type: 'boolean' },
          refreshExpiredTiles: { type: 'boolean' },
          fadeDuration: { type: 'float64' },
          crossSourceCollisions: { type: 'boolean' },
          collectResourceTiming: { type: 'boolean' },
          maxTileCacheZoomLevels: { type: 'float64' },
          anisotropicFilterPitch: { type: 'float64' },
        }
      },
    }
  },
};

const geoPlugin: Plugin = {
  tag: 'plugin/geo',
  name: $localize`🌐️ Geo`,
  config: {
    type: 'lens',
    mod: $localize`🗺️ Map`,
    default: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    icons: [{ label: $localize`🗺️` }],
    filters: [
      { query: 'plugin/geo', label: $localize`📍️ geo`, group: $localize`Plugins 🧰️` },
    ],
    description: $localize`A GeoJSON Feature.`,
  },
};

const geoPointPlugin: Plugin = {
  tag: 'plugin/geo/point',
  name: $localize`🌐️📍️ Geo Point`,
  config: {
    type: 'lens',
    mod: $localize`🗺️ Map`,
    default: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    icons: [{ label: $localize`📍️` }],
    description: $localize`A GeoJSON Point.`,
    form: [{
      key: 'type',
      defaultValue: 'Feature',
    }, {
      key: 'geometry.type',
      defaultValue: 'Point',
    }, {
      key: 'geometry.coordinates',
      type: 'location',
      props: {
        label: $localize`Location: `,
      },
    }],
  },
  defaults: {
    type: 'Feature',
    geometry: {
      type: 'Point',
      coordinates: [0, 0],
    }
  },
  schema: {
    optionalProperties: {
      bb: { elements: { type: 'int32' } } ,
    },
    properties: {
      type: { enum: ['Feature'] },
      geometry: {
        properties: {
          type: { enum: ['Point'] },
          coordinates: { elements: { type: 'int32' } },
        },
      }
    },
  },
};

const geoLineStringPlugin: Plugin = {
  tag: 'plugin/geo/linestring',
  name: $localize`🌐️📌️📌️ Geo Line String`,
  config: {
    type: 'lens',
    mod: $localize`🗺️ Map`,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    icons: [{ label: $localize`📌️📌️` }],
    description: $localize`A GeoJSON LineString.`,
    form: [{
      key: 'type',
      defaultValue: 'Feature',
    }, {
      key: 'geometry.type',
      defaultValue: 'LineString',
    }, {
      key: 'geometry.coordinates',
      type: 'list',
      props: {
        label: $localize`Points:`,
        addText: $localize`+ Add Point`,
      },
      fieldArray: {
        type: 'location',
      },
    }],
  },
  defaults: {
    type: 'Feature',
    geometry: {
      type: 'LineString',
      coordinates: [],
    }
  },
  schema: {
    optionalProperties: {
      bb: { elements: { type: 'int32' } } ,
    },
    properties: {
      type: { enum: ['Feature'] },
      geometry: {
        properties: {
          type: { enum: ['LineString'] },
          coordinates: { elements: { elements: { type: 'int32' } } },
        },
      }
    },
  },
};

const geoPolygonPlugin: Plugin = {
  tag: 'plugin/geo/polygon',
  name: $localize`🌐️🔷️ Geo Polygon`,
  config: {
    type: 'lens',
    mod: $localize`🗺️ Map`,
    default: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    icons: [{ label: $localize`🔷️` }],
    description: $localize`A GeoJSON Polygon.`,
    form: [{
      key: 'type',
      defaultValue: 'Feature',
    }, {
      key: 'geometry.type',
      defaultValue: 'Polygon',
    }, {
      key: 'geometry.coordinates',
      type: 'list',
      props: {
        label: $localize`Rings:`,
        addText: $localize`+ Add Ring`,
      },
      fieldArray: {
        type: 'list',
        props: {
          label: $localize`Points:`,
          addText: $localize`+ Add Point`,
        },
        fieldArray: {
          type: 'location',
        },
      },
    }],
  },
  defaults: {
    type: 'Feature',
    geometry: {
      type: 'Polygon',
      coordinates: [],
    }
  },
  schema: {
    optionalProperties: {
      bb: { elements: { type: 'int32' } } ,
    },
    properties: {
      type: { enum: ['Feature'] },
      geometry: {
        properties: {
          type: { enum: ['Polygon'] },
          coordinates: { elements: { elements: { elements: { type: 'int32' } } } },
        },
      }
    },
  },
};

const geoMultiPointPlugin: Plugin = {
  tag: 'plugin/geo/multipoint',
  name: $localize`🌐️📍️📍️ Geo Multi Point`,
  config: {
    type: 'lens',
    mod: $localize`🗺️ Map`,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    icons: [{ label: $localize`📍️📍️` }],
    description: $localize`A GeoJSON MultiPoint.`,
    form: [{
      key: 'type',
      defaultValue: 'Feature',
    }, {
      key: 'geometry.type',
      defaultValue: 'MultiPoint',
    }, {
      key: 'geometry.coordinates',
      type: 'list',
      props: {
        label: $localize`Points:`,
        addText: $localize`+ Add Point`,
      },
      fieldArray: {
        type: 'location',
      },
    }],
  },
  defaults: {
    type: 'Feature',
    geometry: {
      type: 'MultiPoint',
      coordinates: [[]],
    }
  },
  schema: {
    optionalProperties: {
      bb: { elements: { type: 'int32' } } ,
    },
    properties: {
      type: { enum: ['Feature'] },
      geometry: {
        properties: {
          type: { enum: ['MultiPoint'] },
          coordinates: { elements: { elements: { type: 'int32' } } },
        },
      }
    },
  },
};

const geoMultiLineStringPlugin: Plugin = {
  tag: 'plugin/geo/multilinestring',
  name: $localize`🌐️📌️📌️📌️ Geo Multi Line String`,
  config: {
    type: 'lens',
    mod: $localize`🗺️ Map`,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    icons: [{ label: $localize`📌️📌️📌️` }],
    description: $localize`A GeoJSON MultiLineString.`,
    form: [{
      key: 'type',
      defaultValue: 'Feature',
    }, {
      key: 'geometry.type',
      defaultValue: 'MultiLineString',
    }, {
      key: 'geometry.coordinates',
      type: 'list',
      props: {
        label: $localize`Lines:`,
        addText: $localize`+ Add Line`,
      },
      fieldArray: {
        type: 'list',
        props: {
          label: $localize`Points:`,
          addText: $localize`+ Add Point`,
        },
        fieldArray: {
          type: 'location',
        },
      },
    }],
  },
  defaults: {
    type: 'Feature',
    geometry: {
      type: 'MultiLineString',
      coordinates: [],
    }
  },
  schema: {
    optionalProperties: {
      bb: { elements: { type: 'int32' } } ,
    },
    properties: {
      type: { enum: ['Feature'] },
      geometry: {
        properties: {
          type: { enum: ['MultiLineString'] },
          coordinates: { elements: { elements: { elements: { type: 'int32' } } } },
        },
      }
    },
  },
};

const geoMultiPolygonPlugin: Plugin = {
  tag: 'plugin/geo/multipolygon',
  name: $localize`🌐️🔷️🔷️ Geo Multi Polygon`,
  config: {
    type: 'lens',
    mod: $localize`🗺️ Map`,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    icons: [{ label: $localize`🔷️🔷️` }],
    description: $localize`A GeoJSON MultiPolygon.`,
    form: [{
      key: 'type',
      defaultValue: 'Feature',
    }, {
      key: 'geometry.type',
      defaultValue: 'MultiPolygon',
    }, {
      key: 'geometry.coordinates',
      type: 'list',
      props: {
        label: $localize`Polygons:`,
        addText: $localize`+ Add Polygon`,
      },
      fieldArray: {
        type: 'list',
        props: {
          label: $localize`Rings:`,
          addText: $localize`+ Add Ring`,
        },
        fieldArray: {
          type: 'list',
          props: {
            label: $localize`Points:`,
            addText: $localize`+ Add Point`,
          },
          fieldArray: {
            type: 'location',
          },
        },
      },
    }],
  },
  defaults: {
    type: 'Feature',
    geometry: {
      type: 'MultiPolygon',
      coordinates: [],
    }
  },
  schema: {
    optionalProperties: {
      bb: { elements: { type: 'int32' } } ,
    },
    properties: {
      type: { enum: ['Feature'] },
      geometry: {
        properties: {
          type: { enum: ['MultiPolygon'] },
          coordinates: { elements: { elements: { elements: { elements: { type: 'int32' } } } } },
        },
      }
    },
  },
};

export const mapMod: Mod = {
  template: [
    mapTemplate,
  ],
  plugin: [
    geoPlugin,
    geoPointPlugin,
    geoLineStringPlugin,
    geoPolygonPlugin,
    geoMultiPointPlugin,
    geoMultiLineStringPlugin,
    geoMultiPolygonPlugin,
  ],
};

export function features(ref: Ref) {
  const result: Feature[] = [];
  if (!ref.plugins) return result;
  Object.entries(ref.plugins).forEach(([key, value]) => {
    if (key.startsWith('plugin/geo/')) {
      result.push(value);
    }
  })
  return result;
}
