import { DateTime } from 'luxon';
import { Plugin } from '../model/plugin';
import { Mod } from '../model/tag';

export const markitdownPlugin: Plugin = {
  tag: 'plugin/delta/md',
  name: $localize`📝️ MarkItDown`,
  config: {
    mod: $localize`📝️ MarkItDown`,
    type: 'tool',
    default: false,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Convert documents to Markdown using Microsoft MarkItDown.
Supports PDF, Word, Excel, PowerPoint, images (with OCR), audio (transcription), HTML, and more.`,
    aiInstructions: `# plugin/delta/md
The MarkItDown plugin converts various file formats to Markdown text.
It uses the Microsoft markitdown Python library to process documents.

Supported formats:
- Microsoft Office: Word (.docx), Excel (.xlsx), PowerPoint (.pptx)
- PDF files (.pdf)
- Images (.jpg, .png, etc.) - extracts text via OCR
- Audio files - transcribes to text
- HTML, JSON, XML, CSV files
- ZIP archives containing multiple files

The converted Markdown is stored in the Ref's comment field.
The original file URL is preserved in the plugin data.`,
    icons: [{ label: $localize`📝️`, order: 2 }],
    filters: [
      { query: 'plugin/delta/md', label: $localize`📝️💭️ markitdown query`, title: $localize`Convert to Markdown`, group: $localize`Notifications ✉️` },
    ],
    actions: [
      { tag: 'plugin/delta/md', labelOff: $localize`to markdown`, title: $localize`Convert document to Markdown using MarkItDown`, global: true },
      { tag: 'plugin/delta/md', labelOn: $localize`cancel`, title: $localize`Cancel MarkItDown conversion.` },
    ],
    timeoutMs: 300_000,
    requirements: `
      markitdown
      requests
    `,
    language: 'python',
    // language=python
    script: `
import json
import os
import sys
import tempfile
import requests
from markitdown import MarkItDown

ref = json.load(sys.stdin)
origin = ref.get('origin', '')

# Get the URL to convert - check plugin data first, then ref URL
url = ref.get('plugins', {}).get('plugin/delta/md', {}).get('url')
if not url:
    # Try to find URL from various plugin sources
    for plugin_key in ['plugin/pdf', 'plugin/file', 'plugin/image', 'plugin/audio', 'plugin/video']:
        plugin_url = ref.get('plugins', {}).get(plugin_key, {}).get('url')
        if plugin_url:
            url = plugin_url
            break
if not url:
    url = ref.get('url', '')

if not url:
    print("Error: No URL found to convert", file=sys.stderr)
    sys.exit(1)

# Check if URL is a cache URL and resolve it
if url.startswith('cache:'):
    cache_id = url[6:]
    cache_api = f"{os.environ['JASPER_API']}/api/v1/cache/{cache_id}"
    try:
        cache_response = requests.get(
            cache_api,
            headers={
                'Local-Origin': origin or 'default',
                'User-Role': 'ROLE_ADMIN',
            },
            allow_redirects=True
        )
        if cache_response.ok:
            # The cache endpoint might redirect to the actual file
            url = cache_response.url
    except Exception as e:
        print(f"Warning: Could not resolve cache URL: {e}", file=sys.stderr)

# Download the file to a temporary location
temp_file = None
try:
    response = requests.get(url, stream=True, timeout=60)
    response.raise_for_status()

    # Determine file extension from content-type or URL
    content_type = response.headers.get('content-type', '')
    ext = ''
    if 'pdf' in content_type:
        ext = '.pdf'
    elif 'word' in content_type or 'docx' in content_type:
        ext = '.docx'
    elif 'excel' in content_type or 'xlsx' in content_type:
        ext = '.xlsx'
    elif 'powerpoint' in content_type or 'pptx' in content_type:
        ext = '.pptx'
    elif 'html' in content_type:
        ext = '.html'
    elif 'image' in content_type:
        ext = '.png'
    elif 'audio' in content_type:
        ext = '.mp3'
    else:
        # Try to get extension from URL
        url_path = url.split('?')[0]
        if '.' in url_path:
            ext = '.' + url_path.rsplit('.', 1)[-1]

    temp_file = tempfile.NamedTemporaryFile(delete=False, suffix=ext)
    for chunk in response.iter_content(chunk_size=8192):
        temp_file.write(chunk)
    temp_file.close()

    # Convert using MarkItDown
    md = MarkItDown()
    result = md.convert(temp_file.name)
    markdown_content = result.text_content

    if not markdown_content or not markdown_content.strip():
        print("Warning: No content extracted from document", file=sys.stderr)
        markdown_content = "(No text content could be extracted from this document)"

    # Update the ref with the markdown content
    ref.pop('metadata', None)
    ref.setdefault('tags', [])
    # Remove the delta tag to prevent re-running
    ref['tags'] = [t for t in ref['tags'] if not (t + '/').startswith('plugin/delta/md/') and t != 'plugin/delta/md']
    # Add signature tag
    ref['tags'].append('+plugin/delta/md')

    # Store the markdown in the comment
    ref['comment'] = markdown_content

    # Store the source URL in plugin data
    ref.setdefault('plugins', {})
    ref['plugins']['+plugin/delta/md'] = {
        'sourceUrl': url
    }

    print(json.dumps({
        'ref': [ref],
    }))

except requests.exceptions.RequestException as e:
    print(f"Error downloading file: {e}", file=sys.stderr)
    sys.exit(1)
except Exception as e:
    print(f"Error converting document: {e}", file=sys.stderr)
    sys.exit(1)
finally:
    if temp_file and os.path.exists(temp_file.name):
        os.remove(temp_file.name)
    `,
  },
  schema: {
    optionalProperties: {
      url: { type: 'string' },
      sourceUrl: { type: 'string' },
    },
  },
};

export const markitdownSignaturePlugin: Plugin = {
  tag: '+plugin/delta/md',
  name: $localize`📝️ MarkItDown Result`,
  config: {
    mod: $localize`📝️ MarkItDown`,
    type: 'tool',
    default: false,
    signature: '+plugin/delta/md',
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Signature tag for documents converted to Markdown using Microsoft MarkItDown.`,
    icons: [{ thumbnail: $localize`📝️`, order: 1 }],
    filters: [
      { query: '+plugin/delta/md', label: $localize`📝️ markdown`, title: $localize`Converted to Markdown`, group: $localize`Delta Δ` },
    ],
    advancedActions: [
      { tag: '+plugin/delta/md', labelOn: $localize`reconvert`, title: $localize`Reconvert document to Markdown` },
      { tag: 'plugin/alias/plugin/delta/md', labelOff: $localize`reconvert`, title: $localize`Reconvert document to Markdown` },
    ],
  },
  schema: {
    optionalProperties: {
      sourceUrl: { type: 'string' },
    },
  },
};

export const markitdownMod: Mod = {
  plugin: [
    markitdownPlugin,
    markitdownSignaturePlugin,
  ],
};
