import { DateTime } from 'luxon';
import { Plugin } from '../model/plugin';
import { Mod, modSchema } from '../model/tag';

export const storePlugin: Plugin = {
  tag: 'plugin/mod/store',
  name: $localize`🎁️ Store`,
  config: {
    mod: $localize`🎁️ Store`,
    version: 1,
    settings: $localize`store`,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Browse and install community created mods.`,
  },
};

export const storeMod: Mod = {
  plugin: [
    storePlugin,
  ],
};
