import * as moment from 'moment';
import { Template } from '../model/template';

export const privateIcon: Template = {
  tag: 'public',
  name: $localize`👁️ Private Icon`,
  config: {
    type: 'icon',
    default: true,
    mod: $localize`👁️ Private Icon`,
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    description: $localize`Show private icon on non-public Refs and add filters for
      private and public Refs`,
    icons: [
      { label: $localize`👁️`, tag: '!public', title: $localize`Private`, global: true },
    ],
    filters: [
      { query: 'public', label: $localize`🌐️ public`, group: $localize`Filters` },
      { query: '!public', label: $localize`👁️ private`, group: $localize`Filters` },
    ],
  },
};

