import { DateTime } from 'luxon';
import { Plugin } from '../model/plugin';
import { Mod } from '../model/tag';

export const progressPlugin: Plugin = {
  tag: 'plugin/progress',
  name: $localize`⏳️ Progress`,
  config: {
    mod: $localize`⏳️ Progress`,
    type: 'plugin',
    version: 1,
    default: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Stores progress in the tag itself (e.g., plugin/progress/37/100 is 37%).
      Scripts reporting progress should also add the _seal/delta tag to prevent the update from
      running delta scripts again.`,
    advancedActions: [
      { tag: 'plugin/progress', labelOn: $localize`clear progress`, title: $localize`Remove stale progress from this Ref.` },
      { tag: '_seal/delta', labelOn: $localize`unseal`, title: $localize`Allow delta scripts to run on this Ref again.`, role: 'ROLE_MOD' },
    ],
    // language=CSS
    css: `
      .info-progress progress {
        width: 6em;
        height: 0.8em;
        vertical-align: middle;
      }
    `,
    // language=Handlebars
    infoUi: `{{#with (progress ref 'plugin/progress')}}<span class="info-progress" title="{{value}} / {{max}}"><progress max="{{max}}" value="{{value}}"></progress> {{percent}}%</span>{{/with}}`,
  },
};

export const progressMod: Mod = {
  plugin: [
    progressPlugin,
  ]
};
