import { DateTime } from 'luxon';
// @ts-ignore
import extModelText from '../model/ext.ts' with { loader: 'text' };
import { Plugin } from '../model/plugin';
// @ts-ignore
import pluginModelText from '../model/plugin.ts' with { loader: 'text' };
// @ts-ignore
import refModelText from '../model/ref.ts' with { loader: 'text' };
import { Mod } from '../model/tag';
// @ts-ignore
import tagModelText from '../model/tag.ts' with { loader: 'text' };
import { Template } from '../model/template';
// @ts-ignore
import templateModelText from '../model/template.ts' with { loader: 'text' };
// @ts-ignore
import userModelText from '../model/user.ts' with { loader: 'text' };

export const rootPlugin: Plugin = {
  tag: 'plugin',
  name: $localize`📦️ Root Plugin`,
  config: {
    mod: $localize`⚓️ Root`,
    default: true,
    view: $localize`📦️`,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Add Ref sorts.`,
    sorts: [
      { sort: 'created', label: $localize`✨️ new` },
      { sort: 'published', label: $localize`📅️ published` },
      { sort: 'modified', label: $localize`🕓️ modified` },
      { sort: 'metadata->modified', label: $localize`🧵️ new response`, title: $localize`Date of new response` },
      { sort: 'title', label: $localize`🇦️ title` },
      { sort: 'url', label: $localize`🔗️ url` },
      { sort: 'scheme', label: $localize`🏳️️ scheme` },
      { sort: 'tags:len', label: $localize`🏷️ tags`, title: $localize`Number of tags` },
      { sort: 'metadata->responses', label: $localize`💌️ responses`, title: $localize`Number of responses` },
      { sort: 'sources:len', label: $localize`📜️ sources`, title: $localize`Number of sources` },
    ],
  }
};

export const rootTemplate: Template = {
  tag: '',
  name: $localize`⚓️ Root Template`,
  config: {
    mod: $localize`⚓️ Root`,
    default: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Add common features Ext tag pages: Adding pinned Refs, sidebar markdown,
    a custom theme and a set of non-global custom themes to choose from in addition to global themes.`,
    aiInstructions: ` # Root Template
    The root template uses the empty string as a tag. Since templates are matched to Exts by prefix matching,
    the root template matches every tag. Here are the models in use:
    \`\`\`typescript
    ` + tagModelText + `
    ` + refModelText + `
    ` + extModelText + `
    ` + userModelText + `
    ` + pluginModelText + `
    ` + templateModelText + `
    \`\`\`

    The root template sets up basic functionality such as deleted icons and filters, and basic Ext config:
    \`\`\`typescript
    export interface RootConfig {
      pinned?: string[];
      sidebar?: string;
      modmail?: boolean;
      dms?: string;
      queryFilters?: { query: string, label?: string}[];
      responseFilters?: { response: \`plugin/\${string}\` | \`!plugin/\${string}\`, label?: string }[];
      themes?: Record<string, string>;
      theme?: string;
      defaultSort?: string;
      submitText?: boolean;
      addTags?: string[];
      defaultExpanded?: boolean;
      hideEdit?: boolean;
      disableResize?: boolean;
      defaultCols?: number;
    }
    \`\`\`
    `,
    icons: [
      { tag: 'plugin/delete', label: $localize`🗑️`, global: true },
    ],
    filters: [
      { scheme: 'http:', label: $localize`http:`, group: $localize`Schemes 🏳️️`},
      { scheme: 'https:', label: $localize`https:`, group: $localize`Schemes 🏳️️`},
      { scheme: 'ftp:', label: $localize`ftp:`, group: $localize`Schemes 🏳️️`},
      { scheme: 'email:', label: $localize`email:`, group: $localize`Schemes 🏳️️`},
      { scheme: 'tel:', label: $localize`tel:`, group: $localize`Schemes 🏳️️`},
      { scheme: 'magnet:', label: $localize`magnet:`, group: $localize`Schemes 🏳️️`},
    ],
    sorts: [
      { sort: 'modified', label: $localize`🕓️ modified` },
      { sort: 'name', label: $localize`🇦️ name` },
      { sort: 'tag', label: $localize`🏷️ tag` },
      { sort: 'tag:len', label: $localize`/🏷️ level`, title: $localize`Number of subtags` },
      { sort: 'origin', label: $localize`🏛️ origin` },
      { sort: 'origin:len', label: $localize`🪆 nesting` },
    ],
    form: [{
      key: 'pinned',
      type: 'refs',
      props: {
        label: $localize`Pinned:`,
        addText: $localize`+ Add another pinned link`,
      },
      fieldArray: {
        props: {
          label: $localize`📌️`,
        }
      },
    }, {
      key: 'submitText',
      type: 'select',
      defaultValue: false,
      props: {
        label: $localize`Submit:`,
        options: [
          { value: true, label: $localize`Text Posts` },
          { value: false, label: $localize`Link Posts` },
        ],
      }
    }, {
      key: 'addTags',
      type: 'tags',
      defaultValue: ['public'],
      props: {
        label: $localize`Add Tags:`
      },
    }, {
      key: 'queryFilters',
      type: 'list',
      props: {
        label: $localize`Query Filters:`,
        addText: $localize`+ Add another query filter`,
      },
      fieldArray: {
        fieldGroup: [{
          key: 'label',
          type: 'string',
          props: {
            label: $localize`Label:`
          }
        }, {
          key: 'query',
          type: 'query',
          props: {
            required: true,
          }
        }]
      }
    }],
    advancedForm: [{
      key: 'dms',
      type: 'tag',
      props: {
        label: $localize`DMs:`
      }
    }, {
      key: 'responseFilters',
      type: 'list',
      props: {
        label: $localize`Response Filters:`,
        addText: $localize`+ Add another response filter`,
      },
      fieldArray: {
        fieldGroup: [{
          key: 'label',
          type: 'string',
          props: {
            label: $localize`Label:`
          }
        }, {
          key: 'response',
          type: 'plugin',
          props: {
            required: true,
          }
        }]
      }
    }, {
      key: 'defaultCols',
      type: 'select',
      props: {
        label: $localize`Columns:`,
        options: [
          { label: $localize`Default` },
          { value: 1, label: $localize`1 Column` },
          { value: 2, label: $localize`2 Columns` },
          { value: 3, label: $localize`3 Columns` },
          { value: 4, label: $localize`4 Columns` },
          { value: 5, label: $localize`5 Columns` },
          { value: 6, label: $localize`6 Columns` },
        ],
      },
    }, {
      key: 'childTags',
      type: 'number',
      props: {
        label: $localize`Child Tags in Sidebar:`,
      },
    }, {
      key: 'noFloatingSidebar',
      type: 'boolean',
      props: {
        label: $localize`No Floating Sidebar:`,
      },
    }, {
      key: 'defaults',
      type: 'boolean',
      props: {
        label: $localize`Defaults:`,
      },
    }],
  },
  defaults: <RootConfig> {
    defaultSort: ['published'],
    addTags: ['public'],
  },
  schema: {
    optionalProperties: {
      pinned: { elements: { type: 'string' } },
      sidebar: { type: 'string' },
      popover: { type: 'string' },
      modmail: { type: 'boolean' },
      dms: { type: 'string' },
      queryFilters: { elements: {
        properties: {
          query: { type: 'string' },
        },
        optionalProperties: {
          label: { type: 'string' },
        }
      }},
      responseFilters: { elements: {
        properties: {
          response: { type: 'string' },
        },
        optionalProperties: {
          label: { type: 'string' },
        }
      }},
      themes: { values: { type: 'string' } },
      theme: { type: 'string' },
      defaultSort: { elements: { type: 'string' } },
      defaultFilter: { elements: { type: 'string' } },
      submitText: { type: 'boolean'},
      addTags: { elements: { type: 'string' } },
      defaultExpanded: { type: 'boolean'},
      hideEdit: { type: 'boolean'},
      disableResize: { type: 'boolean'},
      defaultCols: { type: 'int8'},
      childTags: { type: 'int8'},
      noFloatingSidebar: { type: 'boolean'},
      defaults: { type: 'boolean'},
    },
  },
};

export interface RootConfig {
  pinned?: string[];
  sidebar?: string;
  popover?: string;
  modmail?: boolean;
  dms?: string;
  queryFilters?: { query: string, label?: string}[];
  responseFilters?: { response: `plugin/${string}` | `+plugin/${string}` | `_plugin/${string}` | `!plugin/${string}` | `!+plugin/${string}` | `!_plugin/${string}`, label?: string }[];
  themes?: Record<string, string>;
  theme?: string;
  defaultSort?: string[];
  defaultFilter?: string[];
  submitText?: boolean;
  addTags?: string[];
  defaultExpanded?: boolean;
  hideEdit?: boolean;
  disableResize?: boolean;
  defaultCols?: number;
  childTags?: number;
  noFloatingSidebar?: boolean;
  defaults?: boolean;
}

export const internalTemplate: Template = {
  tag: 'internal',
  name: $localize`⚙️ Internal`,
  config: {
    mod: $localize`⚓️ Root`,
    default: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Internal Refs which should be hidden by default`,
    icons: [
      { thumbnail: $localize`⚙️`, order: -20 },
    ],
    filters: [
      { query: 'internal', label: $localize`⚙️ internal`, title: $localize`Show hidden comments and reactions`, group: $localize`Filters 🕵️️` },
      { scheme: 'internal:', label: $localize`internal:`, group: $localize`Schemes 🏳️️`},
    ],
  },
};

export const altPlugin: Plugin = {
  tag: 'plugin/alt',
  name: $localize`ℹ️ Alt Text`,
  config: {
    mod: $localize`⚓️ Root`,
    default: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Use comment as alt text`,
    icons: [
      { tag: 'plugin/alt', label: $localize`ℹ️`, global: true, order: -3 },
    ],
  },
};

export const lockedTemplate: Template = {
  tag: 'locked',
  name: $localize`🔒️ Locked`,
  config: {
    mod: $localize`⚓️ Root`,
    default: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Show locked icon on locked Refs and add filters for
      locked and unlocked Refs`,
    icons: [
      { label: $localize`🔒️`, title: $localize`Locked`, order: -2 },
    ],
    actions: [
      { tag: '_plugin/delta/unlock', labelOff: $localize`unlock`, title: $localize`Unlock this post to allow editing`},
    ],
    filters: [
      { query: 'locked', label: $localize`🔒️ locked`, title: $localize`Locked`, group: $localize`Filters 🕵️️` },
      { query: '!locked', label: $localize`🔓️ unlocked`, title: $localize`Unlocked`, group: $localize`Filters 🕵️️` },
    ],
    editorButtons: [
      { labelOff: $localize`🔓️`, labelOn: $localize`🔒️`, title: $localize`Lock this post to prevent editing`, ribbon: true, order: 100, global: true },
    ],
  },
};

export const unlockPlugin: Plugin = {
  tag: '_plugin/delta/unlock',
  name: $localize`🔓️ Unlock`,
  config: {
    mod: $localize`⚓️ Root`,
    default: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    timeoutMs: 30_000,
    language: 'javascript',
    // language=JavaScript
    script: `
      const ref = JSON.parse(require('fs').readFileSync(0, 'utf-8'));
      if (ref?.tags?.find(t => t === 'locked' || t?.startsWith('locked/'))) {
        ref.tags = ref.tags.filter(t => t !== 'locked' && !t.startsWith('locked/'));
        delete ref.metadata;
        console.log(JSON.stringify({ ref: [ref] }))
      }
    `,
  },
};

export const privateTemplate: Template = {
  tag: 'public',
  name: $localize`🌐️ Public`,
  config: {
    mod: $localize`⚓️ Root`,
    default: true,
    reply: ['public'],
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Show private icon on non-public Refs and add filters for
      private and public Refs`,
    icons: [
      { label: $localize`👁️`, tag: '!public', title: $localize`Private`, order: -2, global: true },
    ],
    filters: [
      { query: 'public', label: $localize`🌐️ public`, title: $localize`Public read access`, group: $localize`Filters 🕵️️` },
      { query: '!public', label: $localize`👁️ private`, title: $localize`Private read access`, group: $localize`Filters 🕵️️` },
    ],
    editorButtons: [
      { labelOff: $localize`👁️`, labelOn: $localize`🌐️`, title: $localize`Toggle 🌐️ Public or 👁️ Private`, remember: true, order: -1, global: true },
    ],
  },
};

export const diffTemplate: Template = {
  tag: 'diff',
  name: $localize`🔀 Diff`,
  config: {
    mod: $localize`⚓️ Root`,
    default: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Enable diff action for comparing reference versions using Monaco editor`,
  },
};

export const rootMod: Mod = {
  plugin: [
    rootPlugin,
    altPlugin,
    unlockPlugin,
  ],
  template: [
    rootTemplate,
    internalTemplate,
    lockedTemplate,
    privateTemplate,
    diffTemplate,
  ]
};
