import * as moment from 'moment/moment';
import { Plugin } from '../model/plugin';
import { Mod } from '../model/tag';

export const schedulerPlugin: Plugin = {
  tag: '_plugin/scheduler',
  name: $localize`⏲️ Scheduler`,
  config: {
    mod: $localize`⏲️ Scheduler`,
    default: true,
    settings: $localize`scheduler`,
    generated: 'Generated by jasper-ui ' + moment().toISOString(),
    description: $localize`Schedule various jobs.`,
    form: [{
      key: 'scrapeInterval',
      type: 'duration',
      defaultValue: 'PT24H',
      props: {
        label: $localize`Interval`,
      }
    }]
  },
  schema: {
    properties: {
      interval: { type: 'string' },
    }
  }
};

export const backupSchedulerPlugin: Plugin = {
  tag: '_plugin/scheduler/backup',
  name: $localize`⏲️📼️ Backup Scheduler`,
  config: {
    mod: $localize`⏲️ Scheduler`,
    default: true,
    generated: 'Generated by jasper-ui ' + moment().toISOString(),
    description: $localize`Schedule backups.`,
    form: [{
      key: 'newerThan',
      type: 'duration',
      defaultValue: 'PT24H',
      props: {
        label: $localize`Newer Than`,
      }
    }, {
      key: 'ref',
      type: 'boolean',
      props: {
        label: $localize`Refs`,
      }
    }, {
      key: 'ext',
      type: 'boolean',
      props: {
        label: $localize`Exts`,
      }
    }, {
      key: 'user',
      type: 'boolean',
      props: {
        label: $localize`Users`,
      }
    }, {
      key: 'plugin',
      type: 'boolean',
      props: {
        label: $localize`Plugins`,
      }
    }, {
      key: 'template',
      type: 'boolean',
      props: {
        label: $localize`Templates`,
      }
    }]
  },
  schema: {
    optionalProperties: {
      newerThan: { type: 'string' },
      ref: { type: 'boolean' },
      ext: { type: 'boolean' },
      user: { type: 'boolean' },
      plugin: { type: 'boolean' },
      template: { type: 'boolean' },
    }
  }
};

export const schedulerMod: Mod = {
  plugins: {
    schedulerPlugin,
    backupSchedulerPlugin,
  }
}
