import { DateTime } from 'luxon';
import { Plugin } from '../model/plugin';
import { Mod } from '../model/tag';

export const scorePlugin: Plugin = {
  tag: 'plugin/score',
  name: $localize`🏆️ Score`,
  config: {
    mod: $localize`🏆️ Score`,
    version: 1,
    type: 'plugin',
    default: true,
    add: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Store a numeric score on a Ref.`,
    sorts: [
      { sort: 'plugins->plugin/score:num', label: $localize`🏆️ score`, title: $localize`Score` },
    ],
  },
  defaults: 0,
  schema: { type: 'float64' },
};

export const scoreMod: Mod = {
  plugin: [
    scorePlugin,
  ],
};
