import { $localize } from '@angular/localize/init';
import * as moment from 'moment';
import { Plugin } from '../model/plugin';
import { Template } from '../model/template';

export const seamlessPlugin: Plugin = {
  tag: 'plugin/seamless',
  name: $localize`🪡 seamless`,
  config: {
    type: 'plugin',
    default: true,
    add: true,
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    description: $localize`Remove the white border from the comment markdown.`,
    icons: [{ label: $localize`🪡`}],
    // language=CSS
    css: `
      .ref.plugin-seamless {
        & > app-viewer > .expand,
        & > .row > .stack > .link-below > .stack > app-viewer > .expand {
          border: none !important;
        }
      }
    `,
  },
};
