import moment from 'moment';
import { Plugin } from '../model/plugin';
import { Mod } from '../model/tag';

export const summaryQueryPlugin: Plugin = {
  tag: 'plugin/summary',
  name: '✂️️💭️ Summarize',
  config: {
    mod: $localize`✂️ Summarize`,
    type: 'tool',
    default: false,
    add: true,
    signature: '+plugin/summary',
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    description: $localize`Send this Ref to the ai to create a summary response.`,
    icons: [{ label: $localize`️💭️`, order: -3 }],
    filters: [
      { query: 'plugin/summary', label: $localize`✂️️💭️ summarize`, group: $localize`Notifications ✉️` },
    ],
    advancedActions: [
      { tag: 'plugin/summary', labelOff: $localize`summarize`, global: true }
    ],
  },
};

export const summaryPlugin: Plugin = {
  tag: '+plugin/summary',
  name: '✂️️ OpenAI Summary',
  config: {
    mod: $localize`✂️ Summarize`,
    type: 'tool',
    default: false,
    signature: '+plugin/summary',
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    description: $localize`AI signature tag. Plugin configures OpenAi to respond to 'plugin/summary' prompts
    and sign this response with this tag. Plugin data contains token usage stats.`,
    icons: [{ thumbnail: $localize`✂️️`, order: 1 }],
    filters: [
      { query: '+plugin/summary', label: $localize`✂️️ summary`, group: $localize`Plugins 🧰️` },
    ],
    titlePrefix: $localize`AI Summary: `,
    systemPrompt: $localize`Summarize the following:`,
    model: 'gpt-4-turbo-preview',
    maxTokens: 4096,
  },
  schema: {},
  generateMetadata: true,
};

export const summaryMod: Mod = {
  plugins: {
    summaryQueryPlugin,
    summaryPlugin,
  },
};
