import * as moment from 'moment';
import { Plugin } from '../model/plugin';

export const tablePlugin: Plugin = {
  tag: 'plugin/table',
  name: '📏️ Table',
  config: {
    type: 'plugin',
    default: true,
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    description: $localize`Activates built-in table support and allows users to create tables.`,
    submitText: $localize`📏️ table`,
    icons: [{ label: $localize`📏️`}],
    filters: [
      { query: 'plugin/table', label: $localize`📏️ table`, group: $localize`Plugins 🧰️` },
    ],
  },
};
