import * as moment from 'moment';
import { Template } from '../model/template';

export const terminalTheme: Template = {
  tag: 'theme/terminal',
  name: $localize`🖌️ Terminal Theme`,
  config: {
    type: 'theme',
    mod: $localize`🖌️ Themes`,
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    description: $localize`Adds a terminal graphics style theme to the global theme list. Will combine
    themes if multiple specified with the same name.`,
    themes: {
      [$localize`Terminal`]: `
        * {
          font-family: monospace;
        }
        body.dark-theme, body.dark-theme ::backdrop, body.dark-theme .editor.fullscreen app-md {
          background-color: #333;
          background-image: none;
          background-blend-mode: normal;
        }
        body.dark-theme .container {
          background: none;
        }
        body.light-theme, body.light-theme ::backdrop, body.light-theme .editor.fullscreen app-md {
          background-color: #EEE;
          background-image: none;
          background-blend-mode: normal;
        }
        .sidebar details summary span:after {
          content: '+';
        }
        .sidebar details[open] summary span:after {
          content: '+';
          transform: rotate(-135deg);
        }
      `,
    },
  },
};
