import * as moment from 'moment';
import { Plugin } from '../model/plugin';

export const threadPlugin: Plugin = {
  tag: 'plugin/thread',
  name: $localize`🧵️ Threads`,
  config: {
    type: 'plugin',
    default: true,
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    description: $localize`Attempt to merge similar Refs tagged plugin/thread into threads.`,
    filters: [
      { query: 'plugin/thread', label: $localize`🧵️ threads`, group: $localize`Plugins 🧰️` },
    ],
    reply: ['internal', 'plugin/thread'],
  },
  generateMetadata: true,
};
