import * as moment from 'moment';
import { Plugin } from '../model/plugin';
import { imagePlugin } from './image';
import { videoPlugin } from './video';

export const thumbnailPlugin: Plugin = {
  tag: 'plugin/thumbnail',
  name: $localize`⭕️ Thumbnail`,
  config: {
    type: 'plugin',
    default: true,
    cache: true,
    add: true,
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    description: $localize`Activates built-in thumbnail support and allows users to add thumbnails to Refs.`,
    extensions: [...videoPlugin.config!.extensions!, ...imagePlugin.config!.extensions!],
    advancedForm: [{
      key: 'showUrl',
      type: 'radio',
      defaultValue: true,
      props: {
        label: $localize`Show:`,
        options: [
          { value: true, label: 'Image' },
          { value: false, label: 'Color' },
        ],
      },
    }, {
      key: 'url',
      type: 'image',
      props: {
        label: $localize`URL:`,
      },
      expressions: { hide: '!model.showUrl' },
    }, {
      key: 'color',
      type: 'color',
      props: {
        label: $localize`Color:`,
      },
      expressions: { hide: 'model.showUrl' },
    }, {
      key: 'emoji',
      type: 'string',
      props: {
        label: $localize`Emoji:`,
      },
    }, {
      key: 'radius',
      type: 'number',
      props: {
        label: $localize`Radius:`,
      },
    }],
  },
  schema: {
    optionalProperties: {
      showUrl: { type: 'boolean' },
      url: { type: 'string' },
      color: { type: 'string' },
      emoji: { type: 'string' },
      radius: { type: 'int32' },
    },
  },
};
