import { DateTime } from 'luxon';
import { Plugin } from '../model/plugin';
import { Mod } from '../model/tag';

export const videoPlugin: Plugin = {
  tag: 'plugin/video',
  name: $localize`🎞️ Video`,
  config: {
    type: 'plugin',
    default: true,
    proxy: true,
    add: true,
    embeddable: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    aiInstructions: ` # plugin/video
    The video plugin indicates a Ref contains an video file. It contains optional
    field url which is typically missing. When the url field is missing it is
    assumed to be the URL of the Ref instead.
    You may refer to a video you returned with the URL ai:part, or optionally
    multiple returned assets as ai:part1, ai:part2, etc. These will be uploaded
    to the cache and the URL will be rewritten with it's cache URL. Even if you use
    the url field of an video plugin, anything not prefixed with ai:part will be
    assumed to refer to an existing URL in the system and not replaced.
    `,
    submit: $localize`🎞️ video`,
    icons: [{ label: $localize`🎞️`, order: 2 }],
    filters: [
      { query: 'plugin/video', label: $localize`🎞️ video`, title: $localize`Videos`, group: $localize`Media 🎬️` },
    ],
    extensions: ['.3gp', '.mpg', '.mpeg', '.mp4', '.m4v', '.m4p', '.webm', '.ogv', '.m3u8', '.mov'],
    description: $localize`Play in a video player.`,
    advancedForm: [{
      key: 'url',
      type: 'video',
      props: {
        label: $localize`URL:`,
      },
    }],
  },
  defaults: {},
  schema: {
    optionalProperties: {
      url: { type: 'string' },
    },
  },
};

export const videoMod: Mod = {
  plugin: [
    videoPlugin,
  ],
};
