import { chromium } from '@playwright/test';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1280, height: 720 } });
const s = async l => console.log(l, p.url(), await p.locator('.show-remotes').count());
await p.goto('http://localhost:4200/settings/plugin?debug=ADMIN', { waitUntil: 'networkidle' }); await s('load');
await p.locator('#show-remotes').check(); await p.waitForTimeout(1000); await s('checked');
await p.locator('.tabs a', {hasText:'template'}).click(); await p.waitForTimeout(1000); await s('template');
await p.locator('#show-remotes').check(); await p.waitForTimeout(1000); await s('checked');
await p.goBack(); await p.waitForTimeout(1000); await s('back');
await p.goBack(); await p.waitForTimeout(1000); await s('back');
await p.goForward(); await p.waitForTimeout(1000); await s('fwd');
await p.locator('.tabs a', {hasText:'setup'}).click(); await p.waitForTimeout(1000); await s('setup');
await p.goBack(); await p.waitForTimeout(1000); await s('back');
await p.locator('.tabs a', {hasText:'origin'}).click(); await p.waitForTimeout(1000); await s('origin');
await p.locator('.tabs a', {hasText:'plugin'}).last().click(); await p.waitForTimeout(1000); await s('plugin');
await p.goto('http://localhost:4200/tag/@*?debug=ADMIN', { waitUntil: 'networkidle' }); await s('tag');
await p.locator('a', {hasText:/^tags$/i}).first().click(); await p.waitForTimeout(1500); await s('tags');
await b.close();
