import { DateTime } from 'luxon';
import { Plugin } from '../../model/plugin';
import { Mod } from '../../model/tag';

const errorPlugin: Plugin = {
  tag: '+plugin/error',
  name: $localize`⚠️ Error`,
  config: {
    mod: $localize`⚠️ Error`,
    version: 1,
    default: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    inbox: $localize`errors`,
    icons: [{ label: $localize`⚠️` }],
    filters: [
      { query: '+plugin/error', label: $localize`⚠️ error`, title: $localize`Stopped with an error`, group: $localize`Plugins 🧰️` },
    ],
    actions: [
      { tag: '+plugin/error', labelOn: $localize`retry` },
    ],
    description: $localize`
    View which Refs have failed running a script and will not be retried.
    See the attached logs for the specifics of the error.
    Click 'retry' to clear the error and try again.`,
  },
};

const logPlugin: Plugin = {
  tag: '+plugin/log',
  name: $localize`🪵 Log`,
  config: {
    mod: $localize`⚠️ Error`,
    version: 1,
    default: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    icons: [{ label: $localize`🪵`, order: 3 }],
    filters: [
      { query: '+plugin/log', label: $localize`🪵 logs`, title: $localize`Error logs`, group: $localize`Plugins 🧰️` },
    ],
    description: $localize`Logs associated with a Ref.`,
    // language=CSS
    css: `
    .plugin_log .embed {
      white-space: pre;
      display: block;
      unicode-bidi: embed;
      font-family: monospace;
      .expand {
        max-width: min(100vw - 16px, 120em);
        overflow-x: auto;
      }
    }
    `
  },
};

export const errorMod: Mod = {
  plugin: [
    errorPlugin,
    logPlugin,
  ],
}
