import { DateTime } from 'luxon';
import { Plugin } from '../../model/plugin';
import { Mod } from '../../model/tag';

export const pipPlugin: Plugin = {
  tag: 'plugin/pip',
  name: '🪟 Picture in Picture',
  config: {
    type: 'plugin',
    default: true,
    add: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    icons: [{ label: $localize`🪟` }],
    filters: [
      { query: 'plugin/pip', label: $localize`🪟 pip`, title: $localize`Picture-in-picture`, group: $localize`Plugins 🧰️` },
    ],
    description: $localize`Open embed picture-in-picture..`,
    windowConfig: <PipWindowConfig> {
      disallowReturnToOpener: true,
    },
  }
};

export type PipWindowConfig = { width?: number, height?: number, disallowReturnToOpener?: boolean, preferInitialWindowPlacement?: boolean };

export const pipMod: Mod = {
  plugin: [
    pipPlugin,
  ]
};
