import { DateTime } from 'luxon';
import { Plugin } from '../../model/plugin';
import { Mod } from '../../model/tag';

export const seamlessPlugin: Plugin = {
  tag: 'plugin/seamless',
  name: $localize`🪡 Seamless`,
  config: {
    type: 'plugin',
    default: true,
    add: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Remove the white border from the comment markdown.`,
    aiInstructions: `# plugin/seamless
    Remove the white border around the embedded markdown comment. This can be particularly
    useful when embedding a Ref in markdown like ![](ai:ref). Otherwise, theme depending
    when markdown viewers are expanded or embedded in other markdown the thin white border will be present.`,
    icons: [{ label: $localize`🪡` }],
    // language=CSS
    css: `
      .plugin_seamless > .expand {
        border: none !important;
      }
    `,
  },
};

export const seamlessMod: Mod = {
  plugin: [
    seamlessPlugin,
  ]
};
