import { DateTime } from 'luxon';
import { Mod } from '../../model/tag';
import { Template } from '../../model/template';

export const snippetConfig: Template = {
  tag: 'config/snippet',
  name: $localize`👨️‍💻️ Snippet`,
  config: {
    type: 'config',
    noUpdate: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    snippet: `
    <!-- Add your analytics trackers and other site scripts here -->
    `,
    subDiff: [
      'snippet'
    ],
    adminForm: [{
      key: 'snippet',
      type: 'code',
      props: {
        label: $localize`Snippet:`,
        language: 'html'
      }
    }],
  },
};

export const snippetMod: Mod = {
  template: [
    snippetConfig,
  ]
};
