services:
  web:
    image: ghcr.io/cjmalloy/jasper
    ports:
      - 8081:8081
    environment:
      SPRING_PROFILES_ACTIVE: prod,admin,storage,feed-burst,repl-burst
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jasper
      SPRING_DATASOURCE_USERNAME: jasper
      SPRING_DATASOURCE_PASSWORD: "${JASPER_DATABASE_PASSWORD:-jasper}"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: jasper
      POSTGRES_PASSWORD: "${JASPER_DATABASE_PASSWORD-jasper}"
      POSTGRES_DB: jasper
