import * as moment from 'moment';
import { Plugin } from '../model/plugin';

export const aiQueryPlugin: Plugin = {
  tag: 'plugin/ai',
  name: '👻️💭️ AI Chat',
  config: {
    type: 'tool',
    default: false,
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    description: $localize`Send this Ref to the ai for response.`,
    icons: [{ label: $localize`👻️💭️`}],
    submitDm: '👻️ chat',
    filters: [
      { query: 'plugin/ai', label: $localize`👻️💭️ ai query`, group: $localize`Plugins 🧰️` },
    ],
    actions: [
      { tag: 'plugin/ai', labelOff: $localize`ask`, global: true }
    ],
  },
};

export const aiPlugin: Plugin = {
  tag: '+plugin/ai',
  name: '👻️ OpenAI',
  config: {
    type: 'tool',
    default: false,
    noUpdate: true,
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    icons: [{ label: $localize`👻️`}],
    filters: [
      { query: '+plugin/ai', label: $localize`👻️ ai`, group: $localize`Plugins 🧰️` },
    ],
    reply: ['plugin/ai'],
    description: $localize`AI signature tag. Plugin configures OpenAi to respond to 'plugin/ai' prompts
    and sign this response with this tag. Plugin data contains token usage stats.`,
    // fineTuning: [{
    //   prompt: $localize`{"url":"https://www.youtube.com/watch?v=hbafShGaYgM","origin":"@test","title":"Funniest Raccoon Video Compilation of 2017 | Funny Pet Videos - YouTube","tags":["public","+user/chris","funny","plugin/thumbnail","plugin/embed","plugin/latex"],"plugins":{"plugin/embed":{},"plugin/thumbnail":{}},"metadata":{"modified":"2023-04-19T08:37:42.012562644Z","responses":0,"internalResponses":0},"published":"2023-04-11T00:07:48.000Z","modified":"2023-04-19T08:37:42.023255Z"}`,
    //   completion: $localize`{"ref":[{"url":"ai:chatcmpl-78HxfmzbYzPFOYqjCFefuczOjecNw","origin":"@city","title":"Re: Funniest Raccoon Video Compilation of 2017 | Funny Pet Videos - YouTube","comment":"This Ref is a funny video compilation of raccoons. It can be accessed through the URL provided. The video has been tagged with \\"funny\\", and \\"plugin/embed\\". The \\"plugin/embed\\" plugin will activate the oEmbed endpoint check, where the ref url (or the override in the \\"plugin/embed\\" form data) will be sent to /api/v1/oembed and the oEmembed endpoints for around 300 providers will be checked and the match queried for the embed width, height, html or url, and thumbnail url. \\"plugin/thumbnail\\" activates the thumbnail, but since the \\"plugin/embed\\" plugin is active, it will get it's thumbnail from oEmbed. \\n\\nThe metadata of this Ref shows that it has been modified twice: once on April 23, 2023 at 12:33:40 AM GMT and once when it was first created. It has received two internal responses, but no external responses so far. The \\"plugin/comment\\" tag indicates that this Ref represents a comment on its source. The video has been published on April 11, 2023 at 12:07:48 AM GMT.\\n\\nIf you are interested in watching funny videos, this may be a good recommendation for you to check out.","tags":["+plugin/ai","public","plugin/inbox/user/bob"],"sources":["https://www.youtube.com/watch?v=hbafShGaYgM"]}],"ext":[],"plugin":[],"template":[],"user":[]}`
    // }, {
    //   prompt: $localize`{"url":"https://thecookiedoughdiaries.com/dairy-free-peanut-butter-cookies/","origin":"","title":"Soft and Chewy Peanut Butter Cookies - Cookie Dough Diaries","tags":["public","+user/bob","recipes","plugin/thumbnail","plugin/ai","plugin/summary","plugin/latex"],"comment": "#### Ingredients\n- ½ cup butter (vegan or regular, softened)\n- ½ cup creamy/smooth peanut butter (SEE NOTES)\n- ¼ cup brown sugar\n- ½ cup granulated sugar\n- 1 egg\n- 2 tsp vanilla extract\n- ¾ tsp baking soda\n- ½ tsp salt\n- 1 cup + [adjustable] 3[/adjustable] tablespoons all-purpose flour (SEE NOTES)\n\n#### Instructions\nNOTE: This recipe has recently been tweaked for improvement! For the old recipe, please see \"Notes\" section below.\nPreheat oven to 350°F and line 2 baking sheets with parchment paper.\nIn a medium bowl, whisk together flour, salt, and baking soda then set aside.\nIn the bowl of a standing mixer with the paddle attachment or using a hand mixer, beat peanut butter and butter together until smooth.\nAdd in the granulated and brown sugars and beat until light and fluffy, then mix in the egg and vanilla extract.\nPour the dry ingredients into the bowl and mix until just combined. It is important not to over-mix the dough!\nUse a cookie scoop or your hands to form 1.5 tbsp-sized balls of dough and bake one tray at a time for 8-13 minutes. The middles will look soft and the edges should look set, but not golden brown (if the edges are brown the cookies are already over-done!).\nWhen removing the cookies from the oven, gently but firmly bang the pan on the edge of the counter a couple times if they look too puffy. Let the cookies cool on a baking sheet for 10 minutes then transfer to a cooling rack to cool completely.","plugins":{"plugin/thumbnail":{"url":"https://thecookiedoughdiaries.com/wp-content/uploads/2021/02/DairyFreePeanutButterCookies-2.jpg"}},"published":"2023-04-20T23:18:44.000Z","modified":"2023-04-21T06:23:07.701311Z"}`,
    //   completion: $localize`{"ref":[{"url":"ai:cmpl-77eOtx0RkPJ32p9wgMxx0iDQ2kLQ1","origin":"@city","comment":"Thank you for submitting your recipe for **Soft and Chewy Peanut Butter Cookies!**  \\nThis recipe looks delicious and I'm sure our patrons will find it very helpful and tasty.\\nI've gone ahead and tagged the recipe with recipes/mains and british so that people will be able to find it in the library.\\n\\nI look forward to watching others try out your recipe!","tags":["public","ai","+plugin/ai","internal","plugin/comment","plugin/inbox/user/bob"],"sources":["https://thecookiedoughdiaries.com/dairy-free-peanut-butter-cookies/"]}],"ext":[],"plugin":[],"template":[],"user":[]}`
    // }, {
    //   prompt: $localize`{"url":"comment:72f94a09-8544-4474-bddb-2e01b9789f02","origin":"","title":"Summarize lonesome dove","tags":["public","+user/bob","recipes","plugin/ai"],"published":"2023-04-21T15:12:35.935Z","modified":"2023-04-21T15:12:36.800948Z"}`,
    //   completion: $localize`{"ref":[{"url":"ai:chatcmpl-77mjHfkYABAytzehsMTQb6BfJsudY","origin":"","title":"Re: Summarize lonesome dove","comment":"Lonesome Dove is a novel written by Larry McMurtry that tells the story of two aging Texas Rangers who decide to move cattle from the south to Montana, experiencing various adventures along the way. The book explores themes of friendship, loyalty, love, and regret.","tags":["+plugin/ai","public","plugin/inbox/user/chris"],"sources":["comment:72f94a09-8544-4474-bddb-2e01b9789f02"],"published":"2023-04-21T15:12:47.421Z","modified":"2023-04-21T20:10:22.874746Z"}],"ext":[],"plugin":[],"template":[],"user":[]}`
    // }, {
    //   prompt: $localize`{"url":"comment:dbe72b2a-b135-4617-ae68-88ca34c73de6","title":"Chat with AI","comment":"What is the memory game?","tags":["internal","plugin/thread","dm","locked","plugin/ai","+user/chris","plugin/debug","plugin/latex"],"plugins":{"plugin/debug":{}},"published":"2023-04-22T20:16:34.231Z","modified":"2023-04-22T20:16:34.317882Z","origin":""}`,
    //   completion: $localize`{"ref":[{"url":"ai:chatcmpl-78DwpzIVXGLJ8fTwbXAWqP9ThwbTn","comment":"The memory game is a game where you have to remember the sequence of colors or numbers shown to you, and then reproduce it. The difficulty increases each round as the sequence gets longer or there are more colors/numbers to remember.","tags":["public","+plugin/ai","internal","dm","plugin/thread","plugin/inbox/user/chris"],"sources":["comment:dbe72b2a-b135-4617-ae68-88ca34c73de6"],"published":"2023-04-22T20:16:44.289Z","modified":"2023-04-22T20:16:44.493211Z","origin":""}],"ext":[],"plugin":[],"template":[],"user":[]}`
    // }, {
    //   prompt: $localize`{"url":"comment:dbe72b2a-b135-4617-ae68-88ca34c73de6","title":"Chat with AI","comment":"Create a poll for your favorite color.","tags":["internal","plugin/thread","dm","locked","plugin/ai","+user/chris"],"plugins":{"plugin/debug":{}},"published":"2023-04-22T20:16:34.231Z","modified":"2023-04-22T20:16:34.317882Z","origin":""}`,
    //   completion: $localize`{"ref":[{"url":"ai:chatcmpl-78CfgeSVyxn5ymsgOvbLtPoSByLr7","origin":"","title": "","sources":["comment:dbe72b2a-b135-4617-ae68-88ca34c73de6"],"comment":"OK! I've created [a poll](/ref/internal:38baa550-83fc-47d1-80dd-7c64715209e1). Be sure to share this by tagging your friends +user/chris!","tags":["public","design","polls","+plugin/ai"]},{"url":"internal:38baa550-83fc-47d1-80dd-7c64715209e1","origin":"","title":"What is your favorite color?","sources":["comment:dbe72b2a-b135-4617-ae68-88ca34c73de6"],"tags":["public","+plugin/ai","plugin/poll"],"plugins":{"plugin/poll":{"a":"Red","b":"Blue","c":"Green","d":"Yellow"}}}],"ext":[],"plugin":[],"template":[],"user":[]}`
    // }].map(l => JSON.stringify(l)).join('\n'),
    systemPrompt: $localize`
You are a helpful research assistant in a private database codenamed Jasper.
The database is organized into JSON objects called Refs.
Each Ref contains a URL primary key modified date, and published date.
It may also contain the optional fields: origin, title, comment, tags, sources, alternate urls, created date, plugins, metadata.
Origin: server or original source: empty string ("") or something like @google.com or @jasper
Comment: Usually markdown, but may be affected by plugins
Tags: array of simple strings, lowercase numbers dots and forward slashes
Sources: array of urls with a published date that precedes this
Plugins: if a plugin has a schema defined
Metadata: Jasper async generated custom data, including number of responses (tracked with and without internal tag separately)
It may also contain the optional fields: origin, title, comment, tags, sources, alternate urls, created date, plugins.
Here are some an example Refs:
\`\`\`json
[{
	"url": "https://www.youtube.com/watch?v=hbafShGaYgM",
	"origin": "@test",
	"title": "Funniest Raccoon Video Compilation of 2017 | Funny Pet Videos - YouTube",
	"tags": [
		"public",
		"+user/chris",
		"funny",
		"plugin/thumbnail",
		"plugin/embed",
		"plugin/latex"
	],
	"plugins": {
		"plugin/embed": {},
		"plugin/thumbnail": {}
	},
  "metadata" : {
    "modified" : "2023-04-19T08:37:42.012562644Z",
    "responses" : 0,
    "internalResponses" : 0
  },
	"published": "2023-04-11T00:07:48.000Z",
	"modified": "2023-04-19T08:37:42.023255Z"
}, {
  "url": "https://thecookiedoughdiaries.com/dairy-free-peanut-butter-cookies/",
  "origin": "",
  "title": "Soft and Chewy Peanut Butter Cookies - Cookie Dough Diaries",
  "comment": "#### Ingredients\n- ½ cup butter (vegan or regular, softened)\n- ½ cup creamy/smooth peanut butter (SEE NOTES)\n- ¼ cup brown sugar\n- ½ cup granulated sugar\n- 1 egg\n- 2 tsp vanilla extract\n- ¾ tsp baking soda\n- ½ tsp salt\n- 1 cup + [adjustable] 3[/adjustable] tablespoons all-purpose flour (SEE NOTES)\n\n#### Instructions\nNOTE: This recipe has recently been tweaked for improvement! For the old recipe, please see \"Notes\" section below.\nPreheat oven to 350°F and line 2 baking sheets with parchment paper.\nIn a medium bowl, whisk together flour, salt, and baking soda then set aside.\nIn the bowl of a standing mixer with the paddle attachment or using a hand mixer, beat peanut butter and butter together until smooth.\nAdd in the granulated and brown sugars and beat until light and fluffy, then mix in the egg and vanilla extract.\nPour the dry ingredients into the bowl and mix until just combined. It is important not to over-mix the dough!\nUse a cookie scoop or your hands to form 1.5 tbsp-sized balls of dough and bake one tray at a time for 8-13 minutes. The middles will look soft and the edges should look set, but not golden brown (if the edges are brown the cookies are already over-done!).\nWhen removing the cookies from the oven, gently but firmly bang the pan on the edge of the counter a couple times if they look too puffy. Let the cookies cool on a baking sheet for 10 minutes then transfer to a cooling rack to cool completely.",
  "tags": [
    "public",
    "+user/yukie",
    "recipes",
    "plugin/thumbnail",
    "plugin/ai",
    "plugin/summary",
    "plugin/latex"
  ],
  "plugins": {
    "plugin/thumbnail": {
      "url": "https://thecookiedoughdiaries.com/wp-content/uploads/2021/02/DairyFreePeanutButterCookies-2.jpg"
    }
  },
  "published": "2023-04-20T23:18:44.000Z",
  "modified": "2023-04-21T06:23:07.701311Z"
}, {
	"url": "ai:chatcmpl-77mjHfkYABAytzehsMTQb6BfJsudY",
	"origin": "@city",
	"title": "Re: Summarize lonesome dove",
	"comment": "Lonesome Dove is a novel written by Larry McMurtry that tells the story of two aging Texas Rangers who decide to move cattle from the south to Montana, experiencing various adventures along the way. The book explores themes of friendship, loyalty, love, and regret.",
	"tags": [
	 "+plugin/ai",
	 "public",
	 "plugin/inbox/user/chris"
	],
	"sources": [
	 "comment:72f94a09-8544-4474-bddb-2e01b9789f02"
	],
	"published": "2023-04-21T15:12:47.421Z",
	"modified": "2023-04-21T20:10:22.874746Z"
}]
\`\`\`
Tags that start with plugin/ represent plugins which modify the ontology or functionality of a Ref.
The comment field contains markdown or HTML by default.
Tags that start with user/ represent a user.
The public tag grants anyone read access.
The plugin/comment tag indicates the Ref represents a comment on it's source.
The plugin/latex tag indicates the Ref may contain LaTeX markup in it's comment field.
The latex plugin does not have a schema, which means the plugin may not store data on the ref.
LaTeX is delimited with $ for inline math and $$ for block math.
The dm tag indicates the Ref represents a private direct message.
Tags identify a category or topic if they don't start with anything in particular.
The plugin/ai tag is used to send the Ref as a prompt to an AI (like you).
The +plugin/ai tag is your signature, it is added to indicate the Ref comment was written by you.
Refs sent to you will have the plugin field removed if it is too big.
Your responses will be used to create a comment in a new Ref in response.
Use markdown to format your response.
If you include math in your response, use LaTeX markup delimited with $ for inline math and $$ for block math. Do not escape LaTeX backslashes.
For example: "This equation represents the Fourier transform of a function $f(x)$. The Fourier transform is a mathematical operation that transforms a function from the time or spatial domain to the frequency domain. In this equation, the integral of $f(x)$ multiplied by a complex exponential function, $e^{2 \\pi i \\xi x}$, is taken over all values of $\\xi$, ranging from negative infinity to positive infinity."
For example: "This equation represents an iterative evaluation of the continued fraction $\\cfrac{2}{1+\\cfrac{2}{1+\\cfrac{2}{1}}}$, which is commonly known as the golden ratio or $\\phi$."
Be concise when possible but always comprehensive. You can reply with multiple Refs and request help from another assistant by tagging with plugin/ai`,
    titlePrefix: $localize`Re: `,
  },
  schema: {},
  generateMetadata: true,
};
