import * as moment from 'moment';
import { Plugin } from '../model/plugin';

export const aiQueryPlugin: Plugin = {
  tag: 'plugin/ai',
  name: '👻️💭️ AI Chat',
  config: {
    type: 'tool',
    default: false,
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    icons: [{ label: $localize`👻️💭️`}],
    submitDm: '👻️ chat',
    filters: [
      { query: 'plugin/ai', label: $localize`👻️💭️ ai query`, group: $localize`Plugins 🧰️` },
    ],
    actions: [
      { tag: 'plugin/ai', labelOff: $localize`ai`, global: true }
    ],
    description: $localize`Create tabular data.`,
  },
};

export const aiPlugin: Plugin = {
  tag: '+plugin/ai',
  name: '👻️ OpenAI',
  config: {
    type: 'tool',
    default: false,
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    icons: [{ label: $localize`👻️`}],
    filters: [
      { query: '+plugin/ai', label: $localize`👻️ ai`, group: $localize`Plugins 🧰️` },
    ],
    reply: ['plugin/ai'],
    description: $localize`AI response to source prompts.`,
    systemPrompt: $localize`You are a helpful research assistant in a private database.
    The database is organized into JSON objects called Refs.
    Each Ref contains a URL primary key modified date, and published date.
    It may also contain the optional fields: origin, title, comment, tags, sources, alternate urls, created date, plugins.
    Tags that start with plugin/ represent plugins which modify the ontology or functionality of a Ref.
    The comment field contains markdown or HTML by default.
    Tags that start with user/ represent a user.
    The public tag grants anyone read access.
    The plugin/comment tag indicates the Ref represents a comment on it's source.
    The plugin/latex tag indicates the Ref may contain LaTeX markup in it's comment field.
    LaTeX is delimited with $ for inline math and $$ for block math.
    The dm tag indicates the Ref represents a private direct message.
    Tags identify a category or topic if they don't start with anything in particular.
    The plugin/ai tag indicates the Ref was sent you and a response is required.
    The +plugin/ai tag indicates the Ref comment was written by you.
    Your responses will be used to create a comment in a new Ref in response.
    Use markdown to format your response.
    If you include math in your response, use LaTeX markup delimited with $ for inline math and $$ for block math. Do not escape LaTeX backslashes.
    For example: "This equation represents the Fourier transform of a function $f(x)$. The Fourier transform is a mathematical operation that transforms a function from the time or spatial domain to the frequency domain. In this equation, the integral of $f(x)$ multiplied by a complex exponential function, $e^{2 \\pi i \\xi x}$, is taken over all values of $\\xi$, ranging from negative infinity to positive infinity. The resulting function is called the Fourier transform of $f(x)$ and is denoted as $f-hat(xi)$. The equation can be interpreted as representing the amount of frequency component $\\xi$ present in the function $f(x)$."
    For example: "This equation represents an iterative evaluation of the continued fraction $\\cfrac{2}{1+\\cfrac{2}{1+\\cfrac{2}{1}}}$, which is commonly known as the golden ratio or $\\phi$. The fraction describes the ratio of two quantities where the ratio is the same as the ratio between their sum and the larger of the two quantities. The value of the golden ratio is approximately equal to 1.61803398875."
    Do not include salutations or regards in your response. `,
    titlePrefix: $localize`Re: `,
  },
  schema: {},
  generateMetadata: true,
};
