import * as moment from 'moment';
import { Plugin } from '../model/plugin';

export const archivePlugin: Plugin = {
  tag: 'plugin/archive',
  name: $localize`Archive`,
  config: {
    type: 'viewer',
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    form: [{
      key: 'url',
      type: 'url',
      props: {
        label: $localize`URL:`,
      },
    }],
  },
  defaults: {},
  schema: {
    optionalProperties: {
      url: { type: 'string' },
    },
  },
};
