import * as moment from 'moment';
import { Plugin } from '../model/plugin';

export const archivePlugin: Plugin = {
  tag: 'plugin/archive',
  name: 'Archive',
  config: {
    generated: 'Generated by jasper-ui ' + moment().toISOString(),
  },
  defaults: {},
  schema: {
    optionalProperties: {
      url: { type: 'string' },
    },
  },
};
