import * as moment from 'moment';
import { Plugin } from '../model/plugin';

export const chartPlugin: Plugin = {
  tag: 'plugin/chart',
  name: '📊️ Chart',
  config: {
    type: 'viewer',
    default: true,
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    submit: $localize`📊️ chart`,
    icons: [{ label: $localize`📊️`}],
    filters: [
      { query: 'plugin/chart', label: $localize`📊️ chart`, group: $localize`Plugins 🧰️` },
    ],
    description: $localize`Draw a chart from a data table.`,
  },
};
