import * as moment from 'moment';

export const commentPlugin = {
  tag: 'plugin/comment',
  config: {
    generated: 'Generated by jenkins-ui ' + moment().toISOString(),
  },
  defaults: {},
  schema: {
    optionalProperties: {
      deleted: { type: 'boolean' },
    },
  },
};
