import * as moment from 'moment';
import { Plugin } from '../model/plugin';

export const htmlPlugin: Plugin = {
  tag: 'plugin/html',
  name: $localize`📐️ HTML Editor`,
  config: {
    type: 'editor',
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    editor: $localize`📐️️ html`,
  },
};

export const latexPlugin: Plugin = {
  tag: 'plugin/latex',
  name: $localize`💲️ LaTeX`,
  config: {
    type: 'editor',
    default: true,
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    description: $localize`Adds LaTeX support to the markdown editor. Use $ to mark inline math, $$ to mark block math.`,
    editor: $localize`💲️ latex`,
  },
};
