import * as moment from 'moment';
import { Plugin } from '../model/plugin';

export const emojiPlugin: Plugin = {
  tag: 'plugin/emoji',
  name: $localize`Markdown Emoji`,
  config: {
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    editor: $localize`🏷️ emoji`,
  },
};

export const htmlPlugin: Plugin = {
  tag: 'plugin/html',
  name: $localize`HTML Editor`,
  config: {
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    editor: $localize`🏷️ html`,
  },
};

export const latexPlugin: Plugin = {
  tag: 'plugin/latex',
  name: $localize`Markdown LaTeX`,
  config: {
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    editor: $localize`🏷️ latex`,
  },
};
