import * as moment from 'moment';
import { Plugin } from '../model/plugin';

export const emojiPlugin: Plugin = {
  tag: 'plugin/emoji',
  name: 'Markdown Emoji',
  config: {
    generated: 'Generated by jasper-ui ' + moment().toISOString(),
  },
};
