import * as moment from 'moment';
import { Plugin } from '../model/plugin';

export const feedPlugin: Plugin = {
  tag: '+plugin/feed',
  name: 'RSS/Atom Feed Plugin',
  config: {
    generated: 'Generated by jenkins-ui ' + moment().toISOString(),
  },
  defaults: {
    scrapeInterval: 'PT15M',
  },
  schema: {
    properties: {
      scrapeInterval: { type: 'string' },
    },
    optionalProperties: {
      addTags: { elements: { type: 'string' } },
      lastScrape: { type: 'string' },
      scrapeDescription: { type: 'boolean' },
      removeDescriptionIndent: { type: 'boolean' },
    },
  },
};
