import * as moment from 'moment';
import { Plugin } from '../model/plugin';

export const imagePlugin: Plugin = {
  tag: 'plugin/image',
  name: 'Image Plugin',
  config: {
    generated: 'Generated by jenkins-ui ' + moment().toISOString(),
  },
  defaults: {},
  schema: {
    optionalProperties: {
      url: { type: 'string' },
    },
  },
};

export const imageExtensions = ['.png', '.jpg', '.jpeg', '.gif', '.svg', '.webp'];

export function isImage(url: string) {
  return imageExtensions.includes(url.slice(url.lastIndexOf('.')).toLowerCase());
}
