import * as moment from 'moment';
import { Plugin } from '../model/plugin';

export const invoicePlugin: Plugin = {
  tag: 'plugin/invoice',
  name: 'Invoice Plugin',
  config: {
    generated: 'Generated by jenkins-ui ' + moment().toISOString(),
  },
  generateMetadata: true,
};

export const invoiceRejectionPlugin: Plugin = {
  tag: 'plugin/invoice/rejected',
  name: 'Invoice Rejected Plugin',
  config: {
    generated: 'Generated by jenkins-ui ' + moment().toISOString(),
  },
  generateMetadata: true,
};

export const invoiceDisputedPlugin: Plugin = {
  tag: 'plugin/invoice/disputed',
  name: 'Invoice Disputed Plugin',
  config: {
    generated: 'Generated by jenkins-ui ' + moment().toISOString(),
  },
  generateMetadata: true,
};

export const invoicePaidPlugin: Plugin = {
  tag: 'plugin/invoice/paid',
  name: 'Invoice Paid Plugin',
  config: {
    generated: 'Generated by jenkins-ui ' + moment().toISOString(),
  },
  generateMetadata: true,
};
