import * as moment from 'moment';
import { Plugin } from '../model/plugin';

export const latexPlugin: Plugin = {
  tag: 'plugin/latex',
  name: 'Markdown LaTeX Plugin',
  config: {
    generated: 'Generated by jenkins-ui ' + moment().toISOString(),
  },
};
