import * as moment from 'moment';
import { Plugin } from '../model/plugin';

export const lockedPlugin: Plugin = {
  tag: 'plugin/locked',
  name: $localize`Locked Icon`,
  config: {
    default: true,
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    icons: [
      { label: $localize`🔒️`, tag: 'locked', title: $localize`Locked` },
    ],
  },
};

