import * as moment from 'moment';
import { Plugin } from '../model/plugin';

export const lockedPlugin: Plugin = {
  tag: 'plugin/locked',
  name: $localize`🔒️ Locked Icon`,
  config: {
    type: 'core',
    default: true,
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    description: $localize`Show locked icon on locked Refs.`,
    icons: [
      { label: $localize`🔒️`, tag: 'locked', title: $localize`Locked`, global: true },
    ],
  },
};

