import * as moment from 'moment';
import { Plugin } from '../model/plugin';

export const oEmbedPlugin: Plugin = {
  tag: '+plugin/oembed',
  name: '📡️ oEmbed',
  config: {
    type: 'core',
    default: true,
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    settings: $localize`oembed`,
    icons: [{ label: $localize`📡️`}],
    description: $localize`Register a method for serverside oEmbed CORS buster.`,
  },
  schema: {
    optionalProperties: {
      provider_name: { type: 'string' },
      provider_url: { type: 'string' },
      endpoints: { elements: {
          optionalProperties: {
            url: { type: 'string' },
            discovery: { type: 'boolean' },
            schemes: { elements: { type: 'string' } },
            formats: { elements: { type: 'string' } },
          },
        },
      },
    },
  }
};
