import * as moment from 'moment';
import { Plugin } from '../model/plugin';

export const originPlugin: Plugin = {
  tag: '+plugin/origin',
  name: 'Remote Origin Replication Plugin',
  config: {
    generated: 'Generated by jenkins-ui ' + moment().toISOString(),
  },
  defaults: {
    scrapeInterval: 'PT15M',
  },
  schema: {
    properties: {
      scrapeInterval: { type: 'string' },
    },
    optionalProperties: {
      query: { type: 'string' },
      proxy: { type: 'string' },
      mapTags: { values: { type: 'string' } },
      addTags: { elements: { type: 'string' } },
      lastScrape: { type: 'string' },
    },
  },
};
