import * as moment from 'moment';
import { Plugin } from '../model/plugin';

export const personPlugin: Plugin = {
  tag: 'plugin/person',
  name: $localize`Person`,
  config: {
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    css: `
      .plugin-person .thumbnail {
        border-radius: 32px;
      }
    `,
  },
};
