import * as moment from 'moment';
import { Plugin } from '../model/plugin';

// @ts-ignore
window.global = {};
export const pollPlugin: Plugin = {
  tag: 'plugin/poll',
  name: $localize`🗳️ Poll`,
  config: {
    default: true,
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    description: $localize`Create a multiple choice poll and view the results.`,
    icons: [
      { label: $localize`🗳️` },
    ],
    submit: $localize`🗳️ poll`,
    genUrl: true,
    actions: [
      { response: 'plugin/poll.a', clear: ['plugin/poll.a', 'plugin/poll.b', 'plugin/poll.c', 'plugin/poll.d'], labelOff: $localize`A`, labelOn: $localize`unvote` },
      { response: 'plugin/poll.b', clear: ['plugin/poll.a', 'plugin/poll.b', 'plugin/poll.c', 'plugin/poll.d'], labelOff: $localize`B`, labelOn: $localize`unvote` },
      { response: 'plugin/poll.c', clear: ['plugin/poll.a', 'plugin/poll.b', 'plugin/poll.c', 'plugin/poll.d'], labelOff: $localize`C`, labelOn: $localize`unvote` },
      { response: 'plugin/poll.d', clear: ['plugin/poll.a', 'plugin/poll.b', 'plugin/poll.c', 'plugin/poll.d'], labelOff: $localize`D`, labelOn: $localize`unvote` },
    ],
    filters: [
      { query: 'plugin/poll', label: $localize`🗳️ poll`, group: $localize`Plugins 🧰️` },
    ],
    ui: `
      <table class="poll-results">
      <th><td></td><td>score</td></th>
        <tr><td>A:</td><td>{{ lookup ref.metadata.plugins 'plugin/poll.a' }}</td></tr>
        <tr><td>B:</td><td>{{ lookup ref.metadata.plugins 'plugin/poll.b' }}</td></tr>
        <tr><td>C:</td><td>{{ lookup ref.metadata.plugins 'plugin/poll.c' }}</td></tr>
        <tr><td>D:</td><td>{{ lookup ref.metadata.plugins 'plugin/poll.d' }}</td></tr>
      </table>
    `,
    form: [{
      key: 'a',
      type: 'input',
      props: {
        label: $localize`Option A:`,
      },
    }, {
      key: 'b',
      type: 'input',
      props: {
        label: $localize`Option B:`,
      },
    }, {
      key: 'c',
      type: 'input',
      props: {
        label: $localize`Option C:`,
      },
    },{
      key: 'd',
      type: 'input',
      props: {
        label: $localize`Option D:`,
      },
    }],
  },
  schema: {
    optionalProperties: {
      a: { type: 'string' },
      b: { type: 'string' },
      c: { type: 'string' },
      d: { type: 'string' },
    },
  },
};

export const pollOptionAPlugin: Plugin = {
  tag: 'plugin/poll.a',
  name: $localize`🎫️ Poll Option A`,
  config: {
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
  },
  generateMetadata: true,
  userUrl: true,
};

export const pollOptionBPlugin: Plugin = {
  tag: 'plugin/poll.b',
  name: $localize`🎫️ Poll Option B`,
  config: {
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
  },
  generateMetadata: true,
  userUrl: true,
};

export const pollOptionCPlugin: Plugin = {
  tag: 'plugin/poll.c',
  name: $localize`🎫️ Poll Option C`,
  config: {
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
  },
  generateMetadata: true,
  userUrl: true,
};

export const pollOptionDPlugin: Plugin = {
  tag: 'plugin/poll.d',
  name: $localize`🎫️ Poll Option D`,
  config: {
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
  },
  generateMetadata: true,
  userUrl: true,
};
