import * as moment from 'moment';
import { Plugin } from '../model/plugin';

export const snippetPlugin: Plugin = {
  tag: 'plugin/snippet',
  name: $localize`👨️‍💻️ Snippet`,
  config: {
    type: 'core',
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    snippet: `
      /*
       * Add your analytics trackers and other site scripts here.
       */
    `,
  },
};
