import * as moment from 'moment';
import { Plugin } from '../model/plugin';

export const thumbnailPlugin: Plugin = {
  tag: 'plugin/thumbnail',
  name: 'Thumbnail Plugin',
  config: {
    generated: 'Generated by jenkins-ui ' + moment().toISOString(),
  },
  defaults: {},
  schema: {
    optionalProperties: {
      url: { type: 'string' },
      height: { type: 'int32', nullable: true },
      width: { type: 'int32', nullable: true },
      time: { type: 'timestamp', nullable: true },
    },
  },
};
