import * as moment from 'moment';
import { Plugin } from '../model/plugin';
import { bitchuteHosts, getHost, imgurHosts, youtubeHosts } from '../util/hosts';
import { isImage } from './image';
import { isVideo } from './video';

export const thumbnailPlugin: Plugin = {
  tag: 'plugin/thumbnail',
  name: $localize`Thumbnail`,
  config: {
    type: 'viewer',
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    form: [{
      key: 'url',
      type: 'url',
      props: {
        label: $localize`URL:`,
      },
    }],
  },
  defaults: {},
  schema: {
    optionalProperties: {
      url: { type: 'string' },
    },
  },
};

export function isKnownThumbnail(url: string) {
  const host = getHost(url);
  if (!host) return false;
  return isImage(url) ||
    isVideo(url) ||
    youtubeHosts.includes(host) ||
    bitchuteHosts.includes(host) ||
    imgurHosts.includes(host);
}
