import * as moment from 'moment';
import { Plugin } from '../model/plugin';
import { imagePlugin } from './image';
import { videoPlugin } from './video';

export const thumbnailPlugin: Plugin = {
  tag: 'plugin/thumbnail',
  name: $localize`🍥️ Thumbnail`,
  config: {
    type: 'viewer',
    default: true,
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    extensions: [...videoPlugin.config!.extensions!, ...imagePlugin.config!.extensions!],
    form: [{
      key: 'url',
      type: 'url',
      props: {
        label: $localize`URL:`,
      },
    }],
  },
  defaults: {},
  schema: {
    optionalProperties: {
      url: { type: 'string' },
    },
  },
};
