import * as moment from 'moment';
import { Plugin } from '../model/plugin';

export const videoPlugin: Plugin = {
  tag: 'plugin/video',
  name: 'Video',
  config: {
    type: 'viewer',
    default: true,
    generated: $localize`Generated by jasper-ui ${moment().toISOString()}`,
    submit: $localize`🎞️ video`,
    icons: [{ label: $localize`🎞️`}],
    filters: [
      { query: 'plugin/video', label: $localize`🎞️ video`, group: $localize`Plugins 🧰️` },
    ],
    extensions: ['.3gp', '.mpg', '.mpeg', '.mp4', '.m4v', '.m4p', '.webm', '.ogv', '.m3u8', '.mov'],
    description: $localize`Play in an inline video player.`,
    form: [{
      key: 'url',
      type: 'url',
      props: {
        label: $localize`URL:`,
      },
    }],
  },
  defaults: {},
  schema: {
    optionalProperties: {
      url: { type: 'string' },
    },
  },
};
