import { DateTime } from 'luxon';
import { Plugin } from '../../model/plugin';
import { Mod } from '../../model/tag';
import { Template } from '../../model/template';

export const backgammonPlugin: Plugin = {
  tag: 'plugin/backgammon',
  name: $localize`🎲️ Backgammon`,
  config: {
    mod: $localize`🎲️ Backgammon`,
    type: 'plugin',
    submitText: true,
    editingViewer: true,
    generated: 'Generated by jenkins-ui ' + DateTime.now().toISO(),
    description: $localize`Activates built-in Backgammon game`,
    icons: [{ label: $localize`🎲️`, order: 3 }],
    published: $localize`played`,
    filters: [
      { query: 'plugin/backgammon', label: $localize`🎲️ backgammon`, title: $localize`Backgammon games`, group: $localize`Games 🕹️` },
    ],
    actions: [
      { tag: 'plugin/chat', labelOff: $localize`chat`, title: $localize`Open chatroom` },
      { event: 'flip', label: $localize`flip`, title: $localize`Spin the board 180 degrees.` },
      { event: 'reload', label: $localize`reload`, title: $localize`Reload the game.`  },
    ],
    // language=CSS
    css: `
      body.dark-theme {
        .backgammon-board {
          --bg: rgba(178, 103, 41, 0.2);
          --black: #111;
          --red: #633;
          --play: rgba(255, 255, 0, 0.3);
          --brown: #431;
          --brown-alt: #653;
          --glow: rgba(200, 200, 200, 0.5);
          --move: rgba(0, 128, 0, 0.5);
          border: 0.5px solid rgba(255, 255, 255, 0.2);
        }
        .replay-controls {
          background: rgba(20, 20, 20, 0.95);
          box-shadow: 0 -2px 10px rgba(0, 0, 0, 0.7);
          .scrubber-bar {
            background: rgba(200, 200, 200, 0.2);
            &::-webkit-slider-thumb {
              box-shadow: 0 0 4px rgba(255, 255, 255, 0.3);
            }
            &::-moz-range-thumb {
              box-shadow: 0 0 4px rgba(255, 255, 255, 0.3);
            }
          }
          .scrubber-ticks .scrubber-tick {
            background: #ffd700;
            box-shadow: 0 0 6px #ffd700;
            .tick-emoji {
              text-shadow: 0 0 3px rgba(0, 0, 0, 0.8);
            }
          }
          .control-buttons .replay-btn {
            background: rgba(200, 200, 200, 0.1);
            border-color: rgba(200, 200, 200, 0.3);
            &:hover:not(:disabled) {
              background: rgba(200, 200, 200, 0.2);
            }
          }
        }
      }
      body.light-theme {
        .backgammon-board {
          --bg: rgba(187, 147, 71, 0.5);
          --black: #333;
          --red: #A55;
          --play: #DDD;
          --brown: #862;
          --brown-alt: #975;
          --glow: rgba(0, 0, 0, 0.5);
          --move: rgba(82, 136, 82, 0.5);
          border: 0.5px solid transparent;
        }
        .replay-controls {
          background: var(--card);
          box-shadow: 0 -2px 10px rgba(0, 0, 0, 0.3);
          .scrubber-bar {
            background: rgba(50, 50, 50, 0.5);
            &::-webkit-slider-thumb {
              box-shadow: 0 0 4px rgba(0, 0, 0, 0.4);
            }
            &::-moz-range-thumb {
              box-shadow: 0 0 4px rgba(0, 0, 0, 0.4);
            }
          }
          .scrubber-ticks .scrubber-tick {
            background: #daa520;
            box-shadow: 0 0 4px #daa520;
            .tick-emoji {
              text-shadow: 0 0 2px rgba(255, 255, 255, 0.6);
            }
          }
          .control-buttons .replay-btn {
            background: rgba(60, 60, 60, 0.1);
            border-color: rgba(60, 60, 60, 0.3);
            &:hover:not(:disabled) {
              background: rgba(60, 60, 60, 0.2);
            }
          }
        }
      }
      .backgammon-piece {
        cursor: grab;
        text-align: center;
        vertical-align: middle;
        transition: transform 250ms cubic-bezier(0, 0, 0.2, 1), scale 250ms cubic-bezier(0, 0, 0.2, 1);
        &.cdk-drag-preview {
          overflow: visible;
          font-size: var(--drag-piece-size) !important;
          transform: scale(1.2);
        }
        &.disabled {
          cursor: default !important;
        }
      }
      .backgammon-spot, .backgammon-bar, .backgammon-off {
        .backgammon-piece.cdk-drag-placeholder {
          opacity: 0;
        }
        &:not(.drag-source) {
          .backgammon-piece.cdk-drag-placeholder {
            height: 0 !important;
          }
        }
      }
    `,
    form: [{
      key: 'redName',
      type: 'string',
      props: {
        label: $localize`Red Player Name`,
      }
    }, {
      key: 'blackName',
      type: 'string',
      props: {
        label: $localize`Black Player Name`,
      }
    }],
  },
  schema: {
    optionalProperties: {
      redName: { type: 'string' },
      blackName: { type: 'string' },
    }
  }
};

export const backgammonTemplate: Template = {
  tag: 'plugin/backgammon',
  name: $localize`🎲️ Backgammon`,
  config: {
    mod: $localize`🎲️ Backgammon`,
    type: 'plugin',
    generated: 'Generated by jenkins-ui ' + DateTime.now().toISO(),
    view: $localize`🎲️`,
    // language=CSS
    css: `
      app-ref-list.plugin_backgammon {
        .list-container {
          grid-auto-flow: row dense;
          padding: 4px;
          gap: 8px;
          grid-template-columns: minmax(0, 1fr);
          @media (min-width: 1500px) {
            grid-template-columns: minmax(0, 1fr) minmax(0, 1fr);
          }
          @media (min-width: 2000px) {
            grid-template-columns: minmax(0, 1fr) minmax(0, 1fr) minmax(0, 1fr);
          }
          .list-number {
            display: none;
          }
          .ref {
            min-width: 0;
            break-inside: avoid;
            .backgammon-board {
              max-height: unset;
            }
            .toggle {
              display: none;
            }
            @media (max-width: 740px) {
              .actions, .info {
                height: 28px;
              }
            }
          }
          .embed {
            display: block !important;
          }
        }
      }
    `,
    advancedForm: [{
      key: 'defaultExpanded',
      type: 'boolean',
      defaultValue: true,
      props: {
        label: $localize`Default Expanded:`,
      },
    }],
  },
  defaults: {
    defaultExpanded: true,
    defaultSort: ['modified,DESC'],
    defaultCols: 0, // Leave to CSS screen size detection, but show cols dropdown
  }
};

export const backgammonMod: Mod = {
  plugin: [
    backgammonPlugin,
  ],
   template: [
    backgammonTemplate,
  ],
};
