import { DateTime } from 'luxon';
import { Plugin } from '../../model/plugin';
import { Mod } from '../../model/tag';
import { Template } from '../../model/template';
import { RootConfig } from '../root';

const jezzballLabels = {
  savedExample: $localize`Saved example`,
  savedExampleTitle: $localize`This Ref is read-only; progress will not be saved.`,
  pause: $localize`Pause`,
  resume: $localize`Resume`,
  slow: $localize`Slow`,
  fast: $localize`Fast`,
  soundOn: $localize`Sound on`,
  soundOff: $localize`Sound off`,
  newGame: $localize`New game`,
  continue: $localize`Continue`,
  level: $localize`Level {level}`,
  lives: $localize`Lives {lives}`,
  filled: $localize`Filled {filled}%`,
  time: $localize`Time {time}`,
  score: $localize`Score {score}`,
  wallVertical: $localize`Wall ↕`,
  wallHorizontal: $localize`Wall ↔`,
  levelComplete: $localize`Level {level} complete`,
  gameOver: $localize`Game over · score {score}`,
  finalScore: $localize`Final score {score}`,
  help: $localize`Click, press Enter, or tap with two fingers to build a wall. Two-finger alignment sets its direction. Use the arrow keys to move the keyboard cursor. Right-click, Space, or the direction button changes direction. Press P to pause.`,
};
const jezzballLabelsSource = JSON.stringify(jezzballLabels).replace(/</g, '\\u003c');

export const jezzballPlugin: Plugin = {
  tag: 'plugin/jezzball',
  name: $localize`🟣️ JezzBall`,
  config: {
    mod: $localize`🟣️ JezzBall`,
    version: 1,
    type: 'plugin',
    editingViewer: true,
    experimental: true,
    submitText: true,
    add: true,
    genId: true,
    export: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Play a faithful remake of the classic JezzBall game.`,
    icons: [{ label: $localize`🟣️`, order: 2 }],
    filters: [
      { query: 'plugin/jezzball', label: $localize`🟣️ JezzBall`, title: $localize`JezzBall games`, group: $localize`Games 🕹️` },
    ],
    // language=HTML
    snippet: `
    <script>
      function jezzballApp(root, api) {
        if (!root) return function() {};
        if (root._jezzballDestroy) root._jezzballDestroy();

        const COLS = 32;
        const ROWS = 24;
        const CELL = 25;
        const TARGET = 75;
        const MAX_LEVEL = 100;
        const WALL_STEP_SLOW = 0.05;
        const WALL_STEP_FAST = 0.025;
        const BALL_RADIUS = 0.34;
        const LEVEL_SECONDS = 120;
        const labels = ${jezzballLabelsSource};
        const initial = api && api.initial && typeof api.initial === 'object' ? api.initial : {};
        const writable = !api || api.writable !== false;
        let level = Number.isInteger(initial.level) && initial.level > 0 ? Math.min(initial.level, MAX_LEVEL) : 1;
        let score = Number.isFinite(initial.score) && initial.score >= 0 ? Math.floor(initial.score) : 0;
        let checkpoint = { level: level, score: score, final: !!initial.final };
        let lives = 3;
        let remaining = LEVEL_SECONDS;
        let occupied = new Uint8Array(COLS * ROWS);
        let balls = [];
        let wall = null;
        let orientation = 'vertical';
        let wallSpeed = 'fast';
        let sound = true;
        let audioContext = null;
        let running = !checkpoint.final;
        let paused = false;
        let last = 0;
        let wallClock = 0;
        let frame = 0;
        let finalSaved = false;
        let keyboardMode = false;
        const keyboardCursor = { x: Math.floor(COLS / 2), y: Math.floor(ROWS / 2) };

        root.classList.add('jezzball-game');
        root.innerHTML = \`
          <style>
            .jezzball-game { display: block; width: min(100%, 850px); margin: 0 auto; color: var(--text, #ddd); font: 14px system-ui, sans-serif; outline: none; }
            .jezzball-game * { box-sizing: border-box; }
            .jezzball-toolbar { display: flex; align-items: center; min-height: 46px; padding: 8px 4px; }
            .jezzball-stat { position: absolute; z-index: 1; color: #eee; white-space: nowrap; pointer-events: none; text-shadow: 0 1px 2px #000; }
            .jezzball-lives { top: 8px; left: 10px; }
            .jezzball-center { position: absolute; z-index: 1; top: 8px; left: 50%; display: flex; gap: 16px; transform: translateX(-50%); }
            .jezzball-center .jezzball-stat { position: static; }
            .jezzball-time { top: 8px; right: 10px; }
            .jezzball-filled { bottom: 8px; left: 50%; transform: translateX(-50%); }
            .jezzball-example { color: #e7b85b; font-weight: 600; }
            .jezzball-controls { display: flex; gap: 8px; margin-left: auto; }
            .jezzball-controls button, .jezzball-overlay button { border: 1px solid var(--border, #777); border-radius: 4px; background: var(--card, #333); color: var(--text, #eee); padding: 5px 9px; cursor: pointer; }
            .jezzball-controls button:hover, .jezzball-overlay button:hover { background: var(--active, #4a4a4a); }
            .jezzball-stage { position: relative; width: 100%; aspect-ratio: 4 / 3; overflow: hidden; border: 2px solid #777; background: #000; touch-action: none; }
            .jezzball-canvas { display: block; width: 100%; height: 100%; }
            .jezzball-canvas.vertical { cursor: ns-resize; }
            .jezzball-canvas.horizontal { cursor: ew-resize; }
            .jezzball-overlay { position: absolute; inset: 0; display: none; place-content: center; text-align: center; background: rgba(0, 0, 0, .72); color: white; }
            .jezzball-overlay.visible { display: grid; }
            .jezzball-overlay strong { display: block; margin-bottom: 12px; font-size: 24px; }
            :fullscreen .jezzball-game { width: min(100vw, calc(100vh * 4 / 3)); max-width: none; }
            :fullscreen .jezzball-toolbar { display: none; }
            @media (prefers-color-scheme: light) {
              .jezzball-game { color: var(--text, #333); }
              .jezzball-controls button, .jezzball-overlay button { background: var(--card, #eee); color: var(--text, #222); border-color: var(--border, #999); }
              .jezzball-controls button:hover, .jezzball-overlay button:hover { background: var(--active, #ddd); }
            }
          </style>
          <div class="jezzball-toolbar">
            <span class="jezzball-example" title="\${labels.savedExampleTitle}">\${labels.savedExample}</span>
            <span class="jezzball-controls">
              <button class="jezzball-direction" type="button"></button>
              <button class="jezzball-speed" type="button"></button>
              <button class="jezzball-sound" type="button"></button>
              <button class="jezzball-pause" type="button">\${labels.pause}</button>
            </span>
          </div>
          <div class="jezzball-stage">
            <canvas class="jezzball-canvas" width="\${COLS * CELL}" height="\${ROWS * CELL}"></canvas>
            <span class="jezzball-stat jezzball-lives"></span>
            <span class="jezzball-center">
              <span class="jezzball-stat jezzball-level"></span>
              <span class="jezzball-stat jezzball-score"></span>
            </span>
            <span class="jezzball-stat jezzball-time"></span>
            <span class="jezzball-stat jezzball-filled"></span>
            <div class="jezzball-overlay"><div><strong></strong><button class="jezzball-new-game" type="button">\${labels.newGame}</button></div></div>
          </div>
        \`;

        const canvas = root.querySelector('.jezzball-canvas');
        const g = canvas.getContext('2d', { alpha: false });
        const levelEl = root.querySelector('.jezzball-level');
        const livesEl = root.querySelector('.jezzball-lives');
        const filledEl = root.querySelector('.jezzball-filled');
        const timeEl = root.querySelector('.jezzball-time');
        const scoreEl = root.querySelector('.jezzball-score');
        const exampleEl = root.querySelector('.jezzball-example');
        const directionButton = root.querySelector('.jezzball-direction');
        const speedButton = root.querySelector('.jezzball-speed');
        const soundButton = root.querySelector('.jezzball-sound');
        const pauseButton = root.querySelector('.jezzball-pause');
        const overlay = root.querySelector('.jezzball-overlay');
        const overlayMessage = overlay.querySelector('strong');
        const newGameButton = overlay.querySelector('.jezzball-new-game');
        root.tabIndex = 0;
        root.setAttribute('aria-label', labels.help);
        exampleEl.hidden = writable;

        function format(label, values) {
          return label.replace(/\\{(\\w+)\\}/g, function(match, key) {
            return Object.prototype.hasOwnProperty.call(values, key) ? values[key] : match;
          });
        }

        function id(x, y) {
          return x + y * COLS;
        }

        function isOccupied(x, y) {
          return x < 0 || y < 0 || x >= COLS || y >= ROWS || occupied[id(x, y)] !== 0;
        }

        function cellBlocked(x, y) {
          if (isOccupied(x, y)) return true;
          const cellId = id(x, y);
          return !!(wall && (wall.negative.cells.has(cellId) || wall.positive.cells.has(cellId)));
        }

        function randomVelocity() {
          const speed = 4.3 + Math.min(level, 12) * 0.08;
          const angle = Math.PI / 5 + Math.random() * Math.PI * 0.3;
          return {
            vx: speed * Math.cos(angle) * (Math.random() < 0.5 ? -1 : 1),
            vy: speed * Math.sin(angle) * (Math.random() < 0.5 ? -1 : 1),
          };
        }

        function placeBalls() {
          balls = [];
          for (let i = 0; i < level + 1; i++) {
            const velocity = randomVelocity();
            let x;
            let y;
            let attempts = 0;
            do {
              x = 2 + Math.random() * (COLS - 4);
              y = 2 + Math.random() * (ROWS - 4);
              attempts++;
            } while (balls.some(ball => Math.hypot(ball.x - x, ball.y - y) < 2) && attempts < 100);
            balls.push({ x: x, y: y, vx: velocity.vx, vy: velocity.vy, spin: Math.random() * Math.PI * 2 });
          }
        }

        function resetLevel() {
          occupied = new Uint8Array(COLS * ROWS);
          wall = null;
          lives = 3;
          remaining = LEVEL_SECONDS;
          paused = false;
          running = true;
          finalSaved = false;
          overlay.classList.remove('visible');
          pauseButton.textContent = labels.pause;
          placeBalls();
          updateHud();
        }

        function percentFilled() {
          let count = 0;
          for (const value of occupied) {
            if (value) count++;
          }
          return Math.floor(count * 100 / occupied.length);
        }

        function updateHud() {
          levelEl.textContent = format(labels.level, { level: level });
          livesEl.textContent = format(labels.lives, { lives: Math.max(0, lives) });
          filledEl.textContent = format(labels.filled, { filled: percentFilled() });
          timeEl.textContent = format(labels.time, { time: Math.max(0, Math.ceil(remaining)) });
          scoreEl.textContent = format(labels.score, { score: score });
          directionButton.textContent = orientation === 'vertical' ? labels.wallVertical : labels.wallHorizontal;
          speedButton.textContent = wallSpeed === 'slow' ? labels.slow : labels.fast;
          soundButton.textContent = sound ? labels.soundOn : labels.soundOff;
          canvas.classList.toggle('vertical', orientation === 'vertical');
          canvas.classList.toggle('horizontal', orientation === 'horizontal');
        }

        function toggleOrientation() {
          orientation = orientation === 'vertical' ? 'horizontal' : 'vertical';
          updateHud();
        }

        function toggleSpeed() {
          wallSpeed = wallSpeed === 'slow' ? 'fast' : 'slow';
          updateHud();
        }

        function toggleSound() {
          sound = !sound;
          updateHud();
        }

        function playSound(frequency, duration) {
          if (!sound) return;
          const AudioContext = window.AudioContext || window.webkitAudioContext;
          if (!AudioContext) return;
          audioContext = audioContext || new AudioContext();
          if (audioContext.state === 'suspended') audioContext.resume();
          const oscillator = audioContext.createOscillator();
          const gain = audioContext.createGain();
          oscillator.frequency.value = frequency;
          gain.gain.setValueAtTime(0.04, audioContext.currentTime);
          gain.gain.exponentialRampToValueAtTime(0.001, audioContext.currentTime + duration);
          oscillator.connect(gain);
          gain.connect(audioContext.destination);
          oscillator.start();
          oscillator.stop(audioContext.currentTime + duration);
        }

        function startWall(x, y) {
          x = Math.floor(x);
          y = Math.floor(y);
          if (!running || paused || wall || cellBlocked(x, y)) return;
          if (balls.some(ball => Math.hypot(ball.x - x - 0.5, ball.y - y - 0.5) < 1.2)) return;
          wall = {
            orientation: orientation,
            origin: { x: x, y: y },
            negative: { x: x, y: y, done: false, destroyed: false, color: 2, cells: new Set([id(x, y)]) },
            positive: { x: x, y: y, done: false, destroyed: false, color: 1, cells: new Set([id(x, y)]) },
          };
          wallClock = 0;
          playSound(260, 0.04);
        }

        function extendEnd(end, direction) {
          if (!wall || end.done || end.destroyed) return;
          const dx = wall.orientation === 'horizontal' ? direction : 0;
          const dy = wall.orientation === 'vertical' ? direction : 0;
          const nx = end.x + dx;
          const ny = end.y + dy;
          if (isOccupied(nx, ny)) {
            end.done = true;
            return;
          }
          end.x = nx;
          end.y = ny;
          end.cells.add(id(nx, ny));
        }

        function fillCapturedAreas() {
          const reachable = new Uint8Array(COLS * ROWS);
          const queue = [];
          for (const ball of balls) {
            const x = Math.max(0, Math.min(COLS - 1, Math.floor(ball.x)));
            const y = Math.max(0, Math.min(ROWS - 1, Math.floor(ball.y)));
            const ballId = id(x, y);
            if (!occupied[ballId] && !reachable[ballId]) {
              reachable[ballId] = 1;
              queue.push(ballId);
            }
          }
          for (let head = 0; head < queue.length; head++) {
            const current = queue[head];
            const x = current % COLS;
            const y = Math.floor(current / COLS);
            const neighbors = [[x - 1, y], [x + 1, y], [x, y - 1], [x, y + 1]];
            for (const neighbor of neighbors) {
              const nx = neighbor[0];
              const ny = neighbor[1];
              if (nx < 0 || ny < 0 || nx >= COLS || ny >= ROWS) continue;
              const neighborId = id(nx, ny);
              if (!occupied[neighborId] && !reachable[neighborId]) {
                reachable[neighborId] = 1;
                queue.push(neighborId);
              }
            }
          }
          for (let i = 0; i < occupied.length; i++) {
            if (!occupied[i] && !reachable[i]) occupied[i] = 3;
          }
        }

        function completeWall() {
          if (!wall) return;
          const completedHalves = [wall.negative, wall.positive].filter(half => !half.destroyed);
          if (!completedHalves.length) {
            wall = null;
            return;
          }
          for (const half of completedHalves) {
            for (const cellId of half.cells) occupied[cellId] = 3;
          }
          wall = null;
          playSound(480, 0.08);
          fillCapturedAreas();
          const filled = percentFilled();
          if (filled >= TARGET) {
            score += level * 100 + filled * 5 + Math.ceil(remaining) + lives * 25;
            level = Math.min(level + 1, MAX_LEVEL);
            checkpoint = { level: level, score: score, final: false };
            if (api && typeof api.save === 'function') api.save(checkpoint);
            playSound(720, 0.16);
            showMessage(format(labels.levelComplete, { level: level - 1 }), labels.continue, resetLevel);
          }
          updateHud();
        }

        function destroyHalf(half) {
          half.destroyed = true;
          half.cells.clear();
          lives--;
          playSound(120, 0.18);
          if (lives <= 0) {
            finishGame();
          } else if (wall && [wall.negative, wall.positive].every(part => part.done || part.destroyed)) {
            completeWall();
          }
          updateHud();
        }

        function finishGame() {
          if (!running) return;
          running = false;
          paused = false;
          playSound(80, 0.3);
          checkpoint = { level: level, score: score, final: true };
          if (!finalSaved && api && typeof api.save === 'function') {
            finalSaved = true;
            api.save(checkpoint);
          }
          showMessage(format(labels.gameOver, { score: score }), labels.newGame, function() {
            level = 1;
            score = 0;
            checkpoint = { level: 1, score: 0, final: false };
            if (writable && api && typeof api.save === 'function') api.save(checkpoint);
            resetLevel();
          });
        }

        function showMessage(message, button, callback) {
          running = false;
          overlayMessage.textContent = message;
          newGameButton.textContent = button;
          overlay.classList.add('visible');
          newGameButton.onclick = function() {
            overlay.classList.remove('visible');
            callback();
            root.focus();
          };
        }

        function ballTouchesHalf(ball, half, direction) {
          if (!wall) return false;
          const leadingCell = id(half.x, half.y);
          const originCell = id(wall.origin.x, wall.origin.y);
          const minX = Math.floor(ball.x - BALL_RADIUS);
          const maxX = Math.floor(ball.x + BALL_RADIUS);
          const minY = Math.floor(ball.y - BALL_RADIUS);
          const maxY = Math.floor(ball.y + BALL_RADIUS);
          for (let y = minY; y <= maxY; y++) {
            for (let x = minX; x <= maxX; x++) {
              const cellId = id(x, y);
              if (cellId === leadingCell || !half.cells.has(cellId)) continue;
              if (cellId === originCell) {
                const position = wall.orientation === 'horizontal' ? ball.x : ball.y;
                const center = (wall.orientation === 'horizontal' ? wall.origin.x : wall.origin.y) + 0.5;
                if ((direction < 0) !== (position < center)) continue;
              }
              const closestX = Math.max(x, Math.min(ball.x, x + 1));
              const closestY = Math.max(y, Math.min(ball.y, y + 1));
              if (Math.hypot(ball.x - closestX, ball.y - closestY) <= BALL_RADIUS) return true;
            }
          }
          return false;
        }

        function hitsBoard(x, y) {
          const minX = Math.floor(x - BALL_RADIUS);
          const maxX = Math.floor(x + BALL_RADIUS);
          const minY = Math.floor(y - BALL_RADIUS);
          const maxY = Math.floor(y + BALL_RADIUS);
          for (let cy = minY; cy <= maxY; cy++) {
            for (let cx = minX; cx <= maxX; cx++) {
              if (isOccupied(cx, cy)) return true;
              if (wall) {
                for (const half of [wall.negative, wall.positive]) {
                  if (half.destroyed) continue;
                  const cellId = id(cx, cy);
                  if ((half.done && half.cells.has(cellId)) ||
                      (!half.done && cellId === id(half.x, half.y))) return true;
                }
              }
            }
          }
          return false;
        }

        function updateBalls(dt) {
          for (const ball of balls) {
            let nextX = ball.x + ball.vx * dt;
            if (nextX - BALL_RADIUS < 0 || nextX + BALL_RADIUS > COLS || hitsBoard(nextX, ball.y)) {
              ball.vx *= -1;
              nextX = ball.x + ball.vx * dt;
            }
            ball.x = Math.max(BALL_RADIUS, Math.min(COLS - BALL_RADIUS, nextX));

            let nextY = ball.y + ball.vy * dt;
            if (nextY - BALL_RADIUS < 0 || nextY + BALL_RADIUS > ROWS || hitsBoard(ball.x, nextY)) {
              ball.vy *= -1;
              nextY = ball.y + ball.vy * dt;
            }
            ball.y = Math.max(BALL_RADIUS, Math.min(ROWS - BALL_RADIUS, nextY));
            ball.spin += dt * 7;
          }
        }

        function update(dt) {
          updateBalls(dt);
          if (wall) {
            wallClock += dt;
            const wallStep = wallSpeed === 'slow' ? WALL_STEP_SLOW : WALL_STEP_FAST;
            while (wall && wallClock >= wallStep) {
              wallClock -= wallStep;
              extendEnd(wall.negative, -1);
              extendEnd(wall.positive, 1);
              for (const [half, direction] of [[wall.negative, -1], [wall.positive, 1]]) {
                if (half.done || half.destroyed) continue;
                if (balls.some(ball => ballTouchesHalf(ball, half, direction))) {
                  destroyHalf(half);
                  if (!running || !wall) break;
                }
              }
              if (!running || !wall) break;
              if (wall && [wall.negative, wall.positive].every(half => half.done || half.destroyed)) completeWall();
            }
          }
          remaining -= dt;
          if (remaining <= 0) finishGame();
        }

        function draw() {
          g.fillStyle = '#000';
          g.fillRect(0, 0, canvas.width, canvas.height);

          for (let y = 0; y < ROWS; y++) {
            for (let x = 0; x < COLS; x++) {
              const color = occupied[id(x, y)];
              if (color) {
                g.fillStyle = '#777';
                g.fillRect(x * CELL, y * CELL, CELL, CELL);
              }
            }
          }

          g.strokeStyle = 'rgba(255,255,255,.08)';
          g.lineWidth = 1;
          for (let x = 1; x < COLS; x++) {
            g.beginPath();
            g.moveTo(x * CELL, 0);
            g.lineTo(x * CELL, canvas.height);
            g.stroke();
          }
          for (let y = 1; y < ROWS; y++) {
            g.beginPath();
            g.moveTo(0, y * CELL);
            g.lineTo(canvas.width, y * CELL);
            g.stroke();
          }

          if (wall) {
            for (const half of [wall.negative, wall.positive]) {
              if (half.destroyed) continue;
              g.fillStyle = half.color === 1 ? '#e3424f' : '#2f8ee5';
              for (const cellId of half.cells) {
                const x = cellId % COLS;
                const y = Math.floor(cellId / COLS);
                g.fillRect(x * CELL + 3, y * CELL + 3, CELL - 6, CELL - 6);
              }
              if (!half.done) {
                g.strokeStyle = '#ececf2';
                g.lineWidth = 2;
                g.strokeRect(half.x * CELL + 2, half.y * CELL + 2, CELL - 4, CELL - 4);
              }
            }
          }

          for (const ball of balls) {
            const x = ball.x * CELL;
            const y = ball.y * CELL;
            const radius = BALL_RADIUS * CELL;
            const phase = ((ball.spin % (Math.PI * 2)) + Math.PI * 2) % (Math.PI * 2);
            const curve = Math.cos(phase) * radius * 4 / 3;
            g.save();
            g.beginPath();
            g.arc(x, y, radius, 0, 7);
            g.clip();
            g.fillStyle = '#f4f1e8';
            g.fillRect(x - radius, y - radius, radius * 2, radius * 2);
            g.fillStyle = '#d93643';
            g.beginPath();
            g.moveTo(x, y - radius);
            g.bezierCurveTo(x + curve, y - radius, x + curve, y + radius, x, y + radius);
            g.arc(x, y, radius, Math.PI / 2, -Math.PI / 2, true);
            g.fill();
            g.restore();
            g.strokeStyle = '#ddd';
            g.lineWidth = 1;
            g.beginPath();
            g.arc(x, y, radius, 0, 7);
            g.stroke();
          }

          if (keyboardMode && root.matches(':focus-visible')) {
            const x = keyboardCursor.x * CELL;
            const y = keyboardCursor.y * CELL;
            g.strokeStyle = '#ffd54f';
            g.lineWidth = 3;
            g.strokeRect(x + 2, y + 2, CELL - 4, CELL - 4);
          }
        }

        function loop(now) {
          if (!root.isConnected) {
            root._jezzballDestroy();
            return;
          }
          if (!last) last = now;
          const dt = Math.min((now - last) / 1000, 0.05);
          last = now;
          if (running && !paused) update(dt);
          draw();
          updateHud();
          frame = requestAnimationFrame(loop);
        }

        function canvasPoint(event) {
          const rect = canvas.getBoundingClientRect();
          return {
            x: (event.clientX - rect.left) * COLS / rect.width,
            y: (event.clientY - rect.top) * ROWS / rect.height,
          };
        }

        const touchPoints = new Map();

        function onPointerDown(event) {
          root.focus();
          keyboardMode = false;
          if (event.pointerType === 'touch') {
            event.preventDefault();
            touchPoints.set(event.pointerId, canvasPoint(event));
            if (touchPoints.size !== 2) return;
            const points = Array.from(touchPoints.values());
            const dx = Math.abs(points[1].x - points[0].x);
            const dy = Math.abs(points[1].y - points[0].y);
            if (dx > dy * Math.sqrt(3)) {
              orientation = 'horizontal';
            } else if (dy > dx * Math.sqrt(3)) {
              orientation = 'vertical';
            } else {
              return;
            }
            updateHud();
            startWall((points[0].x + points[1].x) / 2, (points[0].y + points[1].y) / 2);
            return;
          }
          if (event.button === 2) {
            event.preventDefault();
            toggleOrientation();
            return;
          }
          const point = canvasPoint(event);
          startWall(point.x, point.y);
        }

        function onPointerUp(event) {
          touchPoints.delete(event.pointerId);
        }

        function onKeyDown(event) {
          if (event.target.closest('input, textarea, select, button, [contenteditable="true"]')) return;
          if (event.key === 'ArrowLeft' || event.key === 'ArrowRight' ||
              event.key === 'ArrowUp' || event.key === 'ArrowDown') {
            event.preventDefault();
            keyboardMode = true;
            if (event.key === 'ArrowLeft') keyboardCursor.x = Math.max(0, keyboardCursor.x - 1);
            if (event.key === 'ArrowRight') keyboardCursor.x = Math.min(COLS - 1, keyboardCursor.x + 1);
            if (event.key === 'ArrowUp') keyboardCursor.y = Math.max(0, keyboardCursor.y - 1);
            if (event.key === 'ArrowDown') keyboardCursor.y = Math.min(ROWS - 1, keyboardCursor.y + 1);
          } else if (event.key === 'Enter') {
            event.preventDefault();
            keyboardMode = true;
            startWall(keyboardCursor.x, keyboardCursor.y);
          } else if (event.code === 'Space') {
            event.preventDefault();
            toggleOrientation();
          } else if (event.key.toLowerCase() === 'p') {
            event.preventDefault();
            togglePause();
          }
        }

        function togglePause() {
          if (!running) return;
          paused = !paused;
          pauseButton.textContent = paused ? labels.resume : labels.pause;
        }

        canvas.addEventListener('pointerdown', onPointerDown);
        canvas.addEventListener('pointerup', onPointerUp);
        canvas.addEventListener('pointercancel', onPointerUp);
        canvas.addEventListener('contextmenu', function(event) { event.preventDefault(); });
        directionButton.addEventListener('click', toggleOrientation);
        speedButton.addEventListener('click', toggleSpeed);
        soundButton.addEventListener('click', toggleSound);
        pauseButton.addEventListener('click', togglePause);
        root.addEventListener('keydown', onKeyDown);

        root._jezzballDestroy = function() {
          cancelAnimationFrame(frame);
          canvas.removeEventListener('pointerdown', onPointerDown);
          canvas.removeEventListener('pointerup', onPointerUp);
          canvas.removeEventListener('pointercancel', onPointerUp);
          directionButton.removeEventListener('click', toggleOrientation);
          speedButton.removeEventListener('click', toggleSpeed);
          soundButton.removeEventListener('click', toggleSound);
          pauseButton.removeEventListener('click', togglePause);
          root.removeEventListener('keydown', onKeyDown);
          if (audioContext) audioContext.close();
          root._jezzballDestroy = null;
        };

        if (checkpoint.final) {
          placeBalls();
          showMessage(format(labels.finalScore, { score: score }), labels.newGame, function() {
            level = 1;
            score = 0;
            checkpoint = { level: 1, score: 0, final: false };
            if (writable && api && typeof api.save === 'function') api.save(checkpoint);
            resetLevel();
          });
        } else {
          resetLevel();
        }
        frame = requestAnimationFrame(loop);
        return root._jezzballDestroy;
      }

      Handlebars.registerHelper('jezzball', function(ref, actions, el) {
        return function() {
          const root = el && el.querySelector ? el.querySelector('.jezzball-game') : document.querySelector('.jezzball-game');
          let initial = {};
          try {
            initial = ref && ref.comment ? JSON.parse(ref.comment) : {};
          } catch (error) {
            initial = {};
          }
          const savedScore = ref && ref.plugins && ref.plugins['plugin/score'];
          if (Number.isFinite(savedScore) && savedScore >= 0) initial.score = savedScore;
          jezzballApp(root, {
            initial: initial,
            writable: !actions || (!!actions.comment && !!actions.plugin),
            save: actions && actions.comment && actions.plugin ? function(state) {
              actions.comment(JSON.stringify({ level: state.level, final: state.final }));
              actions.plugin('plugin/score', state.score);
            } : undefined,
          });
        };
      });
    </script>
    `,
    // language=Handlebars
    ui: `
      <div class="jezzball-game">{{defer el (jezzball ref actions el)}}</div>
    `,
  },
};

export const jezzballTemplate: Template = {
  tag: 'plugin/jezzball',
  name: $localize`🟣️ JezzBall`,
  config: {
    mod: $localize`🟣️ JezzBall`,
    version: 1,
    type: 'plugin',
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    view: $localize`🟣️`,
    // language=CSS
    css: `
      app-ref-list.plugin_jezzball {
        .list-container {
          grid-auto-flow: row dense;
          padding: 4px;
          gap: 8px;
          grid-template-columns: minmax(0, 1fr);
          .list-number {
            display: none;
          }
          .ref {
            min-width: 0;
            break-inside: avoid;
            .toggle {
              display: none;
            }
          }
        }
      }
    `,
    advancedForm: [{
      key: 'defaultExpanded',
      type: 'boolean',
      defaultValue: true,
      props: {
        label: $localize`Default Expanded:`,
      },
    }],
  },
  defaults: <RootConfig> {
    defaultExpanded: true,
    submitText: true,
    defaultSort: ['plugins->plugin/score:num,DESC', 'modified,DESC'],
    defaultCols: 1,
  },
};

export const jezzballMod: Mod = {
  plugin: [
    jezzballPlugin,
  ],
  template: [
    jezzballTemplate,
  ],
};
