import { DateTime } from 'luxon';
import { Plugin } from '../../model/plugin';
import { Mod } from '../../model/tag';
import { Template } from '../../model/template';
import { RootConfig } from '../root';

const jezzballLabels = {
  savedExample: $localize`Saved example`,
  savedExampleTitle: $localize`This Ref is read-only; progress will not be saved.`,
  pause: $localize`Pause`,
  resume: $localize`Resume`,
  eject: $localize`Eject`,
  ejectTitle: $localize`Download a portable game`,
  newGame: $localize`New game`,
  continue: $localize`Continue`,
  level: $localize`Level {level}`,
  lives: $localize`Lives {lives}`,
  filled: $localize`Filled {filled}% / {target}%`,
  time: $localize`Time {time}`,
  score: $localize`Score {score}`,
  wallVertical: $localize`Wall ↕`,
  wallHorizontal: $localize`Wall ↔`,
  levelComplete: $localize`Level {level} complete`,
  gameOver: $localize`Game over · score {score}`,
  finalScore: $localize`Final score {score}`,
  help: $localize`Click or press Enter to build a wall. Use the arrow keys to move the keyboard cursor. Right-click, Space, or the direction button changes direction. Press P to pause.`,
};
const jezzballLabelsSource = JSON.stringify(jezzballLabels).replace(/</g, '\\u003c');

export const jezzballPlugin: Plugin = {
  tag: 'plugin/jezzball',
  name: $localize`🟣️ JezzBall`,
  config: {
    mod: $localize`🟣️ JezzBall`,
    version: 1,
    type: 'plugin',
    editingViewer: true,
    experimental: true,
    submitText: true,
    add: true,
    genId: true,
    export: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Play a faithful remake of the classic JezzBall game.`,
    icons: [{ label: $localize`🟣️`, order: 2 }],
    filters: [
      { query: 'plugin/jezzball', label: $localize`🟣️ JezzBall`, title: $localize`JezzBall games`, group: $localize`Games 🕹️` },
    ],
    // language=HTML
    snippet: `
    <script>
      function jezzballApp(root, api) {
        if (!root) return function() {};
        if (root._jezzballDestroy) root._jezzballDestroy();

        const COLS = 32;
        const ROWS = 24;
        const CELL = 25;
        const TARGET = 75;
        const MAX_LEVEL = 100;
        const WALL_STEP = 0.035;
        const BALL_RADIUS = 0.34;
        const LEVEL_SECONDS = 120;
        const labels = ${jezzballLabelsSource};
        const initial = api && api.initial && typeof api.initial === 'object' ? api.initial : {};
        const writable = !api || api.writable !== false;
        let level = Number.isInteger(initial.level) && initial.level > 0 ? Math.min(initial.level, MAX_LEVEL) : 1;
        let score = Number.isFinite(initial.score) && initial.score >= 0 ? Math.floor(initial.score) : 0;
        let checkpoint = { level: level, score: score, final: !!initial.final };
        let lives = 3;
        let remaining = LEVEL_SECONDS;
        let occupied = new Uint8Array(COLS * ROWS);
        let balls = [];
        let wall = null;
        let orientation = 'vertical';
        let running = !checkpoint.final;
        let paused = false;
        let last = 0;
        let wallClock = 0;
        let frame = 0;
        let finalSaved = false;
        let keyboardMode = false;
        const keyboardCursor = { x: Math.floor(COLS / 2), y: Math.floor(ROWS / 2) };

        root.classList.add('jezzball-game');
        root.innerHTML = \`
          <style>
            .jezzball-game { display: block; width: min(100%, 850px); margin: 0 auto; color: #ddd; font: 14px system-ui, sans-serif; outline: none; }
            .jezzball-game * { box-sizing: border-box; }
            .jezzball-hud { display: flex; flex-wrap: wrap; align-items: center; gap: 8px 16px; padding: 8px 4px; }
            .jezzball-stat { white-space: nowrap; }
            .jezzball-example { color: #e7b85b; font-weight: 600; }
            .jezzball-controls { display: flex; gap: 8px; margin-left: auto; }
            .jezzball-controls button, .jezzball-overlay button { border: 1px solid #777; border-radius: 4px; background: #333; color: #eee; padding: 5px 9px; cursor: pointer; }
            .jezzball-controls button:hover, .jezzball-overlay button:hover { background: #4a4a4a; }
            .jezzball-stage { position: relative; width: 100%; aspect-ratio: 4 / 3; overflow: hidden; border: 2px solid #777; background: #050505; touch-action: none; }
            .jezzball-canvas { display: block; width: 100%; height: 100%; cursor: crosshair; }
            .jezzball-overlay { position: absolute; inset: 0; display: none; place-content: center; text-align: center; background: rgba(0, 0, 0, .72); color: white; }
            .jezzball-overlay.visible { display: grid; }
            .jezzball-overlay strong { display: block; margin-bottom: 12px; font-size: 24px; }
            .jezzball-help { margin: 6px 4px 0; color: #999; font-size: 12px; }
            body.light-theme .jezzball-game { color: #333; }
            body.light-theme .jezzball-controls button, body.light-theme .jezzball-overlay button { background: #eee; color: #222; border-color: #999; }
            body.light-theme .jezzball-controls button:hover, body.light-theme .jezzball-overlay button:hover { background: #ddd; }
            @media (prefers-color-scheme: light) {
              body:not(.light-theme):not(.dark-theme) .jezzball-game { color: #333; }
              body:not(.light-theme):not(.dark-theme) .jezzball-controls button,
              body:not(.light-theme):not(.dark-theme) .jezzball-overlay button { background: #eee; color: #222; border-color: #999; }
              body:not(.light-theme):not(.dark-theme) .jezzball-controls button:hover,
              body:not(.light-theme):not(.dark-theme) .jezzball-overlay button:hover { background: #ddd; }
            }
          </style>
          <div class="jezzball-hud">
            <span class="jezzball-stat jezzball-level"></span>
            <span class="jezzball-stat jezzball-lives"></span>
            <span class="jezzball-stat jezzball-filled"></span>
            <span class="jezzball-stat jezzball-time"></span>
            <span class="jezzball-stat jezzball-score"></span>
            <span class="jezzball-stat jezzball-example" title="\${labels.savedExampleTitle}">\${labels.savedExample}</span>
            <span class="jezzball-controls">
              <button class="jezzball-direction" type="button"></button>
              <button class="jezzball-pause" type="button">\${labels.pause}</button>
              <button class="jezzball-eject" type="button" title="\${labels.ejectTitle}">\${labels.eject}</button>
            </span>
          </div>
          <div class="jezzball-stage">
            <canvas class="jezzball-canvas" width="\${COLS * CELL}" height="\${ROWS * CELL}"></canvas>
            <div class="jezzball-overlay"><div><strong></strong><button type="button">\${labels.newGame}</button></div></div>
          </div>
          <p class="jezzball-help">\${labels.help}</p>
        \`;

        const canvas = root.querySelector('.jezzball-canvas');
        const ctx = canvas.getContext('2d', { alpha: false });
        const levelEl = root.querySelector('.jezzball-level');
        const livesEl = root.querySelector('.jezzball-lives');
        const filledEl = root.querySelector('.jezzball-filled');
        const timeEl = root.querySelector('.jezzball-time');
        const scoreEl = root.querySelector('.jezzball-score');
        const exampleEl = root.querySelector('.jezzball-example');
        const directionButton = root.querySelector('.jezzball-direction');
        const pauseButton = root.querySelector('.jezzball-pause');
        const ejectButton = root.querySelector('.jezzball-eject');
        const overlay = root.querySelector('.jezzball-overlay');
        const overlayMessage = overlay.querySelector('strong');
        const newGameButton = overlay.querySelector('button');
        root.tabIndex = 0;
        root.setAttribute('aria-label', labels.help);
        exampleEl.hidden = writable;

        function format(label, values) {
          return label.replace(/\\{(\\w+)\\}/g, function(match, key) {
            return Object.prototype.hasOwnProperty.call(values, key) ? values[key] : match;
          });
        }

        function id(x, y) {
          return x + y * COLS;
        }

        function isOccupied(x, y) {
          return x < 0 || y < 0 || x >= COLS || y >= ROWS || occupied[id(x, y)] === 1;
        }

        function activeCells() {
          return wall ? wall.cells : null;
        }

        function cellBlocked(x, y) {
          return isOccupied(x, y) || !!(wall && wall.cells.has(id(x, y)));
        }

        function randomVelocity() {
          const speed = 4.3 + Math.min(level, 12) * 0.08;
          const angle = Math.PI / 5 + Math.random() * Math.PI * 0.3;
          return {
            vx: speed * Math.cos(angle) * (Math.random() < 0.5 ? -1 : 1),
            vy: speed * Math.sin(angle) * (Math.random() < 0.5 ? -1 : 1),
          };
        }

        function placeBalls() {
          balls = [];
          for (let i = 0; i < level + 1; i++) {
            const velocity = randomVelocity();
            let x;
            let y;
            let attempts = 0;
            do {
              x = 2 + Math.random() * (COLS - 4);
              y = 2 + Math.random() * (ROWS - 4);
              attempts++;
            } while (balls.some(ball => Math.hypot(ball.x - x, ball.y - y) < 2) && attempts < 100);
            balls.push({ x: x, y: y, vx: velocity.vx, vy: velocity.vy });
          }
        }

        function resetLevel() {
          occupied = new Uint8Array(COLS * ROWS);
          wall = null;
          lives = 3;
          remaining = LEVEL_SECONDS;
          paused = false;
          running = true;
          finalSaved = false;
          overlay.classList.remove('visible');
          pauseButton.textContent = labels.pause;
          placeBalls();
          updateHud();
        }

        function percentFilled() {
          let count = 0;
          for (const value of occupied) count += value;
          return Math.floor(count * 100 / occupied.length);
        }

        function updateHud() {
          levelEl.textContent = format(labels.level, { level: level });
          livesEl.textContent = format(labels.lives, { lives: Math.max(0, lives) });
          filledEl.textContent = format(labels.filled, { filled: percentFilled(), target: TARGET });
          timeEl.textContent = format(labels.time, { time: Math.max(0, Math.ceil(remaining)) });
          scoreEl.textContent = format(labels.score, { score: score });
          directionButton.textContent = orientation === 'vertical' ? labels.wallVertical : labels.wallHorizontal;
        }

        function toggleOrientation() {
          orientation = orientation === 'vertical' ? 'horizontal' : 'vertical';
          updateHud();
        }

        function startWall(x, y) {
          x = Math.floor(x);
          y = Math.floor(y);
          if (!running || paused || wall || cellBlocked(x, y)) return;
          if (balls.some(ball => Math.hypot(ball.x - x - 0.5, ball.y - y - 0.5) < 1.2)) return;
          wall = {
            orientation: orientation,
            negative: { x: x, y: y, done: false },
            positive: { x: x, y: y, done: false },
            cells: new Set([id(x, y)]),
          };
          wallClock = 0;
        }

        function extendEnd(end, direction) {
          if (!wall || end.done) return;
          const dx = wall.orientation === 'horizontal' ? direction : 0;
          const dy = wall.orientation === 'vertical' ? direction : 0;
          const nx = end.x + dx;
          const ny = end.y + dy;
          if (isOccupied(nx, ny)) {
            end.done = true;
            return;
          }
          end.x = nx;
          end.y = ny;
          wall.cells.add(id(nx, ny));
        }

        function fillCapturedAreas() {
          const reachable = new Uint8Array(COLS * ROWS);
          const queue = [];
          for (const ball of balls) {
            const x = Math.max(0, Math.min(COLS - 1, Math.floor(ball.x)));
            const y = Math.max(0, Math.min(ROWS - 1, Math.floor(ball.y)));
            const ballId = id(x, y);
            if (!occupied[ballId] && !reachable[ballId]) {
              reachable[ballId] = 1;
              queue.push(ballId);
            }
          }
          for (let head = 0; head < queue.length; head++) {
            const current = queue[head];
            const x = current % COLS;
            const y = Math.floor(current / COLS);
            const neighbors = [[x - 1, y], [x + 1, y], [x, y - 1], [x, y + 1]];
            for (const neighbor of neighbors) {
              const nx = neighbor[0];
              const ny = neighbor[1];
              if (nx < 0 || ny < 0 || nx >= COLS || ny >= ROWS) continue;
              const neighborId = id(nx, ny);
              if (!occupied[neighborId] && !reachable[neighborId]) {
                reachable[neighborId] = 1;
                queue.push(neighborId);
              }
            }
          }
          for (let i = 0; i < occupied.length; i++) {
            if (!occupied[i] && !reachable[i]) occupied[i] = 1;
          }
        }

        function completeWall() {
          if (!wall) return;
          for (const cellId of wall.cells) occupied[cellId] = 1;
          wall = null;
          fillCapturedAreas();
          const filled = percentFilled();
          if (filled >= TARGET) {
            score += level * 100 + filled * 5 + Math.ceil(remaining) + lives * 25;
            level = Math.min(level + 1, MAX_LEVEL);
            checkpoint = { level: level, score: score, final: false };
            if (api && typeof api.save === 'function') api.save(checkpoint);
            showMessage(format(labels.levelComplete, { level: level - 1 }), labels.continue, resetLevel);
          }
          updateHud();
        }

        function loseLife() {
          wall = null;
          lives--;
          if (lives <= 0) finishGame();
          updateHud();
        }

        function finishGame() {
          if (!running) return;
          running = false;
          paused = false;
          checkpoint = { level: level, score: score, final: true };
          if (!finalSaved && api && typeof api.save === 'function') {
            finalSaved = true;
            api.save(checkpoint);
          }
          showMessage(format(labels.gameOver, { score: score }), labels.newGame, function() {
            level = 1;
            score = 0;
            checkpoint = { level: 1, score: 0, final: false };
            if (writable && api && typeof api.save === 'function') api.save(checkpoint);
            resetLevel();
          });
        }

        function showMessage(message, button, callback) {
          running = false;
          overlayMessage.textContent = message;
          newGameButton.textContent = button;
          overlay.classList.add('visible');
          newGameButton.onclick = function() {
            overlay.classList.remove('visible');
            callback();
          };
        }

        function ballTouchesCells(ball, cells) {
          if (!cells) return false;
          const minX = Math.floor(ball.x - BALL_RADIUS);
          const maxX = Math.floor(ball.x + BALL_RADIUS);
          const minY = Math.floor(ball.y - BALL_RADIUS);
          const maxY = Math.floor(ball.y + BALL_RADIUS);
          for (let y = minY; y <= maxY; y++) {
            for (let x = minX; x <= maxX; x++) {
              if (!cells.has(id(x, y))) continue;
              const closestX = Math.max(x, Math.min(ball.x, x + 1));
              const closestY = Math.max(y, Math.min(ball.y, y + 1));
              if (Math.hypot(ball.x - closestX, ball.y - closestY) <= BALL_RADIUS) return true;
            }
          }
          return false;
        }

        function hitsBoard(x, y) {
          const minX = Math.floor(x - BALL_RADIUS);
          const maxX = Math.floor(x + BALL_RADIUS);
          const minY = Math.floor(y - BALL_RADIUS);
          const maxY = Math.floor(y + BALL_RADIUS);
          for (let cy = minY; cy <= maxY; cy++) {
            for (let cx = minX; cx <= maxX; cx++) {
              if (isOccupied(cx, cy)) return true;
            }
          }
          return false;
        }

        function updateBalls(dt) {
          for (const ball of balls) {
            let nextX = ball.x + ball.vx * dt;
            if (nextX - BALL_RADIUS < 0 || nextX + BALL_RADIUS > COLS || hitsBoard(nextX, ball.y)) {
              ball.vx *= -1;
              nextX = ball.x + ball.vx * dt;
            }
            ball.x = Math.max(BALL_RADIUS, Math.min(COLS - BALL_RADIUS, nextX));

            let nextY = ball.y + ball.vy * dt;
            if (nextY - BALL_RADIUS < 0 || nextY + BALL_RADIUS > ROWS || hitsBoard(ball.x, nextY)) {
              ball.vy *= -1;
              nextY = ball.y + ball.vy * dt;
            }
            ball.y = Math.max(BALL_RADIUS, Math.min(ROWS - BALL_RADIUS, nextY));
          }
        }

        function update(dt) {
          updateBalls(dt);
          if (wall) {
            wallClock += dt;
            while (wall && wallClock >= WALL_STEP) {
              wallClock -= WALL_STEP;
              extendEnd(wall.negative, -1);
              extendEnd(wall.positive, 1);
              if (balls.some(ball => ballTouchesCells(ball, activeCells()))) {
                loseLife();
                break;
              }
              if (wall && wall.negative.done && wall.positive.done) completeWall();
            }
          }
          remaining -= dt;
          if (remaining <= 0) finishGame();
        }

        function draw() {
          ctx.fillStyle = '#08090c';
          ctx.fillRect(0, 0, canvas.width, canvas.height);

          ctx.fillStyle = '#24384f';
          for (let y = 0; y < ROWS; y++) {
            for (let x = 0; x < COLS; x++) {
              if (occupied[id(x, y)]) ctx.fillRect(x * CELL, y * CELL, CELL, CELL);
            }
          }

          ctx.strokeStyle = 'rgba(255,255,255,.08)';
          ctx.lineWidth = 1;
          for (let x = 1; x < COLS; x++) {
            ctx.beginPath();
            ctx.moveTo(x * CELL, 0);
            ctx.lineTo(x * CELL, canvas.height);
            ctx.stroke();
          }
          for (let y = 1; y < ROWS; y++) {
            ctx.beginPath();
            ctx.moveTo(0, y * CELL);
            ctx.lineTo(canvas.width, y * CELL);
            ctx.stroke();
          }

          if (wall) {
            ctx.fillStyle = '#d7d7df';
            for (const cellId of wall.cells) {
              const x = cellId % COLS;
              const y = Math.floor(cellId / COLS);
              ctx.fillRect(x * CELL + 4, y * CELL + 4, CELL - 8, CELL - 8);
            }
          }

          for (const ball of balls) {
            const gradient = ctx.createRadialGradient(
              (ball.x - .12) * CELL, (ball.y - .12) * CELL, 1,
              ball.x * CELL, ball.y * CELL, BALL_RADIUS * CELL
            );
            gradient.addColorStop(0, '#f4d7ff');
            gradient.addColorStop(.35, '#b961d1');
            gradient.addColorStop(1, '#4d1766');
            ctx.fillStyle = gradient;
            ctx.beginPath();
            ctx.arc(ball.x * CELL, ball.y * CELL, BALL_RADIUS * CELL, 0, Math.PI * 2);
            ctx.fill();
          }

          if (keyboardMode && root.matches(':focus-visible')) {
            const x = keyboardCursor.x * CELL;
            const y = keyboardCursor.y * CELL;
            ctx.strokeStyle = '#ffd54f';
            ctx.lineWidth = 3;
            ctx.strokeRect(x + 2, y + 2, CELL - 4, CELL - 4);
          }
        }

        function loop(now) {
          if (!last) last = now;
          const dt = Math.min((now - last) / 1000, 0.05);
          last = now;
          if (running && !paused) update(dt);
          draw();
          updateHud();
          frame = requestAnimationFrame(loop);
        }

        function canvasPoint(event) {
          const rect = canvas.getBoundingClientRect();
          return {
            x: (event.clientX - rect.left) * COLS / rect.width,
            y: (event.clientY - rect.top) * ROWS / rect.height,
          };
        }

        function onPointerDown(event) {
          root.focus();
          keyboardMode = false;
          if (event.button === 2) {
            event.preventDefault();
            toggleOrientation();
            return;
          }
          const point = canvasPoint(event);
          startWall(point.x, point.y);
        }

        function onKeyDown(event) {
          if (event.target.closest('input, textarea, select, button, [contenteditable="true"]')) return;
          if (event.key === 'ArrowLeft' || event.key === 'ArrowRight' ||
              event.key === 'ArrowUp' || event.key === 'ArrowDown') {
            event.preventDefault();
            keyboardMode = true;
            if (event.key === 'ArrowLeft') keyboardCursor.x = Math.max(0, keyboardCursor.x - 1);
            if (event.key === 'ArrowRight') keyboardCursor.x = Math.min(COLS - 1, keyboardCursor.x + 1);
            if (event.key === 'ArrowUp') keyboardCursor.y = Math.max(0, keyboardCursor.y - 1);
            if (event.key === 'ArrowDown') keyboardCursor.y = Math.min(ROWS - 1, keyboardCursor.y + 1);
          } else if (event.key === 'Enter') {
            event.preventDefault();
            keyboardMode = true;
            startWall(keyboardCursor.x, keyboardCursor.y);
          } else if (event.code === 'Space') {
            event.preventDefault();
            toggleOrientation();
          } else if (event.key.toLowerCase() === 'p') {
            event.preventDefault();
            togglePause();
          }
        }

        function togglePause() {
          if (!running) return;
          paused = !paused;
          pauseButton.textContent = paused ? labels.resume : labels.pause;
        }

        function eject() {
          const saved = JSON.stringify(checkpoint).replace(/</g, '\\\\u003c');
          const source = '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">' +
            '<title>JezzBall</title></head><body><main class="jezzball-game"></main><scr' + 'ipt>(' +
            jezzballApp.toString() + ')(document.querySelector(".jezzball-game"),{initial:' + saved + '});</scr' + 'ipt></body></html>';
          const url = URL.createObjectURL(new Blob([source], { type: 'text/html;charset=utf-8' }));
          const link = document.createElement('a');
          link.href = url;
          link.download = 'jezzball.html';
          link.click();
          setTimeout(function() { URL.revokeObjectURL(url); }, 1000);
        }

        canvas.addEventListener('pointerdown', onPointerDown);
        canvas.addEventListener('contextmenu', function(event) { event.preventDefault(); });
        directionButton.addEventListener('click', toggleOrientation);
        pauseButton.addEventListener('click', togglePause);
        ejectButton.addEventListener('click', eject);
        root.addEventListener('keydown', onKeyDown);

        root._jezzballDestroy = function() {
          cancelAnimationFrame(frame);
          canvas.removeEventListener('pointerdown', onPointerDown);
          directionButton.removeEventListener('click', toggleOrientation);
          pauseButton.removeEventListener('click', togglePause);
          ejectButton.removeEventListener('click', eject);
          root.removeEventListener('keydown', onKeyDown);
          root._jezzballDestroy = null;
        };

        if (checkpoint.final) {
          placeBalls();
          showMessage(format(labels.finalScore, { score: score }), labels.newGame, function() {
            level = 1;
            score = 0;
            checkpoint = { level: 1, score: 0, final: false };
            if (writable && api && typeof api.save === 'function') api.save(checkpoint);
            resetLevel();
          });
        } else {
          resetLevel();
        }
        frame = requestAnimationFrame(loop);
        return root._jezzballDestroy;
      }

      Handlebars.registerHelper('jezzball', function(ref, actions, el) {
        return function() {
          const root = el && el.querySelector ? el.querySelector('.jezzball-game') : document.querySelector('.jezzball-game');
          let initial = {};
          try {
            initial = ref && ref.comment ? JSON.parse(ref.comment) : {};
          } catch (error) {
            initial = {};
          }
          jezzballApp(root, {
            initial: initial,
            writable: !actions || !!actions.comment,
            save: actions && actions.comment ? function(state) {
              actions.comment(JSON.stringify(state));
            } : undefined,
          });
        };
      });
    </script>
    `,
    // language=Handlebars
    ui: `
      <div class="jezzball-game">{{defer el (jezzball ref actions el)}}</div>
    `,
  },
};

export const jezzballTemplate: Template = {
  tag: 'plugin/jezzball',
  name: $localize`🟣️ JezzBall`,
  config: {
    mod: $localize`🟣️ JezzBall`,
    version: 1,
    type: 'plugin',
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    view: $localize`🟣️`,
    // language=CSS
    css: `
      app-ref-list.plugin_jezzball {
        .list-container {
          grid-auto-flow: row dense;
          padding: 4px;
          gap: 8px;
          grid-template-columns: minmax(0, 1fr);
          .list-number {
            display: none;
          }
          .ref {
            min-width: 0;
            break-inside: avoid;
            .toggle {
              display: none;
            }
          }
        }
      }
    `,
    advancedForm: [{
      key: 'defaultExpanded',
      type: 'boolean',
      defaultValue: true,
      props: {
        label: $localize`Default Expanded:`,
      },
    }],
  },
  defaults: <RootConfig> {
    defaultExpanded: true,
    submitText: true,
    defaultSort: ['modified,DESC'],
    defaultCols: 1,
  },
};

export const jezzballMod: Mod = {
  plugin: [
    jezzballPlugin,
  ],
  template: [
    jezzballTemplate,
  ],
};
