import { DateTime } from 'luxon';
import { Plugin } from '../../model/plugin';
import { Mod } from '../../model/tag';
import { Template } from '../../model/template';
import { RootConfig } from '../root';
import { scorePlugin } from './score';

const skiLabels = {
  name: $localize`⛷️ SkiFree`,
  description: $localize`Ski downhill, race through slalom gates, and perform freestyle jumps. Watch out for the yeti!`,
  free: $localize`Free ski`,
  slalom: $localize`Slalom`,
  freestyle: $localize`Freestyle`,
  start: $localize`Start skiing`,
  newGame: $localize`New game`,
  continue: $localize`Continue`,
  resume: $localize`Resume`,
  paused: $localize`Paused`,
  course: $localize`Course`,
  distance: $localize`Distance: {distance} m`,
  speed: $localize`Speed: {speed} km/h`,
  time: $localize`Time: {time} s`,
  score: $localize`Score: {score}`,
  missed: $localize`Missed gates: {missed} (+5 s each)`,
  complete: $localize`Course complete!`,
  caught: $localize`The yeti caught you!`,
  finished: $localize`Run finished`,
  warning: $localize`Yeti! Press F to outrun it!`,
  savedExample: $localize`Saved example`,
  savedExampleTitle: $localize`This Ref is read-only; progress will not be saved.`,
  help: $localize`Move the pointer to lead the skier; click or tap to jump. Keep the pointer near the bottom to ski downhill. Left/Right: steer · Down: downhill · Up: brake · Space: jump · F: fast · P/Escape: pause · End: finish run · Enter: start/continue. Jump from ramps and turn in the air for tricks. Courses finish at 1,000 m; the yeti appears at 2,000 m.`,
};
const skiLabelsSource = JSON.stringify(skiLabels).replace(/</g, '\\u003c');

export const skiFreePlugin: Plugin = {
  tag: 'plugin/skifree',
  name: skiLabels.name,
  config: {
    mod: skiLabels.name,
    version: 3,
    type: 'plugin',
    editingViewer: true,
    experimental: true,
    submitText: true,
    add: true,
    genId: true,
    export: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: skiLabels.description,
    icons: [{ label: $localize`⛷️`, order: 2 }],
    filters: [
      { query: 'plugin/skifree', label: skiLabels.name, title: skiLabels.name, group: $localize`Games 🕹️` },
    ],
    // language=Handlebars
    infoUi: `{{#if final}}<span class="skifree-final-score">🏆️ {{number (lookup ref.plugins "plugin/score")}}</span>{{/if}}`,
    // language=CSS
    css: `
      .skifree-game {
        display: block;
        width: min(100%, 800px);
        margin: auto;
        color: var(--text);
        font: 13px monospace;
      }
      .skifree-game * { box-sizing: border-box; }
      .skifree-overlay button, .skifree-course {
        padding: 8px 14px;
        border: 1px solid #555;
        border-radius: 0;
        background: #fff;
        color: #111;
        cursor: pointer;
        font: inherit;
      }
      .skifree-game :focus-visible { outline: 2px solid #1686ce; outline-offset: 2px; }
      .skifree-stage { position: relative; overflow: hidden; background: #fff; color: #111; }
      .skifree-hud {
        position: absolute;
        top: 12px;
        left: 12px;
        display: grid;
        gap: 3px;
        font-variant-numeric: tabular-nums;
        pointer-events: none;
        text-shadow: 1px 1px #fff, -1px -1px #fff;
      }
      .skifree-canvas { display: block; width: 100%; aspect-ratio: 6 / 5; touch-action: none; }
      .skifree-overlay {
        position: absolute;
        inset: 0;
        display: grid;
        place-content: center;
        gap: 12px;
        padding: 20px;
        text-align: center;
        background: rgba(255, 255, 255, .8);
        color: #111;
      }
      .skifree-game [hidden] { display: none; }
      .skifree-message { font-size: 26px; }
      .skifree-result { white-space: pre-line; }
      .skifree-example { display: block; padding: 4px; }
      .skifree-help { margin: 8px; font-size: 12px; line-height: 1.5; }
      .skifree-status { position: absolute; right: 12px; top: 12px; max-width: 45%; text-align: right; pointer-events: none; }
      :fullscreen .skifree-game { width: min(100%, calc((100vh - 90px) * 6 / 5)); }
      @media (max-width: 600px) {
        .skifree-hud, .skifree-status { font-size: 10px; }
      }
    `,
    // language=HTML
    snippet: `
    <script>
      function skiFreeApp(root, api) {
        if (!root) return function() {};
        if (root._skiFreeDestroy) root._skiFreeDestroy();
        api = api || {};
        const labels = ${skiLabelsSource};
        const initial = api.initial && typeof api.initial === 'object' ? api.initial : {};
        const writable = api.writable !== false;
        const canvas = root.querySelector('.skifree-canvas');
        const g = canvas.getContext('2d', { alpha: false });
        if (!g) return function() {};
        const find = name => root.querySelector('.skifree-' + name);
        const overlay = find('overlay');
        const course = find('course');
        const startButton = find('start');
        const W = 720, H = 600, ANCHOR = 180, COURSE_END = 4000, YETI_START = 8000;
        const modes = ['free', 'slalom', 'freestyle'];
        let mode = modes.includes(initial.mode) ? initial.mode : 'free';
        let state = 'ready';
        let player, camera, objects, tracks, yeti, distance, elapsed, points, missed, speed, angle;
        let jumpTime, jumpDuration, spin, crashTime, immunity, nextRow, nextGate, courseDone, fast;
        let frame = 0, last = 0, accumulator = 0, destroyed = false;
        let pointer = null, pointerId = null;
        const keys = new Set();
        const listeners = [];
        let overlayAction;

        function on(el, event, handler) {
          el.addEventListener(event, handler);
          listeners.push(() => el.removeEventListener(event, handler));
        }
        function format(label, values) {
          return label.replace(/\\{(\\w+)\\}/g, (match, key) =>
            Object.prototype.hasOwnProperty.call(values, key) ? values[key] : match);
        }
        function number(value) {
          return Number.isFinite(value) ? Math.max(0, Math.min(value, 1000000000)) : 0;
        }
        function clearInput() {
          keys.clear();
          pointer = null;
          if (pointerId !== null && canvas.hasPointerCapture(pointerId)) canvas.releasePointerCapture(pointerId);
          pointerId = null;
        }
        function message(title, action, callback, result) {
          find('message').textContent = title;
          find('result').textContent = result || '';
          startButton.textContent = action;
          overlayAction = callback;
          overlay.hidden = false;
          clearInput();
        }
        function resultText(result, score) {
          return [
            format(labels.distance, { distance: Math.floor(number(result.distance)) }),
            format(labels.time, { time: number(result.time).toFixed(1) }),
            format(labels.score, { score: Math.floor(number(score)) }),
            result.mode === 'slalom' ? format(labels.missed, { missed: Math.floor(number(result.missed)) }) : '',
          ].filter(Boolean).join('\\n');
        }
        function reset() {
          player = { x: 0, y: 0 };
          camera = { x: 0, y: 0 };
          objects = [];
          tracks = [];
          yeti = null;
          distance = elapsed = points = missed = speed = angle = 0;
          jumpTime = spin = crashTime = immunity = 0;
          jumpDuration = 1;
          nextRow = 350;
          nextGate = 500;
          courseDone = false;
          fast = false;
          clearInput();
          generate();
        }
        function start() {
          mode = course.value;
          reset();
          state = 'skiing';
          overlay.hidden = true;
          last = 0;
          accumulator = 0;
          root.focus({ preventScroll: true });
          hud();
        }
        function resume() {
          state = 'skiing';
          overlay.hidden = true;
          last = 0;
          accumulator = 0;
          root.focus({ preventScroll: true });
          hud();
        }
        function togglePause() {
          if (state === 'paused') return resume();
          if (state !== 'skiing') return;
          state = 'paused';
          message(labels.paused, labels.resume, resume);
          hud();
        }
        function score() {
          return mode === 'slalom' ?
            Math.max(0, Math.round(distance * 10 - (elapsed + missed * 5) * 20)) : Math.round(points);
        }
        function save(final) {
          const result = {
            mode: mode, distance: Math.floor(distance), time: Math.round((elapsed + missed * 5) * 10) / 10,
            missed: missed, final: final,
          };
          if (writable && typeof api.save === 'function') api.save(result, score());
          return resultText(result, score());
        }
        function finish(caught) {
          if (state !== 'skiing' && state !== 'paused') return;
          state = 'over';
          const result = save(true);
          message(caught ? labels.caught : labels.finished, labels.newGame, start, result);
          hud();
        }
        function toggleFast() {
          if (state !== 'skiing') return;
          fast = !fast;
          hud();
        }
        function jump(ramp) {
          if (state !== 'skiing' || crashTime > 0 || jumpTime > 0) return;
          jumpDuration = ramp ? 1.6 : .8;
          jumpTime = jumpDuration;
          spin = 0;
        }
        function height() {
          return jumpTime > 0 ? Math.sin(Math.PI * (1 - jumpTime / jumpDuration)) * (jumpDuration > 1 ? 65 : 30) : 0;
        }
        function generate() {
          while (nextRow < player.y + H + 200) {
            for (let i = 0; i < 5; i++) {
              const x = player.x + (Math.random() - .5) * W * 2.8;
              const roll = Math.random();
              const type = roll < .36 ? 'tree' : roll < .49 ? 'rock' : roll < .6 ? 'stump' :
                roll < .74 ? 'mogul' : roll < .85 ? 'ramp' : roll < .92 ? 'skier' : roll < .97 ? 'snowboarder' : 'dog';
              objects.push({ x: x, y: nextRow + Math.random() * 90, type: type, hit: false, phase: Math.random() * 6 });
            }
            nextRow += 125;
          }
          if (mode === 'slalom') {
            while (nextGate < Math.min(player.y + H + 200, COURSE_END)) {
              objects.push({ x: Math.sin(nextGate / 620) * 170, y: nextGate, type: 'gate', hit: false });
              nextGate += 350;
            }
          }
          objects = objects.filter(o => o.y > player.y - 260 && (o.type === 'gate' || Math.abs(o.x - player.x) < W * 3));
          tracks = tracks.filter(t => t.y > player.y - 250).slice(-160);
        }
        function crash() {
          crashTime = 1.3;
          speed = 0;
          jumpTime = 0;
          points = Math.max(0, points - 50);
        }
        function update(dt) {
          elapsed += dt;
          immunity = Math.max(0, immunity - dt);
          const previousY = player.y;
          if (crashTime > 0) {
            crashTime -= dt;
            if (crashTime <= 0) immunity = 1.2;
          } else {
            let turn = (keys.has('arrowright') ? 1 : 0) - (keys.has('arrowleft') ? 1 : 0);
            let pointerGap = Infinity;
            if (turn) {
              angle = Math.max(-Math.PI / 2, Math.min(Math.PI / 2, angle + turn * dt * 8));
              if (jumpTime > 0) spin += dt * 7;
            } else if (pointer) {
              const dx = pointer.x - (W / 2 + player.x - camera.x);
              const dy = pointer.y - (ANCHOR + player.y - camera.y);
              pointerGap = Math.hypot(dx, dy);
              const target = Math.atan2(dx, dy);
              const difference = Math.atan2(Math.sin(target - angle), Math.cos(target - angle));
              if (pointerGap > 3) angle += difference * Math.min(1, dt * 10);
              if (jumpTime > 0) spin += Math.abs(difference) * dt * 3;
            }
            if (keys.has('arrowdown')) angle *= Math.max(0, 1 - dt * 8);
            const braking = keys.has('arrowup') || pointerGap < 4;
            const targetSpeed = braking ? 0 :
              Math.min((fast ? 470 : 205) * Math.max(.2, Math.cos(angle)), pointerGap * 3);
            speed += (targetSpeed - speed) * Math.min(1, dt * (braking ? 10 : 2));
            player.x += Math.sin(angle) * speed * dt;
            player.y += Math.cos(angle) * speed * dt;
            camera.x = Math.max(player.x - W * .35, Math.min(player.x + W * .35, camera.x));
            camera.y = Math.max(player.y + ANCHOR - H * .55, Math.min(player.y + ANCHOR - 80, camera.y));
            distance = Math.max(distance, player.y / 4);
            if (jumpTime > 0) {
              jumpTime = Math.max(0, jumpTime - dt);
              if (!jumpTime) points += Math.round(jumpDuration * 60 + Math.floor(spin / Math.PI) * 100);
            } else if (Math.floor(elapsed * 20) !== Math.floor((elapsed - dt) * 20)) {
              tracks.push({ x: player.x, y: player.y, angle: angle });
            }
          }
          generate();
          for (const o of objects) {
            if (o.type === 'skier' || o.type === 'snowboarder') {
              o.x += Math.sin(elapsed * 1.5 + o.phase) * dt * 50;
              o.y += dt * (o.type === 'skier' ? 65 : 90);
            }
            if (o.type === 'dog') o.x += Math.cos(o.phase) * dt * 70;
            if (o.type === 'gate') {
              if (!o.hit && previousY < o.y && player.y >= o.y) {
                o.hit = true;
                o.passed = Math.abs(player.x - o.x) < 65;
                if (!o.passed) missed++;
              }
              continue;
            }
            if (o.hit || crashTime > 0 || immunity > 0 || Math.abs(o.y - player.y) > 13 ||
                Math.abs(o.x - player.x) > (o.type === 'tree' ? 19 : 15)) continue;
            if (o.type === 'ramp' || o.type === 'mogul') {
              if (!jumpTime && speed > 70) jump(o.type === 'ramp');
            } else if (height() < (o.type === 'tree' ? 48 : 15)) {
              o.hit = true;
              crash();
            }
          }
          if (!courseDone && mode !== 'free' && player.y >= COURSE_END) {
            courseDone = true;
            state = 'course-complete';
            const result = save(false);
            message(labels.complete, labels.continue, resume, result);
          }
          if (!yeti && player.y >= YETI_START) {
            yeti = { x: player.x + 180, y: player.y - 230, eating: 0 };
          }
          if (yeti) {
            const dx = player.x - yeti.x, dy = player.y - yeti.y;
            const gap = Math.hypot(dx, dy);
            const step = Math.min(gap, 265 * dt);
            yeti.x += dx / (gap || 1) * step;
            yeti.y += dy / (gap || 1) * step;
            if (gap < 20 && state === 'skiing') {
              yeti.eating = 1;
              finish(true);
            }
          }
        }
        function hud() {
          find('distance').textContent = format(labels.distance, { distance: Math.floor(distance) });
          find('time').textContent = format(labels.time, { time: (elapsed + missed * 5).toFixed(1) });
          find('score').textContent = format(labels.score, { score: score() });
          find('speed').textContent = format(labels.speed, { speed: Math.round(speed * .9) });
          find('status').textContent = yeti && state === 'skiing' ? labels.warning :
            mode === 'slalom' ? format(labels.missed, { missed: missed }) : '';
          course.disabled = !['ready', 'over'].includes(state);
          course.hidden = course.disabled;
          root.dataset.state = state;
          root.dataset.distance = String(Math.floor(distance));
          root.dataset.fast = String(fast);
        }
        function line(color, width, points) {
          g.strokeStyle = color;
          g.lineWidth = width;
          g.beginPath();
          points.forEach((p, i) => i ? g.lineTo(p[0], p[1]) : g.moveTo(p[0], p[1]));
          g.stroke();
        }
        function polygon(color, points) {
          g.fillStyle = color;
          g.beginPath();
          points.forEach((p, i) => i ? g.lineTo(p[0], p[1]) : g.moveTo(p[0], p[1]));
          g.closePath();
          g.fill();
        }
        function ellipse(color, x, y, rx, ry) {
          g.fillStyle = color;
          g.beginPath();
          g.ellipse(x, y, rx, ry, 0, 0, Math.PI * 2);
          g.fill();
        }
        function skier(x, y, heading, color, air, fallen) {
          g.save();
          g.translate(Math.round(x), Math.round(y));
          ellipse('#dbe2eb', 0, 4, 15, 4);
          g.translate(0, -air);
          if (fallen) {
            line('#222', 3, [[-18, 2], [18, -8]]);
            line('#d22947', 3, [[-14, -10], [14, 9]]);
            ellipse(color, 0, -5, 9, 5);
            ellipse('#f0b487', 10, -8, 5, 5);
          } else {
            g.rotate(-heading * .65 + (air ? Math.sin(spin) * .4 : 0));
            line('#343d50', 3, [[-6, -6], [-6, 15], [-3, 18]]);
            line('#343d50', 3, [[6, -6], [6, 15], [9, 18]]);
            line('#614b85', 4, [[-5, 4], [-4, -8], [4, -8], [6, 4]]);
            polygon(color, [[-7, -21], [6, -21], [8, -7], [-6, -7]]);
            line(color, 4, [[-5, -19], [-13, -9], [-16, -12]]);
            line(color, 4, [[5, -19], [13, -10], [16, -14]]);
            line('#777', 1, [[-16, -12], [-20, 8]]);
            line('#777', 1, [[16, -14], [20, 6]]);
            ellipse('#f0b487', 0, -26, 5, 6);
            g.fillStyle = '#e4314d';
            g.fillRect(-6, -32, 12, 4);
            g.fillStyle = '#222';
            g.fillRect(1, -27, 5, 2);
          }
          g.restore();
        }
        function drawObject(o) {
          const x = Math.round(W / 2 + o.x - camera.x), y = Math.round(ANCHOR + o.y - camera.y);
          if (x < -100 || x > W + 100 || y < -80 || y > H + 80) return;
          g.save();
          g.translate(x, y);
          if (o.type === 'tree') {
            ellipse('#dbe2eb', 9, 4, 22, 5);
            g.fillStyle = '#805231'; g.fillRect(-3, -12, 7, 17);
            polygon('#134a36', [[0, -66], [-15, -37], [-8, -38], [-23, -14], [-14, -16], [-28, 0], [28, 0], [14, -16], [23, -14], [8, -38], [15, -37]]);
            polygon('#238855', [[0, -62], [-12, -38], [-3, -41], [-18, -17], [-3, -21], [-21, -3], [1, -9]]);
            line('#f6fbff', 3, [[-10, -36], [0, -41], [10, -36]]);
          } else if (o.type === 'rock') {
            polygon('#767e8b', [[-17, 0], [-12, -12], [1, -18], [14, -9], [19, 1]]);
            polygon('#c7cfdb', [[-12, -12], [1, -18], [12, -10], [0, -9], [-5, -4]]);
          } else if (o.type === 'stump') {
            g.fillStyle = '#805231'; g.fillRect(-10, -13, 20, 14);
            ellipse('#bc9368', 0, -13, 11, 4);
            line('#684b36', 1, [[-3, -15], [5, -12], [-5, -11]]);
          } else if (o.type === 'ramp') {
            polygon('#b9d8f4', [[-24, 7], [-20, -8], [20, -8], [24, 7]]);
            line('#508fb7', 2, [[-20, -8], [20, -8]]);
            line('#fff', 3, [[-16, -3], [16, -3]]);
          } else if (o.type === 'mogul') {
            ellipse('#c9dbea', 0, 0, 18, 5);
            ellipse('#fff', -2, -3, 17, 5);
          } else if (o.type === 'gate') {
            const color = o.hit ? (o.passed ? '#238855' : '#999') : '#d22c49';
            line(color, 2, [[-65, 1], [-65, -33]]);
            line(color, 2, [[65, 1], [65, -33]]);
            polygon(color, [[-65, -33], [-42, -29], [-65, -22]]);
            polygon(color, [[65, -33], [88, -29], [65, -22]]);
          } else if (o.type === 'dog') {
            ellipse('#a77c51', 0, -6, 10, 5);
            ellipse('#795435', 11, -11, 5, 5);
            const leg = Math.sin(elapsed * 16 + o.phase) * 4;
            line('#795435', 2, [[-7, -5], [-7 + leg, 2]]);
            line('#795435', 2, [[7, -5], [7 - leg, 2]]);
            line('#795435', 2, [[-9, -7], [-16, -13]]);
          } else {
            if (o.type === 'snowboarder') {
              line('#f79028', 6, [[-16, 7], [16, 1]]);
            }
            skier(0, 0, Math.sin(elapsed * 1.5 + o.phase), o.type === 'skier' ? '#f0c327' : '#914dab', 0, o.hit);
          }
          g.restore();
        }
        function drawYeti() {
          if (!yeti) return;
          const x = W / 2 + yeti.x - camera.x, y = ANCHOR + yeti.y - camera.y;
          const stride = Math.sin(elapsed * 15) * 9;
          g.save();
          g.translate(x, y);
          ellipse('#c9d7e4', 0, 8, 23, 6);
          line('#485671', 13, [[-10, -20], [-14 - stride, 4]]);
          line('#485671', 13, [[10, -20], [14 + stride, 4]]);
          line('#f7fafc', 9, [[-10, -20], [-14 - stride, 3]]);
          line('#f7fafc', 9, [[10, -20], [14 + stride, 3]]);
          ellipse('#485671', 0, -32, 23, 28);
          ellipse('#f7fafc', 0, -33, 21, 27);
          line('#485671', 10, [[-18, -43], [-30, -20 + stride]]);
          line('#485671', 10, [[18, -43], [30, -20 - stride]]);
          line('#f7fafc', 7, [[-18, -43], [-30, -20 + stride]]);
          line('#f7fafc', 7, [[18, -43], [30, -20 - stride]]);
          ellipse('#f7fafc', 0, -59, 16, 15);
          g.fillStyle = '#273951';
          g.fillRect(-9, -63, 5, 4); g.fillRect(4, -63, 5, 4);
          ellipse('#273951', 0, -51, 9, yeti.eating ? 9 : 4);
          g.fillStyle = '#fff';
          g.fillRect(-6, -55, 4, 5); g.fillRect(2, -55, 4, 5);
          g.restore();
        }
        function draw() {
          g.fillStyle = '#fff';
          g.fillRect(0, 0, W, H);
          for (const t of tracks) {
            const x = W / 2 + t.x - camera.x, y = ANCHOR + t.y - camera.y;
            for (const offset of [-5, 5]) {
              line('#d8e2ec', 1, [[x + offset, y], [x + offset - Math.sin(t.angle) * 8, y - Math.cos(t.angle) * 8]]);
            }
          }
          if (mode !== 'free') {
            const y = ANCHOR + COURSE_END - camera.y;
            if (y > -40 && y < H + 40) {
              for (let x = 0; x < W; x += 16) {
                g.fillStyle = x % 32 ? '#fff' : '#333';
                g.fillRect(x, y, 16, 8);
                g.fillStyle = x % 32 ? '#333' : '#fff';
                g.fillRect(x, y + 8, 16, 8);
              }
            }
          }
          const sorted = objects.slice().sort((a, b) => a.y - b.y);
          for (const o of sorted) if (o.y <= player.y) drawObject(o);
          if (immunity <= 0 || Math.floor(elapsed * 10) % 2) {
            skier(W / 2 + player.x - camera.x, ANCHOR + player.y - camera.y, angle, '#197dcb', height(), crashTime > 0);
          }
          for (const o of sorted) if (o.y > player.y) drawObject(o);
          drawYeti();
        }
        function loop(now) {
          if (destroyed) return;
          if (!root.isConnected) { root._skiFreeDestroy(); return; }
          if (state === 'skiing') {
            accumulator += last ? Math.min((now - last) / 1000, .1) : 0;
            while (accumulator >= 1 / 120 && state === 'skiing') {
              update(1 / 120);
              accumulator -= 1 / 120;
            }
          }
          last = now;
          draw();
          hud();
          frame = requestAnimationFrame(loop);
        }
        function keyDown(event) {
          if (event.target.closest('button, select, input, textarea') || event.ctrlKey || event.metaKey || event.altKey) return;
          const key = event.key.toLowerCase();
          if (!['arrowleft', 'arrowright', 'arrowup', 'arrowdown', ' ', 'f', 'p', 'escape', 'end', 'enter'].includes(key)) return;
          event.preventDefault();
          pointer = null;
          if (key.startsWith('arrow')) keys.add(key);
          if (event.repeat) return;
          if (key === 'p' || key === 'escape') togglePause();
          if (key === 'end') {
            if (state === 'course-complete') state = 'paused';
            finish(false);
          }
          if (key === 'f') toggleFast();
          if (key === ' ') jump(false);
          if (key === 'enter' && !overlay.hidden) overlayAction();
        }
        function point(event) {
          const rect = canvas.getBoundingClientRect();
          pointer = { x: (event.clientX - rect.left) * W / rect.width, y: (event.clientY - rect.top) * H / rect.height };
        }

        root.setAttribute('aria-label', labels.name);
        find('help').textContent = labels.help;
        find('example').textContent = labels.savedExample;
        find('example').title = labels.savedExampleTitle;
        find('example').hidden = writable;
        course.setAttribute('aria-label', labels.course);
        for (const option of course.options) option.textContent = labels[option.value];
        course.value = mode;
        on(startButton, 'click', () => overlayAction());
        on(root, 'keydown', keyDown);
        on(root, 'keyup', event => keys.delete(event.key.toLowerCase()));
        on(canvas, 'pointerdown', event => {
          if (event.button !== 0 || state !== 'skiing' || pointerId !== null) return;
          event.preventDefault();
          root.focus({ preventScroll: true });
          pointerId = event.pointerId;
          canvas.setPointerCapture(pointerId);
          point(event);
          jump(false);
        });
        on(canvas, 'pointermove', event => {
          if (state === 'skiing' && (event.pointerType === 'mouse' || event.pointerId === pointerId)) point(event);
        });
        const release = () => { pointerId = null; };
        on(canvas, 'pointerup', release);
        on(canvas, 'pointercancel', () => { release(); pointer = null; });
        on(canvas, 'lostpointercapture', release);
        on(canvas, 'pointerleave', event => { if (event.pointerType === 'mouse' && pointerId === null) pointer = null; });
        on(window, 'blur', () => { clearInput(); if (state === 'skiing') togglePause(); });
        on(document, 'visibilitychange', () => { if (document.hidden && state === 'skiing') togglePause(); });
        on(root, 'focusout', event => {
          if (!root.contains(event.relatedTarget)) { clearInput(); if (state === 'skiing') togglePause(); }
        });
        root._skiFreeDestroy = function() {
          if (destroyed) return;
          destroyed = true;
          cancelAnimationFrame(frame);
          clearInput();
          listeners.forEach(remove => remove());
          root._skiFreeDestroy = null;
        };
        reset();
        if (initial.final || number(initial.distance)) {
          state = 'over';
          message(labels.finished, labels.newGame, start, resultText(initial, api.score));
        } else {
          message(labels.name, labels.start, start);
        }
        draw();
        hud();
        frame = requestAnimationFrame(loop);
        return root._skiFreeDestroy;
      }
      Handlebars.registerHelper('skifree', function(ref, actions, el) {
        return function() {
          skiFreeApp(el.querySelector('.skifree-game'), {
            initial: ref && ref.plugins && ref.plugins['plugin/skifree'],
            score: ref && ref.plugins && ref.plugins['plugin/score'],
            writable: !actions || !!actions.patch,
            save: actions && actions.patch ? function(state, score) {
              actions.patch({ plugins: { 'plugin/skifree': state, 'plugin/score': score } });
            } : undefined,
          });
        };
      });
    </script>
    `,
    // language=Handlebars
    ui: `
      <div class="skifree-game" tabindex="0">
        <div class="skifree-stage">
          <canvas class="skifree-canvas" width="720" height="600"></canvas>
          <div class="skifree-hud">
            <span class="skifree-distance"></span><span class="skifree-speed"></span>
            <span class="skifree-time"></span><span class="skifree-score"></span>
          </div>
          <div class="skifree-status" role="status"></div>
          <div class="skifree-overlay">
            <strong class="skifree-message"></strong>
            <span class="skifree-result"></span>
            <select class="skifree-course"><option value="free"></option><option value="slalom"></option><option value="freestyle"></option></select>
            <button class="skifree-start" type="button"></button>
          </div>
        </div>
        <span class="skifree-example"></span>
        <p class="skifree-help"></p>
        {{defer el (skifree ref actions el)}}
      </div>
    `,
  },
  defaults: { mode: 'free' },
  schema: {
    optionalProperties: {
      mode: { enum: ['free', 'slalom', 'freestyle'] },
      distance: { type: 'float64' },
      time: { type: 'float64' },
      missed: { type: 'uint32' },
      final: { type: 'boolean' },
    },
  },
};

export const skiFreeTemplate: Template = {
  tag: 'plugin/skifree',
  name: skiLabels.name,
  config: {
    mod: skiLabels.name,
    version: 1,
    type: 'plugin',
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    view: $localize`⛷️`,
    // language=CSS
    css: `
      app-ref-list.plugin_skifree .list-container {
        grid-template-columns: minmax(0, 1fr);
        gap: 8px;
        .list-number, .ref .toggle { display: none; }
        .ref { min-width: 0; }
      }
    `,
    advancedForm: [{
      key: 'defaultExpanded',
      type: 'boolean',
      defaultValue: true,
      props: { label: $localize`Default Expanded:` },
    }],
  },
  defaults: <RootConfig> {
    submitText: true,
    defaultSort: ['plugins->plugin/score:num,DESC', 'modified,DESC'],
    defaultCols: 1,
  },
};

export const skiFreeMod: Mod = {
  plugin: [scorePlugin, skiFreePlugin],
  template: [skiFreeTemplate],
};
