import { DateTime } from 'luxon';
import { Mod } from '../../model/tag';

export const hideMod: Mod = {
  plugin: [{
    tag: 'plugin/user/hide',
    name: $localize`🙈️️ Hide Refs`,
    config: {
      generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
      description: $localize`Mark Refs as hidden for the current user`,
      icons: [{ response: 'plugin/user/hide', label: $localize`🙈️️`, global: true, order: -1 }],
      filters: [
        { user: 'plugin/user/hide', label: $localize`🙈️️ hidden`, title: $localize`My hidden Refs`, group: $localize`Filters 🕵️️` },
      ],
      actions: [{ response: 'plugin/user/hide', labelOff: $localize`hide`, labelOn: $localize`unhide`, global: true }],
    },
  }],
};
