import { DateTime } from 'luxon';
import { Ext } from '../../model/ext';
import { Mod } from '../../model/tag';
import { Template } from '../../model/template';

export const notesTemplate: Template = {
  tag: 'notes',
  name: $localize` Notebook`,
  config: {
    type: 'lens',
    mod: $localize`✍️ Notes`,
    experimental: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    view: $localize`📓️`,
    description: $localize`Keep private notes in a notebook.`,
    icons: [
      { label: $localize`✍️` },
    ],
    filters: [
      { query: 'notes', label: $localize`✍️ notes`, title: $localize`Notes`, group: $localize`Templates 🎨️` },
    ],
    overrideForm: true,
    form: [{
      key: 'defaultCols',
      type: 'select',
      props: {
        label: $localize`Columns:`,
        options: [
          { label: $localize`Default` },
          { value: 1, label: $localize`1 Column` },
          { value: 2, label: $localize`2 Columns` },
          { value: 3, label: $localize`3 Columns` },
          { value: 4, label: $localize`4 Columns` },
          { value: 5, label: $localize`5 Columns` },
          { value: 6, label: $localize`6 Columns` },
        ],
      },
    }, {
      key: 'badges',
      className: 'badges',
      type: 'tags',
      props: {
        label: $localize`Badges:`,
        addText: $localize`+ Add another badge tag`,
      }
    }, {
      key: 'queryFilters',
      type: 'list',
      props: {
        label: $localize`Query Filters:`,
        addText: $localize`+ Add another query filter`,
      },
      fieldArray: {
        fieldGroup: [{
          key: 'label',
          type: 'string',
          props: {
            label: $localize`Label:`
          }
        }, {
          key: 'query',
          type: 'query',
          props: {
            required: true,
          }
        }]
      }
    }],
    advancedForm: [],
  },
  defaults: {
    defaultCols: 0, // Leave to CSS screen size detection, but show cols dropdown
    badges: ['reminder', 'important'],
    queryFilters: [
      { query: 'reminder', label: $localize`🎗️ Reminder` },
      { query: 'important', label: $localize`‼️ Important` },
    ],
    defaultSort: ['modified'],
    addTags: [],
  },
  schema: {
    optionalProperties: {
      badges: { elements: { type: 'string' } },
    },
  }
};

export const reminderExt: Ext = {
  tag: 'reminder',
  name: $localize`🎗️`
}

export const importantExt: Ext = {
  tag: 'reminder',
  name: $localize`‼️`
}

export const notesMod: Mod = {
  template: [
    notesTemplate,
  ],
  ext: [
    reminderExt,
    importantExt,
  ]
};
