import { DateTime } from 'luxon';
import { Mod } from '../../model/tag';

export const readMod: Mod = {
  plugin: [{
    tag: 'plugin/user/read',
    name: $localize`☑️ Mark as read`,
    config: {
      version: 3,
      generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
      description: $localize`Mark Refs as read for the current user across multiple sessions`,
      filters: [
        { user: '!plugin/user/read', label: $localize`☑️ unread`, title: $localize`You read it`, group: $localize`Lists ☰` },
      ],
      advancedActions: [{ response: 'plugin/user/read', labelOff: $localize`read`, labelOn: $localize`unread`, global: true }],
      // language=CSS
      css: `
        .ref.user-response-plugin_user_read > .row > .stack > .link {
          a, .fake-link {
            color: var(--visited);
          }
        }
      `
    },
  }],
};
