import * as moment from 'moment';
import { Template } from '../model/template';

export const blogTemplate: Template = {
  tag: 'blog',
  name: 'Blog Ext Template',
  config: {
    generated: 'Generated by jenkins-ui ' + moment().toISOString(),
  },
  schema: {
    optionalProperties: {
      filterTags: { type: 'boolean' },
      tags: { elements: { type: 'string' } },
    },
  },
};
