import * as moment from 'moment';
import { Template } from '../model/template';

export const dmTemplate: Template = {
  tag: 'dm',
  name: $localize`✉️ DM`,
  config: {
    default: true,
    internal: true,
    generated: 'Generated by jenkins-ui ' + moment().toISOString(),
    description: $localize`Adds dms tab to inbox. Adds buttons to create private direct messages with users.`,
    filters: [
      { query: 'dm', label: $localize`✉️ dm`, group: $localize`Templates 🎨️` },
    ],
  },
};
