import * as moment from 'moment';
import { Template } from '../model/template';

export const kanbanTemplate: Template = {
  tag: 'kanban',
  name: 'Kanban Board Ext Template',
  config: {
    generated: 'Generated by jenkins-ui ' + moment().toISOString(),
  },
  defaults: {
    columns: []
  },
  schema: {
    properties: {
      columns: { elements: { type: 'string' } },
    },
    optionalProperties: {
      swimLanes: { elements: { type: 'string' } },
      showNoColumn: { type: 'boolean'},
      noColumnTitle: { type: 'string'},
      showNoSwimLane: { type: 'boolean'},
      noSwimLaneTitle: { type: 'string'},
    },
  },
};
