import * as moment from 'moment';
import { Template } from '../model/template';

export const queueTemplate: Template = {
  tag: 'queue',
  name: $localize`🚧️ Work Queue`,
  config: {
    experimental: true,
    generated: 'Generated by jenkins-ui ' + moment().toISOString(),
    submit: $localize`🚧️ queue`,
    description: $localize`Activates built-in Work Queue mode for managing workflows and invoices.`,
    filters: [
      { query: 'queue', label: $localize`🚧️ queue`, group: $localize`Templates 🎨️` },
    ],
  },
  defaults: {
    icons: [
      { label: $localize`✔️`, tag: 'qc/pass', title: $localize`QC Passed`, global: true, order: -1 },
    ],
    actions: [
      { tag: 'qc/pass', labelOff: $localize`approve`, global: true, order: -1 },
      { reply: 'plugin/invoice', labelOff: $localize`invoice`, global: true, order: -1 }
    ],
    filters: [
      { query: '!qc/pass', label: $localize`🕵️ qc`, group: $localize`Editor Tools` },
    ],
  },
  schema: {
    optionalProperties: {
      approvers: { elements: { type: 'string' } },
      bounty: { type: 'string' },
      maxAge: { type: 'string' },
    },
  },
};
