import * as moment from 'moment';
import { Template } from '../model/template';

export const readerTemplate: Template = {
  tag: 'reader',
  name: $localize`📰️ Reader`,
  config: {
    experimental: true,
    generated: 'Generated by jenkins-ui ' + moment().toISOString(),
    submit: $localize`📰️ reader`,
    view: $localize`📰️`,
    filters: [
      { query: 'reader', label: $localize`📰️ reader`, group: $localize`Templates 🎨️` },
    ],
  },
  schema: {
    optionalProperties: {
      categories: { elements: { type: 'string' } },
    },
  },
};
