import * as moment from 'moment';
import { Template } from '../model/template';

export const rootTemplate: Template = {
  tag: '',
  name: 'Default Ext Template',
  config: {
    generated: 'Generated by jenkins-ui ' + moment().toISOString(),
  },
  defaults: {
    pinned: [],
  },
  schema: {
    properties: {
      pinned: { elements: { type: 'string' } },
    },
    optionalProperties: {
      sidebar: { type: 'string' },
      themes: { values: { type: 'string' } },
      theme: { type: 'string' },
    },
  },
};
