import * as moment from 'moment';
import { Template } from '../model/template';

export const defaultSubs = ['+meta', 'science', 'politics', 'history', 'news', 'funny'];

export const userTemplate: Template = {
  tag: 'user',
  name: $localize`User`,
  config: {
    default: true,
    generated: 'Generated by jenkins-ui ' + moment().toISOString(),
  },
  defaults: {
    subscriptions: defaultSubs,
  },
  schema: {
    optionalProperties: {
      lastNotified: { type: 'string' },
      subscriptions: { elements: { type: 'string' } },
      alarms: { elements: { type: 'string' } },
      bookmarks: { elements: { type: 'string' } },
      editors: { elements: { type: 'string' } },
      userThemes: { values: { type: 'string' } },
      userTheme: { type: "string" },
    }
  },
};
