import { DateTime } from 'luxon';
import { Plugin } from '../../model/plugin';
import { Mod } from '../../model/tag';

export const emailPlugin: Plugin = {
  tag: 'plugin/email',
  name: $localize`📧️ Email`,
  config: {
    type: 'plugin',
    default: true,
    add: true,
    reply: ['internal', 'plugin/email'],
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Render e-mail specific formatting.`,
    icons: [
      { label: $localize`📧️` },
    ],
    filters: [
      { query: 'plugin/email', label: $localize`📧️ email`, title: $localize`Emails`, group: $localize`Plugins 🧰️` },
    ],
  },
};

export const emailMod: Mod = {
  plugin: [
    emailPlugin,
  ]
};
