import { DateTime } from 'luxon';
import { Plugin } from '../../model/plugin';
import { Ref } from '../../model/ref';
import { Mod } from '../../model/tag';
import { hasTag } from '../../util/tag';

export const originPlugin: Plugin = {
  tag: '+plugin/origin',
  name: $localize`🏛️ Remote Origin`,
  config: {
    mod: $localize`🏛️ Origin`,
    version: 1,
    default: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    submit: $localize`🏛️ origin`,
    settings: $localize`origin`,
    icons: [{ label: $localize`🏛️`, order: 3 }],
    description: $localize`Replicate a remote Jasper instance. The remote
     origin will be scraped on an interval you specify.
     If the remote is also set up to replicate from this instance, you may
     communicate with remote users.
     You may configure if metadata is generated or plugins are validated. `,
    sorts: [
      { sort: 'origin', label: $localize`🏛️ origin` },
      { sort: 'origin:len', label: $localize`🪆 nesting` },
    ],
    form: [{
      key: 'local',
      type: 'origin',
      props: {
        label: $localize`Local:`
      }
    }, {
      key: 'remote',
      type: 'origin',
      props: {
        label: $localize`Remote:`
      }
    }],
    advancedForm: [{
      key: 'proxy',
      type: 'url',
      props: {
        label: $localize`Proxy:`,
        title: $localize`Fetch all resources directly from the origin, not the internet`,
      }
    }],
  },
  schema: {
    optionalProperties: {
      local: { type: 'string' },
      remote: { type: 'string' },
      proxy: { type: 'string' },
    },
  },
};

export const originPullPlugin: Plugin = {
  tag: '+plugin/origin/pull',
  name: $localize`🏛️📥️ Remote Origin Pull`,
  config: {
    mod: $localize`🏛️ Origin`,
    version: 1,
    default: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    submitChild: $localize`📥️ pull`,
    description: $localize`Replicate a remote Jasper instance. The remote
      origin will be scraped on an interval you specify.
      If the remote is also set up to replicate from this instance, you may
      communicate with remote users.
      You may configure if metadata is generated or plugins are validated. `,
    icons: [
      { label: $localize`📥️` },
      { tag: '-+plugin/cron', label: $localize`🚫️`, title: $localize`Pulling disabled`, order: -1 },
      { tag: '+plugin/cron', condition: 'websocket', label: $localize`📶️`, title: $localize`Streaming updates`, order: -1 },
    ],
    actions: [
      { tag: '+plugin/cron', labelOn: $localize`disable`, labelOff: $localize`enable` },
      { response: '+plugin/user/run', labelOn: $localize`cancel`, title: $localize`Cancel pulling.` },
    ],
    advancedActions: [
      { response: '+plugin/user/run', labelOff: $localize`pull`, title: $localize`Pull a batch of updates from the remote.`, confirm: $localize`Are you sure you want to pull?` },
    ],
    // language=Handlebars
    infoUi: `
      {{#if (interestingTags addTags)}} tagging refs {{/if}}
      {{#each (interestingTags addTags)}}
        #{{.}}
      {{/each}}`,
    form: [{
      key: 'query',
      type: 'query'
    }, {
      key: 'addTags',
      type: 'tags',
      props: {
        label: $localize`Add Tags:`,
      },
    }, {
      key: 'websocket',
      type: 'boolean',
      defaultValue: true,
      props: {
        label: $localize`Stream Updates:`,
      },
    }, {
      key: 'cacheProxy',
      type: 'boolean',
      props: {
        label: $localize`Proxy:`,
      },
    }, {
      key: 'cacheProxyPrefetch',
      type: 'boolean',
      props: {
        label: $localize`Prefetch Proxy:`,
      },
      expressions: {
        hide: '!model.cacheProxy',
      },
    }],
    advancedForm: [{
      key: 'cachePrefetch',
      type: 'boolean',
      props: {
        label: $localize`Prefetch Files:`,
      },
    }, {
      key: 'removeTags',
      type: 'tags',
      props: {
        label: $localize`Remove Tags:`,
        addText: $localize`+ Remove another tag`,
      },
    }, {
      key: 'batchSize',
      type: 'integer',
      defaultValue: 250,
      props: {
        label: $localize`Batch Size:`,
      },
    }, {
      key: 'validatePlugins',
      type: 'boolean',
      props: {
        label: $localize`Validate Plugins:`,
      },
    }, {
      key: 'stripInvalidPlugins',
      type: 'boolean',
      props: {
        label: $localize`Strip Invalid Plugins:`,
      },
      expressions: {
        hide: '!model.validatePlugins',
      },
    }, {
      key: 'validateTemplates',
      type: 'boolean',
      props: {
        label: $localize`Validate Templates:`,
      },
    }, {
      key: 'stripInvalidTemplates',
      type: 'boolean',
      props: {
        label: $localize`Strip Invalid Templates:`,
      },
      expressions: {
        hide: '!model.validateTemplates',
      },
    }],
  },
  defaults: {
    cachePrefetch: true,
    websocket: true,
  },
  schema: {
    optionalProperties: {
      cachePrefetch: { type: 'boolean' },
      cacheProxy: { type: 'boolean' },
      cacheProxyPrefetch: { type: 'boolean' },
      websocket: { type: 'boolean' },
      query: { type: 'string' },
      batchSize: { type: 'int32' },
      validatePlugins: { type: 'boolean' },
      stripInvalidPlugins: { type: 'boolean' },
      validateTemplates: { type: 'boolean' },
      stripInvalidTemplates: { type: 'boolean' },
      originFromTag: { type: 'string' },
      addTags: { elements: { type: 'string' } },
      removeTags: { elements: { type: 'string' } },
    },
  },
};

export const originPushPlugin: Plugin = {
  tag: '+plugin/origin/push',
  name: $localize`🏛️📤️ Remote Origin Push`,
  config: {
    mod: $localize`🏛️ Origin`,
    version: 1,
    default: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    submitChild: $localize`📤️ push`,
    description: $localize`Push modifications to a remote origin.
      On the scheduled interval set, the server will check if the remote cursor is
      behind the local cursor. If "Push on change" is set changes are pushed immediately.`,
    icons: [
      { label: $localize`📤️` },
      { tag: '-+plugin/cron', label: $localize`🚫️`, title: $localize`Pushing disabled`, order: -1 },
      { tag: '+plugin/cron', condition: 'pushOnChange', label: $localize`📶️`, title: $localize`Pushing on change`, order: -1 },
    ],
    actions: [
      { tag: '+plugin/cron', labelOn: $localize`disable`, labelOff: $localize`enable` },
      { response: '+plugin/user/run', labelOn: $localize`cancel`, title: $localize`Cancel pushing` },
    ],
    advancedActions: [
      { response: '+plugin/user/run', labelOff: $localize`push`, title: $localize`Push a batch of updates to the remote.`, confirm: $localize`Are you sure you want to push?` },
    ],
    // language=Handlebars
    infoUi: `
      {{#if (and (hasTag '+plugin/origin/pull' ref) (hasTag '+plugin/origin/push' ref))}}
        <span title="Pushing and Pulling is not recommended">⛔️</span>
      {{/if}}`,
    form: [{
      key: 'pushOnChange',
      type: 'boolean',
      defaultValue: true,
      props: {
        label: $localize`Push on change`,
      }
    }, {
      key: 'cache',
      type: 'boolean',
      props: {
        label: $localize`Push cache`,
      }
    }],
    advancedForm: [{
      key: 'query',
      type: 'query'
    }, {
      key: 'batchSize',
      type: 'integer',
      defaultValue: 250,
      props: {
        label: $localize`Batch Size:`,
      }
    }],
  },
  defaults: {
    pushOnChange: true,
    cache: true,
  },
  schema: {
    optionalProperties: {
      pushOnChange: { type: 'boolean' },
      cache: { type: 'boolean' },
      query: { type: 'string' },
      batchSize: { type: 'int32' },
    },
  },
};

export const originTunnelPlugin: Plugin = {
  tag: '+plugin/origin/tunnel',
  name: $localize`🏛️🕳️️️ Origin Tunnel`,
  config: {
    mod: $localize`🏛️ Origin`,
    version: 1,
    default: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    submitChild: $localize`🕳️️️ tunnel`,
    icons: [{ label: $localize`🕳️️️` }],
    description: $localize`Create an SSH tunnel`,
    advancedForm: [{
      key: 'remoteUser',
      type: 'quser',
      props: {
        label: $localize`Remote User:`,
      },
    }, {
      key: 'sshHost',
      type: 'input',
      props: {
        label: $localize`SSH Host:`,
      },
    }, {
      key: 'sshPort',
      type: 'number',
      props: {
        label: $localize`SSH Port:`,
        min: 22,
      },
    }, {
      key: 'hostFingerprint',
      type: 'string',
      props: {
        label: $localize`Host Fingerprint:`
      }
    }],
  },
  schema: {
    optionalProperties: {
      hostFingerprint: { type: 'string' },
      remoteUser: { type: 'string' },
      sshHost: { type: 'string' },
      sshPort: { type: 'uint32' },
    },
  },
};

export const originInitPlugin: Plugin = {
  tag: '_plugin/delta/origin/init',
  name: $localize`🏛️🔑️ Init Sub-Origin`,
  config: {
    mod: $localize`🏛️ Origin`,
    version: 1,
    default: false,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Initialize a sub-origin by granting admin permissions in the
      sub-origin to all users who have signed the origin, and creating a template
      origin Ref in the sub-origin set up to push to it.`,
    advancedActions: [
      {
        if: '+plugin/origin:!+plugin/origin/push:!+plugin/origin/pull:(+user|_user)',
        tag: '_plugin/delta/origin/init',
        labelOff: $localize`init`,
        title: $localize`Grant admin permissions in the sub-origin to all signing users.`,
        confirm: $localize`Are you sure you want to make all signing users admins in the sub-origin?`,
        role: 'ROLE_ADMIN',
        global: true,
      },
    ],
    timeoutMs: 30_000,
    language: 'javascript',
    subDiff: ['script'],
    adminForm: [{
      key: 'script',
      type: 'code',
      props: {
        label: $localize`Script:`,
        language: 'javascript',
      },
    }],
    // language=JavaScript
    script: `
      const axios = require('axios');
      const ref = JSON.parse(require('fs').readFileSync(0, 'utf-8'));
      const origin = ref.origin || '';
      const local = (ref.plugins?.['+plugin/origin']?.local || '').trim();
      if (!local) {
        console.error('Origin local is blank, not a sub-origin.');
        process.exit(1);
      }
      const subOrigin = origin ? origin + '.' + local.replace(/^@/, '') : local;
      const isUser = t => t === '+user' || t === '_user' || t.startsWith('+user/') || t.startsWith('_user/');
      const users = (ref.tags || []).filter(isUser).filter((t, i, a) => a.indexOf(t) === i);
      const api = process.env.JASPER_API + '/api/v1/user';
      const headers = {
        'Local-Origin': origin || 'default',
        'User-Role': 'ROLE_ADMIN',
      };
      const fetchUser = async qualifiedTag => (await axios.get(api, {
        headers,
        params: { tag: qualifiedTag },
      }).catch(e => {
        if (e.response?.status === 404) return { data: null };
        console.error(e.response?.data);
        throw new Error(e);
      })).data;
      for (const tag of users) {
        const source = await fetchUser(tag + origin) || {};
        const existing = await fetchUser(tag + subOrigin);
        const user = {
          ...source,
          tag,
          origin: subOrigin,
          role: 'ROLE_ADMIN',
        };
        delete user.modified;
        delete user.readAccess;
        delete user.writeAccess;
        delete user.tagReadAccess;
        delete user.tagWriteAccess;
        if (!existing) {
          await axios.post(api, user, { headers }).catch(e => {
            console.error(e.response?.data);
            throw new Error(e);
          });
        } else {
          await axios.put(api, { ...user, modified: existing.modified }, { headers }).catch(e => {
            console.error(e.response?.data);
            throw new Error(e);
          });
        }
      }
      const refApi = process.env.JASPER_API + '/api/v1/ref';
      const template = await axios.get(refApi, {
        headers,
        params: { url: ref.url, origin: subOrigin },
      }).then(res => res.data, e => {
        if (e.response?.status === 404) return null;
        console.error(e.response?.data);
        throw new Error(e);
      });
      if (!template) {
        await axios.post(refApi, {
          url: ref.url,
          origin: subOrigin,
          title: ref.title || subOrigin,
          tags: ['public', 'internal', '+plugin/origin', '+plugin/origin/push', ...(users.length ? ['+plugin/origin/tunnel'] : [])],
          plugins: {
            '+plugin/origin': { remote: subOrigin },
            '+plugin/origin/push': ${JSON.stringify(originPushPlugin.defaults)},
            ...(users.length ? { '+plugin/origin/tunnel': { remoteUser: users[0] + subOrigin } } : {}),
          },
        }, { headers }).catch(e => {
          console.error(e.response?.data);
          throw new Error(e);
        });
      }
      ref.tags = ref.tags.filter(t => t !== '_plugin/delta/origin/init' && !t.startsWith('_plugin/delta/origin/init/'));
      delete ref.metadata;
      console.log(JSON.stringify({ ref: [ref] }));
    `,
  },
};

export function isReplicating(local: string, remote: Ref, apis: Map<string, string>) {
  if (!hasTag('+plugin/origin/pull', remote)) return false;
  const plugin = remote.plugins?.['+plugin/origin'];
  if (plugin?.proxy && apis.has(plugin.proxy)) return apis.get(plugin.proxy) === (plugin.remote || '');
  if (apis.has(remote.url)) return apis.get(remote.url) === (plugin?.remote || '');
  return false;
}

export function isPushing(remote: Ref, subOrigin = '') {
  if (!hasTag('+plugin/origin/push', remote)) return false;
  const plugin = remote.plugins?.['+plugin/origin'];
  return (plugin?.local || '') === subOrigin;
}

export const remoteOriginMod: Mod = {
  plugin: [
    originPlugin,
    originPushPlugin,
    originPullPlugin,
    originTunnelPlugin,
    originInitPlugin,
  ],
};
