import { DateTime } from 'luxon';
import { Plugin } from '../../model/plugin';
import { Mod } from '../../model/tag';

export const markerPdfPlugin: Plugin = {
  tag: 'plugin/delta/md/marker',
  name: $localize`⬇️ Marker PDF Query`,
  config: {
    mod: $localize`⬇️ Marker PDF`,
    version: 1,
    type: 'tool',
    default: false,
    add: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Convert PDF documents to Markdown using Marker PDF.`,
    aiInstructions: `# plugin/delta/md/marker
The Marker PDF plugin converts PDF documents to Markdown text.
It uses the marker-pdf Python library to process PDFs.

The plugin creates a response Ref containing the converted Markdown in its comment field.
Resources are fetched through the Jasper proxy API.`,
    icons: [{ label: $localize`⬇️💭️`, order: -1 }],
    filters: [
      { query: 'plugin/delta/md/marker', label: $localize`⬇️💭️ marker markdown query`, title: $localize`Convert PDF to Markdown with Marker PDF`, group: $localize`Notifications ✉️` },
    ],
    actions: [
      { tag: 'plugin/delta/md/marker', labelOn: $localize`cancel`, title: $localize`Cancel Marker PDF conversion.` },
    ],
    advancedActions: [
      { tag: 'plugin/delta/md/marker', labelOff: $localize`markdown`, title: $localize`Convert PDF to Markdown using Marker PDF`, global: true, multi: true },
    ],
    timeoutMs: 600_000,
    requirements: `
      marker-pdf[full]
      requests
    `,
    language: 'python',
    // language=python
    script: `
import json
import os
import sys
import tempfile
import uuid
import requests
from marker.converters.pdf import PdfConverter
from marker.models import create_model_dict
from marker.output import text_from_rendered

ref = json.load(sys.stdin)
origin = ref.get('origin', '')
tags = ref.get('tags', [])

def has_tag(tag, tags):
    return tag in tags or any(t.startswith(tag + '/') for t in tags)

def get_extension_from_url(url):
    url_path = url.split('?')[0]
    if '.' in url_path.split('/')[-1]:
        return '.' + url_path.rsplit('.', 1)[-1].lower()
    return ''

debug_logs = []
debug_mode = has_tag('+plugin/debug', tags)

def log_debug(message):
    if debug_mode:
        debug_logs.append(message)

url = ref.get('plugins', {}).get('plugin/pdf', {}).get('url') or ref.get('url', '')
ext = get_extension_from_url(url)
if not url or ('plugin/pdf' not in tags and ext != '.pdf'):
    log_debug('Ref is not a PDF')
    sys.exit(0)

proxy_url = f"{os.environ['JASPER_API']}/api/v1/proxy"
temp_file = None

try:
    with requests.get(
        proxy_url,
        headers={
            'Local-Origin': origin or 'default',
            'User-Role': 'ROLE_ADMIN',
        },
        params={
            'url': url,
            'origin': ref.get('origin', ''),
        },
        timeout=120,
        stream=True
    ) as response:
        response.raise_for_status()
        temp_file = tempfile.NamedTemporaryFile(delete=False, suffix='.pdf')
        for chunk in response.iter_content(chunk_size=8192):
            if chunk:
                temp_file.write(chunk)
        temp_file.flush()
        temp_file.close()

    converter = PdfConverter(
        artifact_dict=create_model_dict(),
    )
    rendered = converter(temp_file.name)
    markdown_content, _, _ = text_from_rendered(rendered)
    if not markdown_content or not markdown_content.strip():
        markdown_content = '(No text content could be extracted from plugin/pdf)'

    response_ref_tags = ['+plugin/delta/md/marker']

    if 'public' in tags:
        response_ref_tags.append('public')
    if 'internal' in tags:
        response_ref_tags.append('internal')
    if 'dm' in tags:
        response_ref_tags.extend(['dm', 'internal', 'plugin/thread'])
    if 'plugin/comment' in tags:
        response_ref_tags.extend(['plugin/comment', 'internal'])
    if 'plugin/thread' in tags:
        response_ref_tags.extend(['plugin/thread', 'internal'])

    user_tags = [t[1:] for t in tags if t in ('+user', '_user') or t.startswith('+user/') or t.startswith('_user/')]
    mailbox_tags = [t for t in tags if t.startswith('plugin/inbox') or t.startswith('plugin/outbox')]
    response_ref_tags.extend(mailbox_tags)
    response_ref_tags.extend(['plugin/inbox/' + t for t in user_tags])
    if 'public' not in tags:
        response_ref_tags.extend(user_tags)
        response_ref_tags.extend([t for t in tags if t.startswith('user/')])

    seen = set()
    unique_tags = []
    for t in response_ref_tags:
        if t not in seen:
            seen.add(t)
            unique_tags.append(t)

    bundle = {
        'ref': [{
            'origin': origin,
            'url': 'internal:' + str(uuid.uuid4()),
            'title': f"Markdown: {ref.get('title', 'Untitled')} (plugin/pdf)",
            'comment': markdown_content,
            'tags': unique_tags,
            'sources': [ref.get('url')],
        }]
    }

    if debug_mode and debug_logs:
        bundle['ref'].append({
            'url': 'log:' + str(uuid.uuid4()),
            'sources': [ref.get('url')],
            'title': 'Marker PDF Debug Logs',
            'comment': '\\n'.join(debug_logs),
            'tags': ['internal', '+plugin/log'],
        })

    print(json.dumps(bundle))
except requests.exceptions.RequestException as e:
    log_debug(f"Error fetching PDF: {e}")
    raise
finally:
    if temp_file and os.path.exists(temp_file.name):
        os.remove(temp_file.name)
    `,
  },
};

export const markerPdfSignaturePlugin: Plugin = {
  tag: '+plugin/delta/md/marker',
  name: $localize`⬇️ Marker PDF Result`,
  config: {
    mod: $localize`⬇️ Marker PDF`,
    version: 1,
    type: 'tool',
    default: false,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Signature tag for documents converted to Markdown using Marker PDF.`,
    icons: [{ label: $localize`⬇️`, order: 1 }],
    filters: [
      { query: '+plugin/delta/md/marker', label: $localize`⬇️ marker markdown`, title: $localize`Converted to Markdown with Marker PDF`, group: $localize`Delta Δ` },
    ],
    advancedActions: [
      { tag: '+plugin/delta/md/marker', labelOn: $localize`reconvert`, title: $localize`Reconvert PDF to Markdown using Marker PDF` },
      { tag: 'plugin/alias/plugin/delta/md/marker', labelOff: $localize`reconvert`, title: $localize`Reconvert PDF to Markdown using Marker PDF` },
    ],
  },
};

export const markerPdfMod: Mod = {
  plugin: [
    markerPdfPlugin,
    markerPdfSignaturePlugin,
  ],
};
