import { DateTime } from 'luxon';
import { Plugin } from '../../model/plugin';
import { Mod } from '../../model/tag';

export const audioPlugin: Plugin = {
  tag: 'plugin/audio',
  name: $localize`📻️ Audio`,
  config: {
    type: 'plugin',
    default: true,
    proxy: true,
    add: true,
    embeddable: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    submit: $localize`📻️ audio`,
    icons: [{ label: $localize`📻️`, order: 2 }],
    filters: [
      { query: 'plugin/audio', label: $localize`📻️ audio`, title: $localize`Audio`, group: $localize`Media 🎬️` },
    ],
    extensions: ['.mp3', '.aac', '.flac', '.m4a', '.ogg', '.wav'],
    description: $localize`Play audio in an audio player.`,
    advancedForm: [{
      key: 'url',
      type: 'audio',
      props: {
        label: $localize`URL:`,
      },
    }],
  },
  defaults: {},
  schema: {
    optionalProperties: {
      url: { type: 'string' },
    },
  },
};

export const audioMod: Mod = {
  plugin: [
    audioPlugin,
  ],
};
