import { DateTime } from 'luxon';
import { Plugin } from '../../model/plugin';
import { Mod } from '../../model/tag';

export const audioPlugin: Plugin = {
  tag: 'plugin/audio',
  name: $localize`📻️ Audio`,
  config: {
    type: 'plugin',
    version: 1,
    default: true,
    proxy: true,
    add: true,
    embeddable: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    aiInstructions: ` # plugin/audio
    The audio plugin indicates a Ref contains an audio file. It contains optional
    field url which is typically missing. When the url field is missing it is
    assumed to be the URL of the Ref instead.
    You may refer to audio you returned with the URL ai:part, or optionally
    multiple returned assets as ai:part1, ai:part2, etc. These will be uploaded
    to the cache and the URL will be rewritten with it's cache URL. Even if you use
    the url field of an audio plugin, anything not prefixed with ai:part will be
    assumed to refer to an existing URL in the system and not replaced.
    `,
    submit: $localize`📻️ audio`,
    icons: [{ label: $localize`📻️`, order: 2 }],
    filters: [
      { query: 'plugin/audio', label: $localize`📻️ audio`, title: $localize`Audio`, group: $localize`Media 🎬️` },
    ],
    extensions: ['.mp3', '.aac', '.flac', '.m4a', '.ogg', '.wav'],
    description: $localize`Play audio in an audio player.

Keyboard shortcuts (when viewer is focused):
Space / K: Play/pause
J / L: Seek ±10s
← / →: Seek ±5s
↑ / ↓: Volume ±5%
M: Mute toggle
Home / End: Jump to start/end
0–9: Percentage seek`,
    advancedForm: [{
      key: 'url',
      type: 'audio',
      props: {
        label: $localize`URL:`,
      },
    }],
  },
  defaults: {},
  schema: {
    optionalProperties: {
      url: { type: 'string' },
    },
  },
};

export const audioMod: Mod = {
  plugin: [
    audioPlugin,
  ],
};
