import { DateTime } from 'luxon';
import { Plugin } from '../../model/plugin';
import { Mod } from '../../model/tag';

export const audioPlugin: Plugin = {
  tag: 'plugin/audio',
  name: $localize`📻️ Audio`,
  config: {
    type: 'plugin',
    version: 3,
    default: true,
    proxy: true,
    add: true,
    embeddable: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    aiInstructions: ` # plugin/audio
    The audio plugin indicates a Ref contains an audio file. It contains optional
    field url which is typically missing. When the url field is missing it is
    assumed to be the URL of the Ref instead.
    Put each generated audio file in a separate Ref after the first response Ref
    and tag it plugin/audio. Set that Ref's URL to ai:part1, ai:part2, and so on,
    matching the returned assets in order. Never use unnumbered ai:part.
    Embed the audio Ref from the first response comment with ![=](ai:partN), or
    link to it with [audio](/ref/ai:partN). Normally omit plugin/audio.url when
    the Ref's own URL is ai:partN; use the plugin url only when the media differs
    from the Ref URL. Never reference an ai:partN that was not actually returned.
    Claimed assets are uploaded and matching references are rewritten. Other URLs
    refer to existing resources and are not replaced.
    `,
    submit: $localize`📻️ audio`,
    icons: [{ label: $localize`📻️`, order: 2 }],
    filters: [
      { query: 'plugin/audio', label: $localize`📻️ audio`, title: $localize`Audio`, group: $localize`Media 🎬️` },
    ],
    extensions: ['.mp3', '.aac', '.flac', '.m4a', '.ogg', '.wav'],
    description: $localize`Play audio in an audio player.

Keyboard shortcuts (when viewer is focused):
Space / K: Play/pause
J / L: Seek ±10s
← / →: Seek ±5s
↑ / ↓: Volume ±5%
M: Mute toggle
Home / End: Jump to start/end
0–9: Percentage seek`,
    advancedForm: [{
      key: 'url',
      type: 'audio',
      props: {
        label: $localize`URL:`,
      },
    }],
  },
  defaults: {},
  schema: {
    optionalProperties: {
      url: { type: 'string' },
    },
  },
};

export const audioMod: Mod = {
  plugin: [
    audioPlugin,
  ],
};
