import { DateTime } from 'luxon';
import { Plugin } from '../../model/plugin';
import { Mod } from '../../model/tag';

export const codePlugin: Plugin = {
  tag: 'plugin/code',
  name: $localize`🗒️ Code`,
  config: {
    type: 'editor',
    version: 3,
    default: true,
    add: true,
    submit: $localize`🗒️ code`,
    editor: true,
    embeddable: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Uses the monaco editor (like vscode).`,
    aiInstructions: `# plugin/code
    The plugin/code tag indicates that a Ref's entire comment is raw source code.
    Use a child tag such as plugin/code/json to identify the language or format.
    Put each requested file in a separate Ref after the first response Ref, using
    a temporary URL such as add:code1. Do not put code in the first response Ref.
    Embed the code Ref from the first response comment with ![=](add:code1), or
    link to it with [filename](/ref/add:code1).
    Never wrap the code Ref's comment in triple backticks or add explanatory text
    to it. Markdown fences and explanations belong only in the first response Ref.`,
    icons: [{ label: $localize`🗒️`, order: 2 }],
    filters: [
      { query: 'plugin/code', label: $localize`🗒️ code`, title: $localize`Code`, group: $localize`Media 🎬️` },
    ],
  },
};

export function mimeToCode(mime: string) {
  if (!mime) return ['plugin/code'];
  switch (mime) {
    case 'text/markdown':
    case 'text/plain': return ['plugin/code/md'];
    case 'text/vnd.qt.linguist': return ['plugin/code/typescript'];
    case 'text/x-patch': return ['plugin/code/diff'];
    case 'application/x-yaml': return ['plugin/code/yaml'];
    case 'application/x-shellscript': return ['plugin/code/shell'];
    case 'application/x-httpd-php': return ['plugin/code/php'];
    case 'application/xml':
    case 'application/xhtml+xml': return ['plugin/code/html'];
    case 'application/json': return ['plugin/code/json'];
  }
  if (mime.startsWith('text/x-')) return ['plugin/code/' + mime.substring('text/x-'.length)]
  if (mime.startsWith('text/')) return ['plugin/code/' + mime.substring('text/'.length)]
  if (mime.startsWith('application/') && mime.endsWith('+xml')) return ['plugin/code/xml']
  return [];
}

export const codeMod: Mod = {
  plugin: [
    codePlugin,
  ]
};
