import { DateTime } from 'luxon';
import { Plugin } from '../../model/plugin';
import { Mod } from '../../model/tag';

export const durationPlugin: Plugin = {
  tag: 'plugin/duration',
  name: $localize`⏱️ Duration`,
  config: {
    type: 'plugin',
    default: true,
    add: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Stores media duration in the tag itself (e.g., plugin/duration/pt15m).`,
    infoUi: `{{#if (duration ref 'plugin/duration')}}<span class="info-tag" title="Duration">⏱️ {{human (duration ref 'plugin/duration')}}</span>{{/if}}`,
  },
};

export const durationMod: Mod = {
  plugin: [
    durationPlugin,
  ]
};
