import { DateTime } from 'luxon';
import { Plugin } from '../../model/plugin';
import { Mod } from '../../model/tag';

export const durationPlugin: Plugin = {
  tag: 'plugin/duration',
  name: $localize`⏱️ Duration`,
  config: {
    type: 'plugin',
    default: true,
    add: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Stores media duration in the tag itself (e.g., plugin/duration/pt15m).`,
    // language=HTML
    snippet: `
      <script>
        Handlebars.registerHelper('duration', (tags) => {
          const t = tags?.find(t => t.startsWith('plugin/duration/') && t.length > 16);
          if (!t) return '';
          try {
            const iso = t.substring(16).toUpperCase();
            const m = iso.match(/^P(?:(\d+)Y)?(?:(\d+)M)?(?:(\d+)D)?(?:T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+(?:\.\d+)?)S)?)?$/);
            if (!m) return '';
            const parts = [];
            if (m[1]) parts.push(m[1] + ' ' + (m[1] == '1' ? 'year' : 'years'));
            if (m[2]) parts.push(m[2] + ' ' + (m[2] == '1' ? 'month' : 'months'));
            if (m[3]) parts.push(m[3] + ' ' + (m[3] == '1' ? 'day' : 'days'));
            if (m[4]) parts.push(m[4] + ' ' + (m[4] == '1' ? 'hour' : 'hours'));
            if (m[5]) parts.push(m[5] + ' ' + (m[5] == '1' ? 'minute' : 'minutes'));
            if (m[6]) { const s = parseFloat(m[6]); parts.push(s + ' ' + (s == 1 ? 'second' : 'seconds')); }
            return parts.join(', ');
          } catch (e) {
            return '';
          }
        });
      </script>
    `,
    infoUi: `{{#if (duration ref.tags)}}<span class="info-tag" title="Duration">⏱️ {{duration ref.tags}}</span>{{/if}}`,
  },
};

export const durationMod: Mod = {
  plugin: [
    durationPlugin,
  ]
};
