import { DateTime } from 'luxon';
import { Plugin } from '../../model/plugin';
import { Mod } from '../../model/tag';

export const filePlugin: Plugin = {
  tag: 'plugin/file',
  name: $localize`💾️️ File`,
  config: {
    mod: $localize`💾️️ File Cache`,
    version: 3,
    default: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    aiInstructions: ` # plugin/file
    The file plugin indicates a Ref contains a file received from the AI. It is
    used with the cache plugin (_plugin/cache) to store the received file in
    this server's file cache.
    Refer to each file you return with a numbered URL such as ai:part1,
    ai:part2, etc. These will be uploaded to the cache and the URL will be
    rewritten with its cache URL.
    `,
    icons: [{ label: $localize`💾️️`, order: 1 }],
    description: $localize`Allow storing user files on the server.`,
    filters: [
      { query: 'plugin/file', label: $localize`💾️️ file`, title: $localize`Uploaded Files`, group: $localize`Media 🎬️` },
    ],
    editorButtons: [
      { event: 'attach', label: $localize`📎️`, title: $localize`Attach File`, global: true },
    ],
  },
};

export const fileMod: Mod = {
  plugin: [
    filePlugin,
  ]
};
