import { DateTime } from 'luxon';
import { Plugin } from '../../model/plugin';
import { Mod } from '../../model/tag';
import { Template } from '../../model/template';

export const imagePlugin: Plugin = {
  tag: 'plugin/image',
  name: $localize`🖼️ Image`,
  config: {
    mod: $localize`🖼️ Images`,
    version: 5,
    type: 'plugin',
    default: true,
    proxy: true,
    add: true,
    embeddable: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    adminForm: [{
      key: 'aiInstructions',
      type: 'editor',
      props: {
        label: $localize`AI Instructions:`,
      },
    }],
    aiInstructions: ` # plugin/image
The image plugin indicates a Ref contains an image. It is strongly associated
with plugin/thumbnail. It contains optional fields { url, width, height } which
are typically all missing. When the url field is missing it is assumed to be the
URL of the Ref instead.
When an image-generation tool is available, use it for requests to create or modify
images. For every generated image you want retained, return a separate Ref tagged
plugin/image whose URL is ai:part1, ai:part2, and so on, corresponding to the
returned assets in order. Never use unnumbered ai:part. Embed the image from the
first response comment with ![](ai:partN), or link to it with [image](/ref/ai:partN).
The Ref may include a title, tags, and plugin/image data; when its own URL is
ai:partN, normally omit plugin/image.url. Only an explicit Ref URL or media-plugin
URL claims an asset; unclaimed generated assets are discarded. Never invent or
reference ai:partN unless the corresponding asset was actually returned.
Claimed assets are uploaded to the cache and all matching references are rewritten.
Non-ai:part URLs refer to existing resources and are not replaced.
Only set the width/height in the plugin data to disable autosizing.
    `,
    submit: $localize`🖼️ image`,
    icons: [{ label: $localize`🖼️`, order: 2 }],
    filters: [
      { query: 'plugin/image', label: $localize`🖼️ image`, title: $localize`Images`, group: $localize`Media 🎬️` },
    ],
    extensions: ['.png', '.jpg', '.jpeg', '.gif', '.svg', '.webp'],
    description: $localize`Display an image.`,
    advancedForm: [{
      key: 'url',
      type: 'image',
      props: {
        label: $localize`URL: `,
      },
    }, {
      key: 'width',
      type: 'number',
      props: {
        label: $localize`Width: `,
      },
    }, {
      key: 'height',
      type: 'number',
      props: {
        label: $localize`Height: `,
      },
    }],
  },
  schema: {
    optionalProperties: {
      url: { type: 'string' },
      width: { type: 'uint16' },
      height: { type: 'uint16' },
    },
  },
};

export const imageTemplate: Template = {
  tag: 'plugin/image',
  name: $localize`🖼️ Images`,
  config: {
    mod: $localize`🖼️ Images`,
    version: 3,
    type: 'plugin',
    default: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    view: $localize`🖼️`,
    description: $localize`Activates built-in Image viewer mode for viewing Refs.`,
    // language=CSS
    css: `
      app-ref-list.plugin_image {
        max-width: 100%;
        .list-container {
          grid-auto-flow: row dense;
          padding: 4px;
          gap: 8px;
          grid-template-columns:  1fr;
          @media (min-width: 1000px) {
            grid-template-columns:  1fr 1fr;
          }
          @media (min-width: 1500px) {
            grid-template-columns: 1fr 1fr 1fr;
          }
          @media (min-width: 2000px) {
            grid-template-columns: 1fr 1fr 1fr 1fr;
          }
          .list-number {
            display: none;
          }
          & > .ref {
            position: relative;
            margin: 0;
            padding: 0;
            grid-template-columns:
              [voting] auto
              [thumbnail] auto
              [toggle] auto
              [main] minmax(0, max-content)
              [actions-toggle] auto
              [nav-toggle] auto
              [end] minmax(0, 1fr);
            grid-template-rows: auto auto auto 1fr;
            .expand {
              display: none;
            }
            .image-expand {
              position: relative;
              min-width: 100%;
              min-height: 100%;
              border-radius: 7px;
              overflow: hidden;
              margin: 0;
              padding: 0;
            }
            & > .embed {
              grid-area: 1 / 1 / 5 / -1;
            }
            &::after,
            & > .voting,
            & > .link,
            & > .info,
            & > .actions {
              visibility: hidden;
            }
            &::after {
              content: '';
              grid-area: 1 / voting / 4 / end;
              margin: 6px;
              border-radius: 8px;
              z-index: 1;
              pointer-events: none;
            }
            & > .voting,
            & > .link,
            & > .info,
            & > .actions {
              z-index: 2;
              margin-left: 14px;
            }
            & > .link,
            & > .info,
            & > .actions {
              margin-right: 14px;
              overflow: hidden;
            }
            & > .link {
              grid-row: 1;
              margin-top: 14px;
            }
            & > .info {
              grid-row: 2;
            }
            & > .actions {
              grid-row: 3;
              margin-bottom: 14px;
            }
            &:hover::after,
            &:hover > .voting,
            &:hover > .link,
            &:hover > .info,
            &:hover > .actions {
              visibility: visible;
            }
            & > .embed:focus-within {
              z-index: 3;
            }
            &.mobile-unlock::after,
            &.mobile-unlock > .voting,
            &.mobile-unlock > .link,
            &.mobile-unlock > .info,
            &.mobile-unlock > .actions {
              visibility: visible !important;
            }
            &.mobile-unlock > .embed {
              z-index: auto !important;
            }
            & > .toggle,
            & > .thumbnail {
              display: none;
            }
          }
        }
      }
      body.dark-theme app-ref-list.plugin_image {
        .list-container > .ref::after {
          -webkit-backdrop-filter: grayscale(1) contrast(0.4) brightness(0.4) blur(8px);
          backdrop-filter: grayscale(1) contrast(0.4) brightness(0.4) blur(8px);
          border: 0.5px solid rgba(255, 255, 255, 0.2);
        }
        .list-container > .ref .image-expand {
          -webkit-backdrop-filter: grayscale(1) brightness(0.9) blur(0.5px);
          backdrop-filter: grayscale(1) brightness(0.9) blur(0.5px);
        }
      }
      body.light-theme app-ref-list.plugin_image {
        .list-container > .ref::after {
          -webkit-backdrop-filter: grayscale(1) contrast(0.3) brightness(1.5) blur(8px);
          backdrop-filter: grayscale(1) contrast(0.3) brightness(1.5) blur(8px);
        }
        .list-container > .ref .image-expand {
          -webkit-backdrop-filter: grayscale(1) brightness(0.9) blur(0.5px);
          backdrop-filter: grayscale(1) brightness(0.9) blur(0.5px);
        }
      }
    `,
    advancedForm: [{
      key: 'defaultExpanded',
      type: 'boolean',
      defaultValue: true,
      props: {
        label: $localize`Default Expanded:`,
      },
    }, {
      key: 'hideEdit',
      type: 'boolean',
      defaultValue: true,
      props: {
        label: $localize`Hide Edit:`,
      },
    }, {
      key: 'disableResize',
      type: 'boolean',
      defaultValue: true,
      props: {
        label: $localize`Disable Resize:`,
      },
    }],
  },
  defaults: {
    defaultExpanded: true,
    hideEdit: true,
    disableResize: true,
    defaultCols: 0, // Leave to CSS screen size detection, but show cols dropdown
  }
};

export const imageMod: Mod = {
  plugin: [
    imagePlugin,
  ],
   template: [
    imageTemplate,
  ],
};
