import { DateTime } from 'luxon';
import { Plugin } from '../../model/plugin';
import { Mod } from '../../model/tag';

export const mp3DeltaPlugin: Plugin = {
  tag: '_plugin/delta/mp3',
  name: $localize`▶️ Get MP3`,
  config: {
    mod: $localize`▶️ Get MP3`,
    version: 1,
    default: false,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Download mp3s using YT-DLP.`,
    actions: [
      { if: 'plugin/embed', tag: '_plugin/delta/mp3', labelOff: $localize`mp3`, title: $localize`Download video with YT-DLP.`, global: true },
      { tag: '_plugin/delta/mp3', labelOn: $localize`cancel`, title: $localize`Cancel YT-DLP.` },
    ],
    timeoutMs: 900_000,
    requirements: `
      yt-dlp
      requests
    `,
    language: 'python',
    // language=python
    script: `
import tempfile
import os
import sys
import requests
import json
import yt_dlp
ref = json.load(sys.stdin)
origin = ref.get('origin', '')
url = ref.get('plugins', {}).get('plugin/embed', {}).get('url', ref.get('url', ''))
with tempfile.NamedTemporaryFile(delete=False) as temp_file:
  base_name = temp_file.name
try:
  ydl_opts = {
    'outtmpl': f'{base_name}',
    'remote_components': ['ejs:github'],
    'js_runtimes': {'bun': {'path': os.environ['JASPER_NODE']}},
    'noprogress': True,
    'format': 'bestaudio[ext=m4a]/bestaudio[ext=mp3]/bestaudio',
    'postprocessors': [{
      'key': 'FFmpegExtractAudio',
      'preferredcodec': 'mp3',
      'preferredquality': '256K',
    }],
  }
  saveStdout = sys.stdout
  sys.stdout = sys.stderr
  try:
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
      info = ydl.extract_info(url, download=True)
      ext = info.get('ext', 'mp4')
  except Exception as e:
    if 'This live event will begin in' in str(e):
      sys.exit(0)
    raise
  finally:
    sys.stdout = saveStdout

  # Read the file content
  with open(base_name, 'rb') as f:
    file_data = f.read()
  response = requests.post(
    f"{os.environ['JASPER_API']}/pub/api/v1/repl/cache",
    data=file_data,
    headers={
      'Local-Origin': origin or 'default',
      'User-Role': 'ROLE_ADMIN',
      'Content-Type': 'mp3',
    },
    params={
      'origin': origin,
      'title': ref.get('title', ''),
      'mime': 'mp3',
    }
  )
  if not response.ok:
    print(f"Error {response.status_code}: {response.text}", file=sys.stderr)
    sys.exit(1)
  cache = response.json()
  ref.pop('metadata', None)
  ref.setdefault('tags', []).append('plugin/video')
  ref['tags'] = [t for t in ref['tags'] if not (t + '/').startswith('_plugin/delta/mp3/') and not (t + '/').startswith('plugin/embed/')]
  ref.setdefault('plugins', {}).setdefault('plugin/video', {})['url'] = cache['url']
  ref.setdefault('plugins', {}).pop('plugin/embed', None)
  print(json.dumps({
    'ref': [{
      **cache,
      **ref,
    }],
  }))
finally:
  # Clean up both the base temp file and the downloaded file
  if os.path.exists(base_name):
    os.remove(base_name)
    `,
  },
};

export const mp3Mod: Mod = {
  plugin: [
    mp3DeltaPlugin,
  ]
};
