import { DateTime } from 'luxon';
import { Plugin } from '../../model/plugin';
import { Mod } from '../../model/tag';

export const mp3DeltaPlugin: Plugin = {
  tag: '_plugin/delta/mp3',
  name: $localize`💽 Get MP3`,
  config: {
    mod: $localize`💽 Get MP3`,
    version: 1,
    type: 'tool',
    default: false,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Download mp3s using YT-DLP.`,
    actions: [
      { if: 'plugin/embed', tag: '_plugin/delta/mp3', labelOff: $localize`mp3`, title: $localize`Download mp3 YT-DLP.`, global: true },
      { tag: '_plugin/delta/mp3', labelOn: $localize`cancel`, title: $localize`Cancel YT-DLP.` },
    ],
    timeoutMs: 900_000,
    requirements: `
      yt-dlp
      requests
    `,
    language: 'python',
    // language=python
    script: `
import tempfile
import os
import sys
import requests
import json
import yt_dlp
ref = json.load(sys.stdin)
origin = ref.get('origin', '')
url = ref.get('plugins', {}).get('plugin/embed', {}).get('url', ref.get('url', ''))
base_opts = {
    'remote_components': ['ejs:github'],
    'js_runtimes': {'bun': {'path': os.environ['JASPER_NODE']}},
    'noprogress': True,
    'format': 'bestaudio[ext=m4a]/bestaudio[ext=mp3]/bestaudio',
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'mp3',
        'preferredquality': '256K',
    }],
}
def has_tag(tag, tags):
    return tag in tags or any(t.startswith(tag + '/') for t in tags)
def process_single_track(track_url, track_title):
    with tempfile.NamedTemporaryFile(delete=False) as temp_file:
        base_name = temp_file.name
    downloaded_file = None
    try:
        ydl_opts = {**base_opts, 'outtmpl': f'{base_name}.%(ext)s'}
        saveStdout = sys.stdout
        sys.stdout = sys.stderr
        try:
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(track_url, download=True)
                ext = info.get('ext', 'mp3').lower()
        except Exception as e:
            if 'This live event will begin in' in str(e):
                return None
            raise
        finally:
            sys.stdout = saveStdout
        downloaded_file = f'{base_name}.{ext}'
        if not os.path.exists(downloaded_file):
            for fallback_ext in ['mp3', 'm4a', 'webm', 'ogg']:
                if os.path.exists(f"{base_name}.{fallback_ext}"):
                    downloaded_file = f"{base_name}.{fallback_ext}"
                    ext = fallback_ext
                    break
        if not downloaded_file or not os.path.exists(downloaded_file):
            print(f"Error: Could not locate downloaded file for {track_title}", file=sys.stderr)
            sys.exit(1)
        with open(downloaded_file, 'rb') as f:
            file_data = f.read()
        mime_types = {
          'mp3': 'audio/mpeg',
          'm4a': 'audio/mp4',
          'webm': 'audio/webm',
          'opus': 'audio/opus',
          'ogg': 'audio/ogg',
          'wav': 'audio/wav',
          'flac': 'audio/flac',
          'aac': 'audio/aac',
        }
        mime = mime_types.get(ext, 'application/octet-stream')
        response = requests.post(
            f"{os.environ['JASPER_API']}/pub/api/v1/repl/cache",
            data=file_data,
            headers={
                'Local-Origin': origin or 'default',
                'User-Role': 'ROLE_ADMIN',
                'Content-Type': mime,
            },
            params={
                'origin': origin,
                'title': track_title + '.' + ext,
                'mime': mime,
            }
        )
        if not response.ok:
            print(f"Error {response.status_code}: {response.text}", file=sys.stderr)
            sys.exit(1)
        return response.json()
    finally:
        if os.path.exists(base_name):
            os.remove(base_name)
        if downloaded_file and os.path.exists(downloaded_file):
            os.remove(downloaded_file)
        for clean_ext in ['mp3', 'm4a', 'webm', 'ogg', 'opus']:
            if os.path.exists(f"{base_name}.{clean_ext}"):
                os.remove(f"{base_name}.{clean_ext}")
saveStdout = sys.stdout
sys.stdout = sys.stderr
try:
    with yt_dlp.YoutubeDL({**base_opts, 'extract_flat': True}) as ydl:
        info = ydl.extract_info(url, download=False)
except Exception as e:
    if 'This live event will begin in' in str(e):
        sys.exit(0)
    raise
finally:
    sys.stdout = saveStdout
output_refs = []
source_urls = []
if 'entries' in info:
    playlist_title = info.get('title', ref.get('title', 'Playlist'))
    parent_tags = ref.get('tags', [])
    child_extra_tags = []
    if has_tag('public', parent_tags):
        for t in parent_tags:
            if t == 'public' or t.startswith('public/'):
                if t not in child_extra_tags:
                    child_extra_tags.append(t)
    for t in parent_tags:
        if t.startswith('_user/') or t.startswith('+user/') or t.startswith('user/'):
            if t not in child_extra_tags:
                child_extra_tags.append(t)
    for index, entry in enumerate(info['entries']):
        if not entry: continue
        entry_url = entry.get('url') or entry.get('webpage_url')
        entry_title = entry.get('title') or f"Track {index + 1}"
        formatted_title = f"{index + 1:02d} - {entry_title}"
        cache_data = process_single_track(entry_url, formatted_title)
        if not cache_data: continue
        child_tags = ['plugin/audio'] + child_extra_tags
        child_ref = {
            'url': entry_url,
            'origin': origin,
            'title': formatted_title,
            'tags': child_tags,
            'plugins': {'plugin/audio': {'url': cache_data['url']}}
        }
        output_refs.append(child_ref)
        source_urls.append(entry_url)
    ref.pop('metadata', None)
    ref.setdefault('tags', []).append('plugin/playlist')
    ref['tags'] = [t for t in ref['tags'] if not (t + '/').startswith('_plugin/delta/mp3/') and not (t + '/').startswith('plugin/embed/')]
    ref.setdefault('plugins', {}).pop('plugin/embed', None)
    ref['sources'] = source_urls
    output_refs.insert(0, ref)
else:
    track_title = info.get('title', ref.get('title', ''))
    cache_data = process_single_track(url, track_title)
    if cache_data:
        ref.pop('metadata', None)
        ref.setdefault('tags', []).append('plugin/audio')
        ref['tags'] = [t for t in ref['tags'] if not (t + '/').startswith('_plugin/delta/mp3/') and not (t + '/').startswith('plugin/embed/')]
        ref.setdefault('plugins', {}).setdefault('plugin/audio', {})['url'] = cache_data['url']
        ref.setdefault('plugins', {}).pop('plugin/embed', None)
        output_refs.append({**cache_data, **ref})
print(json.dumps({'ref': output_refs}))
    `,
  },
};

export const mp3Mod: Mod = {
  plugin: [
    mp3DeltaPlugin,
  ]
};
