import { DateTime } from 'luxon';
import { Plugin } from '../../model/plugin';
import { Mod } from '../../model/tag';
import { Template } from '../../model/template';

export const playlistPlugin: Plugin = {
  tag: 'plugin/playlist',
  name: $localize`⏭️ Playlist`,
  config: {
    name: $localize`⏭️ Playlist`,
    version: 2,
    type: 'semantic',
    default: true,
    add: true,
    embeddable: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Create a playlist from the list of sources`,
    icons: [{ label: $localize`⏭️`, order: 1 }],
    filters: [
      { query: 'plugin/playlist', label: $localize`⏭️ playlist`, title: $localize`Playlists`, group: $localize`Media 🎬️` },
    ],
    advancedActions: [
      { event: 'media', label: $localize`media` },
    ]
  },
};

export const playlistMod: Mod = {
  plugin: [
    playlistPlugin,
  ],
};
