import { DateTime } from 'luxon';
import { Plugin } from '../../model/plugin';
import { Mod } from '../../model/tag';

export const ytDeltaPlugin: Plugin = {
  tag: '_plugin/delta/yt',
  name: $localize`🔍️ yt-dlp Metadata`,
  config: {
    type: 'plugin',
    default: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Fetches metadata and storyboards using yt-dlp.`,
    language: 'python',
    // language=Python
    script: `
import json
import sys
import urllib.request
import os
import yt_dlp

def main():
    stdin = sys.stdin.read()
    if not stdin:
        return sys.exit(1)

    payload = json.loads(stdin)
    refs = payload.get('ref', [])
    if not refs:
        return sys.exit(0)

    ref = refs[0]
    url = ref.get('url')

    ydl_opts = {
        'quiet': True,
        'skip_download': True,
    }

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=False)
    except Exception as e:
        print(json.dumps({'error': str(e)}))
        return sys.exit(1)

    duration = info.get('duration')
    storyboards = info.get('storyboards', [])
    video_id = info.get('id', 'unknown_id')

    # Duration handling via tag (plugin/duration/...)
    if duration:
        m, s = divmod(duration, 60)
        h, m = divmod(m, 60)
        iso_dur = 'pt'
        if h > 0: iso_dur += f'{int(h)}h'
        if m > 0: iso_dur += f'{int(m)}m'
        iso_dur += f'{int(s)}s'

        tags = ref.get('tags', [])
        if 'plugin/duration' not in tags:
            tags.append('plugin/duration')

        # Filter out old durations and add the newly fetched one
        tags = [t for t in tags if not t.startswith('plugin/duration/')]
        tags.append(f'plugin/duration/{iso_dur}')
        ref['tags'] = tags

    # Storyboard handling
    plugins = ref.get('plugins', {})
    if storyboards:
        storage_dir = os.path.join('/var/lib/jasper', 'storyboards', video_id)
        os.makedirs(storage_dir, exist_ok=True)

        # Target the best available storyboard spec
        spec = storyboards[-1]
        sb_url = spec.get('url')
        if sb_url:
            try:
                filename = f"{video_id}_storyboard.jpg"
                local_path = os.path.join(storage_dir, filename)
                urllib.request.urlretrieve(sb_url, local_path)

                plugins['plugin/thumbnail/storyboard'] = {
                    'url': f'/storyboards/{video_id}/{filename}',
                    'width': spec.get('width', 160),
                    'height': spec.get('height', 90),
                    'x': 0,
                    'y': 0
                }
            except Exception as e:
                pass

    ref['plugins'] = plugins

    # Remove the yt trigger tag so it doesn't infinitely loop
    ref['tags'] = [t for t in ref.get('tags', []) if t != '_plugin/delta/yt']

    print(json.dumps({'ref': [ref]}))

if __name__ == '__main__':
    main()
`
  },
  defaults: {},
  schema: {},
};

export const ytInfoMod: Mod = {
  plugin: [
    ytDeltaPlugin,
  ]
};
