import { DateTime } from 'luxon';
import { Plugin } from '../../model/plugin';
import { Mod } from '../../model/tag';

export const ytDeltaPlugin: Plugin = {
  tag: '_plugin/delta/yt',
  name: $localize`🔍️ yt-dlp Metadata`,
  config: {
    default: true,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Fetches metadata and storyboards using yt-dlp.`,
    language: 'python',
    timeoutMs: 300_000,  // 5 minutes should be sufficient for metadata fetching
    requirements: `
      yt-dlp
    `,
    // language=Python
    script: `
import json
import sys
import yt_dlp

ref = json.load(sys.stdin)
plugins = ref.get('plugins', {})
embed = plugins.get('plugin/embed', {})
url = embed.get('url') or ref.get('url')

ydl_opts = {
    'quiet': True,
    'skip_download': True,
}

try:
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        info = ydl.extract_info(url, download=False)
except Exception as e:
    print(json.dumps({'error': str(e)}), file=sys.stderr)
    sys.exit(1)

duration = info.get('duration')
storyboards = [f for f in info.get('formats', []) if f.get('format_note') == 'storyboard']

# Duration handling via tag (plugin/duration/...)
if duration:
    m, s = divmod(duration, 60)
    h, m = divmod(m, 60)
    iso_dur = 'pt'
    if h > 0: iso_dur += f'{int(h)}h'
    if m > 0: iso_dur += f'{int(m)}m'
    iso_dur += f'{int(s)}s'

    tags = ref.get('tags', [])
    # Filter out old durations and add the newly fetched one
    tags = [t for t in tags if not t.startswith('plugin/duration/')]
    tags.append(f'plugin/duration/{iso_dur}')
    ref['tags'] = tags

# Storyboard handling
plugins = ref.get('plugins', {})
if storyboards:
    # Target the best available storyboard spec
    # Pick the storyboard with the highest individual frame resolution
    spec = max(storyboards, key=lambda f: f.get('width', 0) * f.get('height', 0))
    # URL contains $M placeholder for fragment index; use fragment 0
    sb_url = spec.get('url', '').replace('$M', '0')
    if sb_url:
        plugins['plugin/thumbnail/storyboard'] = {
            'url': sb_url,
            'width': int(spec.get('width', 160)),
            'height': int(spec.get('height', 90)),
            'rows': int(spec.get('rows', 1)),
            'cols': int(spec.get('columns', 1))
        }
        tags = ref.get('tags', [])
        if 'plugin/thumbnail/storyboard' not in tags:
            tags.append('plugin/thumbnail/storyboard')
            ref['tags'] = tags

ref['plugins'] = plugins

# Remove the yt trigger tag so it doesn't infinitely loop
ref['tags'] = [t for t in ref.get('tags', []) if not (t + '/').startswith('_plugin/delta/yt/')]

ref.pop('metadata', None)
print(json.dumps({'ref': [ref]}))
`
  },
};

export const ytInfoMod: Mod = {
  plugin: [
    ytDeltaPlugin,
  ]
};
