import { DateTime } from 'luxon';
import { Plugin } from '../../model/plugin';
import { Mod } from '../../model/tag';

/**
 * Python helpers for delta scripts that update the input Ref in-place.
 * Requires the requests package.
 * save_ref(ref, update) reloads the latest Ref, applies update to a copy and pushes
 * the result through the replicate endpoint (which does not require CSRF) with a new
 * modified date. If saving fails it is retried. Return None from update to skip saving.
 * Unless exit_on_failure is False, the script exits if the Ref can never be saved.
 */
// language=python
export const pythonSaveRef = `
import copy as _copy
import datetime as _datetime
import os as _os
import sys as _sys
import time as _time
import requests as _requests
def fetch_ref(url, origin):
    response = _requests.get(
        f"{_os.environ['JASPER_API']}/api/v1/ref",
        headers={
            'Local-Origin': origin or 'default',
            'User-Role': 'ROLE_ADMIN',
        },
        params={
            'url': url,
            'origin': origin,
        },
        timeout=30,
    )
    if not response.ok:
        raise Exception(f"{response.status_code}: {response.text}")
    return response.json()
def push_ref(ref):
    origin = ref.get('origin') or ''
    pushed = {k: v for k, v in ref.items() if k != 'metadata'}
    pushed['origin'] = origin
    pushed['modified'] = _datetime.datetime.now(_datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%fZ')
    response = _requests.post(
        f"{_os.environ['JASPER_API']}/pub/api/v1/repl/ref",
        headers={
            'Local-Origin': origin or 'default',
            'User-Role': 'ROLE_ADMIN',
        },
        params={
            'origin': origin,
        },
        json=[pushed],
        timeout=30,
    )
    if not response.ok:
        raise Exception(f"{response.status_code}: {response.text}")
    return pushed
def save_ref(ref, update, attempts=5, exit_on_failure=True):
    origin = ref.get('origin') or ''
    for attempt in range(attempts):
        if attempt: _time.sleep(attempt)
        try:
            latest = fetch_ref(ref['url'], origin)
        except Exception as e:
            print(f"Error reloading Ref: {e}", file=_sys.stderr)
            continue
        updated = update(_copy.deepcopy(latest))
        if updated is None or updated == latest: return latest
        try:
            return push_ref(updated)
        except Exception as e:
            print(f"Error saving Ref: {e}", file=_sys.stderr)
    print(f"Could not save Ref {origin} {ref['url']}", file=_sys.stderr)
    if exit_on_failure: _sys.exit(1)
`;

/**
 * Python helper for delta scripts that report progress with the plugin/progress tag.
 * Requires pythonSaveRef. The _seal/delta tag prevents the update from re-triggering the delta.
 */
// language=python
export const pythonReportProgress = `
_progress_state = {'tag': None, 'time': 0}
def report_progress(ref, value, max=100, force=False):
    tag = f'plugin/progress/{int(value)}/{int(max)}'
    now = _time.monotonic()
    if tag == _progress_state['tag'] or not force and now - _progress_state['time'] < 1: return
    _progress_state['tag'] = tag
    _progress_state['time'] = now
    def update(latest):
        latest['tags'] = [t for t in latest.get('tags') or [] if not (t + '/').startswith('plugin/progress/') and t != '_seal/delta'] + [tag, '_seal/delta']
        return latest
    save_ref(ref, update, attempts=1, exit_on_failure=False)
`;

export const ytdlpDeltaPlugin: Plugin = {
  tag: '_plugin/delta/ytdlp',
  name: $localize`▶️ Get Video`,
  config: {
    mod: $localize`▶️ YT-DLP`,
    version: 4,
    type: 'tool',
    default: false,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Download and cache videos using YT-DLP.`,
    actions: [
      { if: 'plugin/embed', tag: '_plugin/delta/ytdlp', labelOff: $localize`yt-dlp`, title: $localize`Download video with YT-DLP.`, global: true },
      { tag: '_plugin/delta/ytdlp', labelOn: $localize`cancel`, title: $localize`Cancel YT-DLP.` },
    ],
    timeoutMs: 900_000,
    requirements: `
      yt-dlp
      requests
    `,
    language: 'python',
    subDiff: ['script'],
    adminForm: [{
      key: 'script',
      type: 'code',
      props: {
        label: $localize`Script:`,
        language: 'python',
      },
    }],
    // language=python
    script: `
import tempfile
import os
import sys
import requests
import json
import yt_dlp
${pythonSaveRef}
${pythonReportProgress}
ref = json.load(sys.stdin)
origin = ref.get('origin', '')
url = ref.get('plugins', {}).get('plugin/embed', {}).get('url', ref.get('url', ''))
def on_progress(d):
  if d.get('status') != 'downloading': return
  total = d.get('total_bytes') or d.get('total_bytes_estimate')
  done = d.get('downloaded_bytes')
  if total and done is not None:
    report_progress(ref, min(99, 100 * done // total))
report_progress(ref, 0)
with tempfile.NamedTemporaryFile(delete=False) as temp_file:
  base_name = temp_file.name
downloaded_file = None
try:
  ydl_opts = {
    'outtmpl': f'{base_name}.%(ext)s',
    'remote_components': ['ejs:github'],
    'js_runtimes': {'bun': {'path': os.environ['JASPER_NODE']}},
    'noprogress': True,
    'progress_hooks': [on_progress],
  }
  saveStdout = sys.stdout
  sys.stdout = sys.stderr
  try:
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
      info = ydl.extract_info(url, download=True)
      ext = info.get('ext', 'mp4')
  except Exception as e:
    if 'This live event will begin in' in str(e):
      sys.exit(0)
    raise
  finally:
    sys.stdout = saveStdout

  # Find the actual downloaded file
  downloaded_file = f'{base_name}.{ext}'

  # Read the file content
  with open(downloaded_file, 'rb') as f:
    file_data = f.read()

  # Determine mime type based on extension
  mime_types = {
    'mp4': 'video/mp4',
    'webm': 'video/webm',
    'mp3': 'audio/mpeg',
    'm4a': 'audio/mp4',
    'mkv': 'video/x-matroska',
  }
  mime = mime_types.get(ext, 'application/octet-stream')

  response = requests.post(
    f"{os.environ['JASPER_API']}/pub/api/v1/repl/cache",
    data=file_data,
    headers={
      'Local-Origin': origin or 'default',
      'User-Role': 'ROLE_ADMIN',
      'Content-Type': mime,
    },
    params={
      'origin': origin,
      'title': ref.get('title', ''),
      'mime': mime,
    }
  )
  if not response.ok:
    print(f"Error {response.status_code}: {response.text}", file=sys.stderr)
    sys.exit(1)
  cache = response.json()
  def finish(latest):
    latest['tags'] = [t for t in latest.get('tags') or [] if not (t + '/').startswith(('_plugin/delta/ytdlp/', 'plugin/embed/', 'plugin/progress/', '_seal/delta/'))]
    if 'plugin/video' not in latest['tags']: latest['tags'].append('plugin/video')
    plugins = latest.get('plugins') or {}
    plugins.pop('plugin/embed', None)
    plugins['plugin/video'] = {**(plugins.get('plugin/video') or {}), 'url': cache['url']}
    latest['plugins'] = plugins
    return latest
  save_ref(ref, finish)
  print(json.dumps({'ref': []}))
finally:
  # Clean up both the base temp file and the downloaded file
  if os.path.exists(base_name):
    os.remove(base_name)
  if downloaded_file and os.path.exists(downloaded_file):
    os.remove(downloaded_file)
    `,
  },
};

export const ytdlpMetaDeltaPlugin: Plugin = {
  tag: '_plugin/delta/ytmeta',
  name: $localize`🔍️ Get Metadata`,
  config: {
    mod: $localize`▶️ YT-DLP`,
    version: 5,
    type: 'tool',
    default: false,
    generated: $localize`Generated by jasper-ui ${DateTime.now().toISO()}`,
    description: $localize`Fetches metadata and storyboards using yt-dlp.`,
    language: 'python',
    timeoutMs: 300_000,
    requirements: `
      yt-dlp
      requests
    `,
    subDiff: ['script'],
    adminForm: [{
      key: 'script',
      type: 'code',
      props: {
        label: $localize`Script:`,
        language: 'python',
      },
    }],
    // language=python
    script: `
import json
import os
import sys
import yt_dlp
${pythonSaveRef}
ref = json.load(sys.stdin)
plugins = ref.get('plugins', {})
embed = plugins.get('plugin/embed', {})
url = embed.get('url') or ref.get('url')

ydl_opts = {
    'quiet': True,
    'remote_components': ['ejs:github'],
    'js_runtimes': {'bun': {'path': os.environ['JASPER_NODE']}},
    'skip_download': True,
}

try:
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        info = ydl.extract_info(url, download=False)
except Exception as e:
    if 'This live event will begin in' in str(e):
        sys.exit(0)
    print(json.dumps({'error': str(e)}), file=sys.stderr)
    sys.exit(1)

def apply_metadata(ref, info):
    duration = info.get('duration')
    storyboards = [f for f in info.get('formats', []) if f.get('format_note') == 'storyboard']

    # Duration handling via tag (plugin/duration/...)
    if duration:
        m, s = divmod(duration, 60)
        h, m = divmod(m, 60)
        iso_dur = 'pt'
        if h > 0: iso_dur += f'{int(h)}h'
        if m > 0: iso_dur += f'{int(m)}m'
        iso_dur += f'{int(s)}s'

        tags = ref.get('tags', [])
        # Filter out old durations and add the newly fetched one
        tags = [t for t in tags if not t.startswith('plugin/duration/')]
        tags.append(f'plugin/duration/{iso_dur}')
        ref['tags'] = tags

    # Storyboard handling
    plugins = ref.get('plugins', {})
    if storyboards:
        # Target the best available storyboard spec
        # Pick the storyboard with the highest individual frame resolution
        spec = max(storyboards, key=lambda f: f.get('width', 0) * f.get('height', 0))
        # URL contains $M placeholder for fragment index; use fragment 0
        sb_url = spec.get('url', '').replace('$M', '0')
        if sb_url:
            sb_rows = int(spec.get('rows', 1))
            sb_cols = int(spec.get('columns', 1))
            plugins['plugin/thumbnail/storyboard'] = {
                'url': sb_url,
                'rows': sb_rows,
                'cols': sb_cols,
                'width': int(spec.get('width', 0)),
                'height': int(spec.get('height', 0)),
            }
            tags = ref.get('tags', [])
            if 'plugin/thumbnail/storyboard' not in tags:
                tags.append('plugin/thumbnail/storyboard')
                ref['tags'] = tags

    ref['plugins'] = plugins

output_refs = []
source_urls = []
if 'entries' in info:
    parent_tags = ref.get('tags', [])
    child_tags = [t for t in parent_tags if t == 'public' or t.startswith(('public/', '_user/', '+user/', 'user/'))]
    playlist_urls = {url, ref.get('url'), info.get('webpage_url')}
    for index, entry in enumerate(info['entries']):
        if not entry: continue
        entry_url = entry.get('webpage_url') or entry.get('url')
        if entry_url in playlist_urls:
            entry_url = entry.get('url')
        if not entry_url or entry_url in playlist_urls: continue
        child_ref = {
            'url': entry_url,
            'origin': ref.get('origin', ''),
            'title': entry.get('title') or f"Track {index + 1}",
            'tags': ['plugin/embed'] + child_tags,
            'plugins': {'plugin/embed': {'url': entry_url}},
        }
        apply_metadata(child_ref, entry)
        output_refs.append(child_ref)
        source_urls.append(entry_url)

def finish(latest):
    if 'entries' in info:
        latest['sources'] = source_urls
        latest['tags'] = [t for t in latest.get('tags') or [] if not (t + '/').startswith('plugin/embed/')]
        if 'plugin/playlist' not in latest['tags']:
            latest['tags'].append('plugin/playlist')
        latest['plugins'] = latest.get('plugins') or {}
        latest['plugins'].pop('plugin/embed', None)
    else:
        apply_metadata(latest, info)
    # Remove the yt trigger tag so it doesn't infinitely loop
    latest['tags'] = [t for t in latest.get('tags') or [] if not (t + '/').startswith('_plugin/delta/ytmeta/')]
    return latest

save_ref(ref, finish)
print(json.dumps({'ref': output_refs}))
`
  },
};

export const ytdlpMod: Mod = {
  plugin: [
    ytdlpDeltaPlugin,
    ytdlpMetaDeltaPlugin,
  ]
};
