name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t jasperkms/jasper-ui:$(date +%s)

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the testing image
      run: docker build . --file Dockerfile --target test --tag test
    - name: Run the test container
      run: docker run --name test test
    - name: Copy the tests from the container
      if: always()
      run: docker cp test:/tests tests
    - name: Publish Unit Test Results
      uses: dorny/test-reporter@v1.5.0
      if: always()
      with:
        name: Test Results
        path: "tests/*.xml"
        reporter: java-junit
