name: Release

on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Build
        run: npm ci && npm run build

      - name: Zip
        run: |
          echo "jasper-ui_${{ startsWith(github.ref, 'refs/tags/v') }}.zip" >> $RELEASE_FILE
          cd dist/jasper-ui/; zip -r ../../$RELEASE_FILE .

      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ startsWith(github.ref, 'refs/tags/v') }}
          draft: true
          prerelease: false

      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./$RELEASE_FILE
          asset_name: $RELEASE_FILE
          asset_content_type: application/zip
